import type { UnitSummary } from "@/lib/types"

export const BOOK = {
  title: "聊天聊不完",
  titleEn: "Chat Without End",
  subtitle: "120个中文情境 · 3600道会话题",
  subtitleEn: "120 Chinese situations, 3,600 conversation prompts",
  author: "解丽琪",
  authorEn: "Shelley Hsieh",
  publisher: "新学林",
  year: 2023,
  isbnSimplified: "978-986-526-418-5",
  narrators: ["欧喜强", "胡砚涵"],
  edition: "简体字版",
} as const

export const UNITS: UnitSummary[] = [
  {
    id: 1,
    title: "家庭生活",
    titleEn: "Family life",
    status: "ready",
    lessonCount: 10,
    topics: [
      { id: "1-1", title: "休息睡觉", titleEn: "Rest and sleep" },
      { id: "1-2", title: "作息时间", titleEn: "Daily schedule" },
      { id: "1-3", title: "家务", titleEn: "Housework" },
      { id: "1-4", title: "婚姻", titleEn: "Marriage" },
      { id: "1-5", title: "家人和家庭活动", titleEn: "Family and family activities" },
      { id: "1-6", title: "生儿育女", titleEn: "Having and raising children" },
      { id: "1-7", title: "派对", titleEn: "Parties" },
      { id: "1-8", title: "购物", titleEn: "Shopping" },
      { id: "1-9", title: "兴趣爱好", titleEn: "Hobbies" },
      { id: "1-10", title: "个人习惯", titleEn: "Personal habits" },
    ],
  },
  {
    id: 2,
    title: "学校生活",
    titleEn: "School life",
    status: "planned",
    lessonCount: 6,
    topics: [
      { id: "2-1", title: "老师同学", titleEn: "Teachers and classmates" },
      { id: "2-2", title: "作业", titleEn: "Homework" },
      { id: "2-3", title: "课外活动", titleEn: "Extracurriculars" },
      { id: "2-4", title: "上学", titleEn: "Going to school" },
      { id: "2-5", title: "便当和营养午餐", titleEn: "Bento and school lunch" },
      { id: "2-6", title: "外语学习", titleEn: "Learning a foreign language" },
    ],
  },
  {
    id: 3,
    title: "职场",
    titleEn: "The workplace",
    status: "planned",
    lessonCount: 3,
    topics: [
      { id: "3-1", title: "工作", titleEn: "Work" },
      { id: "3-2", title: "人格特质和智商", titleEn: "Personality and intelligence" },
      { id: "3-3", title: "模拟求职面试", titleEn: "Mock job interview" },
    ],
  },
  {
    id: 4,
    title: "自我认识",
    titleEn: "Knowing yourself",
    status: "planned",
    lessonCount: 7,
    topics: [
      { id: "4-1", title: "自我介绍", titleEn: "Self-introduction" },
      { id: "4-2", title: "经常和不常做的事", titleEn: "Things you do and don’t do" },
      { id: "4-3", title: "恋爱和约会", titleEn: "Love and dating" },
      { id: "4-4", title: "喜好和厌恶", titleEn: "Likes and dislikes" },
      { id: "4-5", title: "愿望", titleEn: "Wishes" },
      { id: "4-6", title: "到目前为止的人生", titleEn: "Life so far" },
      { id: "4-7", title: "让陌生人迅速相爱的三十六个问题", titleEn: "36 questions for strangers" },
    ],
  },
  {
    id: 5,
    title: "饮食文化",
    titleEn: "Food culture",
    status: "planned",
    lessonCount: 5,
    topics: [
      { id: "5-1", title: "饮食习惯", titleEn: "Eating habits" },
      { id: "5-2", title: "披萨", titleEn: "Pizza" },
      { id: "5-3", title: "茶和咖啡", titleEn: "Tea and coffee" },
      { id: "5-4", title: "摊贩夜市小吃", titleEn: "Street food and night markets" },
      { id: "5-5", title: "素食", titleEn: "Vegetarian food" },
    ],
  },
  {
    id: 6,
    title: "节日庆典",
    titleEn: "Festivals",
    status: "planned",
    lessonCount: 5,
    topics: [
      { id: "6-1", title: "各国节日庆典", titleEn: "Festivals around the world" },
      { id: "6-2", title: "华人的节日", titleEn: "Chinese festivals" },
      { id: "6-3", title: "圣诞节", titleEn: "Christmas" },
      { id: "6-4", title: "新年", titleEn: "New Year" },
      { id: "6-5", title: "节气", titleEn: "Solar terms" },
    ],
  },
  {
    id: 7,
    title: "跨文化",
    titleEn: "Cross-culture",
    status: "planned",
    lessonCount: 7,
    topics: [
      { id: "7-1", title: "文化差异", titleEn: "Cultural differences" },
      { id: "7-2", title: "礼貌", titleEn: "Politeness" },
      { id: "7-3", title: "礼物", titleEn: "Gifts" },
      { id: "7-4", title: "颜色", titleEn: "Color" },
      { id: "7-5", title: "着装要求", titleEn: "Dress codes" },
      { id: "7-6", title: "感恩", titleEn: "Gratitude" },
      { id: "7-7", title: "隐私", titleEn: "Privacy" },
    ],
  },
  {
    id: 8,
    title: "运动",
    titleEn: "Sports",
    status: "planned",
    lessonCount: 3,
    topics: [
      { id: "8-1", title: "球类运动", titleEn: "Ball sports" },
      { id: "8-2", title: "奥运", titleEn: "The Olympics" },
      { id: "8-3", title: "运动健身", titleEn: "Exercise and fitness" },
    ],
  },
  {
    id: 9,
    title: "国际关系和军政",
    titleEn: "International affairs",
    status: "planned",
    lessonCount: 4,
    topics: [
      { id: "9-1", title: "难民和人权", titleEn: "Refugees and human rights" },
      { id: "9-2", title: "兵役", titleEn: "Military service" },
      { id: "9-3", title: "经济", titleEn: "The economy" },
      { id: "9-4", title: "世界和平", titleEn: "World peace" },
    ],
  },
  {
    id: 10,
    title: "传播媒体",
    titleEn: "Media",
    status: "planned",
    lessonCount: 10,
    topics: [
      { id: "10-1", title: "电视", titleEn: "Television" },
      { id: "10-2", title: "电影", titleEn: "Movies" },
      { id: "10-3", title: "八卦与谣言", titleEn: "Gossip and rumors" },
      { id: "10-4", title: "报章杂志", titleEn: "Newspapers and magazines" },
      { id: "10-5", title: "虚拟世界", titleEn: "The virtual world" },
      { id: "10-6", title: "自媒体和网红", titleEn: "Self-media and influencers" },
      { id: "10-7", title: "广播和聊天室", titleEn: "Radio and chat rooms" },
      { id: "10-8", title: "动画和漫画", titleEn: "Animation and comics" },
      { id: "10-9", title: "书和文字", titleEn: "Books and writing" },
      { id: "10-10", title: "笑话", titleEn: "Jokes" },
    ],
  },
  {
    id: 11,
    title: "公卫和健康",
    titleEn: "Public health",
    status: "planned",
    lessonCount: 5,
    topics: [
      { id: "11-1", title: "长寿和死亡", titleEn: "Longevity and death" },
      { id: "11-2", title: "健康", titleEn: "Health" },
      { id: "11-3", title: "体重控制", titleEn: "Weight control" },
      { id: "11-4", title: "食安问题", titleEn: "Food safety" },
      { id: "11-5", title: "传染病和防疫", titleEn: "Epidemics and prevention" },
    ],
  },
  {
    id: 12,
    title: "情绪",
    titleEn: "Emotions",
    status: "planned",
    lessonCount: 4,
    topics: [
      { id: "12-1", title: "心情感受", titleEn: "Feelings" },
      { id: "12-2", title: "压力", titleEn: "Stress" },
      { id: "12-3", title: "不满与抱怨", titleEn: "Complaints" },
      { id: "12-4", title: "恐惧", titleEn: "Fear" },
    ],
  },
  {
    id: 13,
    title: "科学与迷信",
    titleEn: "Science and superstition",
    status: "planned",
    lessonCount: 7,
    topics: [
      { id: "13-1", title: "超自然", titleEn: "The supernatural" },
      { id: "13-2", title: "发明与创意", titleEn: "Invention and creativity" },
      { id: "13-3", title: "科学技术", titleEn: "Science and technology" },
      { id: "13-4", title: "迷信、禁忌与风水", titleEn: "Superstition, taboos, and feng shui" },
      { id: "13-5", title: "预言和算命", titleEn: "Prophecy and fortune-telling" },
      { id: "13-6", title: "美容抗老", titleEn: "Beauty and anti-aging" },
      { id: "13-7", title: "外太空和不明飞行物", titleEn: "Outer space and UFOs" },
    ],
  },
  {
    id: 14,
    title: "不幸的事",
    titleEn: "Misfortune",
    status: "planned",
    lessonCount: 6,
    topics: [
      { id: "14-1", title: "报警", titleEn: "Calling the police" },
      { id: "14-2", title: "重大犯罪", titleEn: "Serious crime" },
      { id: "14-3", title: "剽窃和欺骗", titleEn: "Plagiarism and cheating" },
      { id: "14-4", title: "自然灾害", titleEn: "Natural disasters" },
      { id: "14-5", title: "人为灾害", titleEn: "Man-made disasters" },
      { id: "14-6", title: "事故", titleEn: "Accidents" },
    ],
  },
  {
    id: 15,
    title: "慈善",
    titleEn: "Charity",
    status: "planned",
    lessonCount: 2,
    topics: [
      { id: "15-1", title: "做慈善", titleEn: "Doing charity" },
      { id: "15-2", title: "领养", titleEn: "Adoption" },
    ],
  },
  {
    id: 16,
    title: "思想和价值观",
    titleEn: "Thoughts and values",
    status: "planned",
    lessonCount: 10,
    topics: [
      { id: "16-1", title: "快乐", titleEn: "Happiness" },
      { id: "16-2", title: "建议", titleEn: "Advice" },
      { id: "16-3", title: "信仰和社团", titleEn: "Faith and groups" },
      { id: "16-4", title: "钱和理财", titleEn: "Money and finance" },
      { id: "16-5", title: "善意的谎言", titleEn: "White lies" },
      { id: "16-6", title: "成见、先入观、刻板印象", titleEn: "Prejudice and stereotypes" },
      { id: "16-7", title: "交换", titleEn: "Exchange" },
      { id: "16-8", title: "二选一，我宁愿", titleEn: "Would you rather" },
      { id: "16-9", title: "品牌", titleEn: "Brands" },
      { id: "16-10", title: "两难问题", titleEn: "Dilemmas" },
    ],
  },
  {
    id: 17,
    title: "动植物",
    titleEn: "Animals and plants",
    status: "planned",
    lessonCount: 3,
    topics: [
      { id: "17-1", title: "动物", titleEn: "Animals" },
      { id: "17-2", title: "宠物", titleEn: "Pets" },
      { id: "17-3", title: "植物", titleEn: "Plants" },
    ],
  },
  {
    id: 18,
    title: "自然环境",
    titleEn: "The natural world",
    status: "planned",
    lessonCount: 2,
    topics: [
      { id: "18-1", title: "地理和气候", titleEn: "Geography and climate" },
      { id: "18-2", title: "环保和地球日", titleEn: "Environment and Earth Day" },
    ],
  },
  {
    id: 19,
    title: "艺术",
    titleEn: "The arts",
    status: "planned",
    lessonCount: 4,
    topics: [
      { id: "19-1", title: "街头文化艺术", titleEn: "Street culture and art" },
      { id: "19-2", title: "音乐", titleEn: "Music" },
      { id: "19-3", title: "视觉艺术", titleEn: "Visual art" },
      { id: "19-4", title: "艺术生活", titleEn: "Art in daily life" },
    ],
  },
  {
    id: 20,
    title: "社会",
    titleEn: "Society",
    status: "planned",
    lessonCount: 6,
    topics: [
      { id: "20-1", title: "邻里", titleEn: "Neighborhoods" },
      { id: "20-2", title: "城市街道", titleEn: "City streets" },
      { id: "20-3", title: "交通", titleEn: "Transportation" },
      { id: "20-4", title: "青少年和青年", titleEn: "Youth" },
      { id: "20-5", title: "时尚潮流", titleEn: "Fashion" },
      { id: "20-6", title: "退休养老", titleEn: "Retirement" },
    ],
  },
  {
    id: 21,
    title: "世界观",
    titleEn: "Worldview",
    status: "planned",
    lessonCount: 9,
    topics: [
      { id: "21-1", title: "中日的差异", titleEn: "China and Japan" },
      { id: "21-2", title: "旅游", titleEn: "Travel" },
      { id: "21-3", title: "背包旅行", titleEn: "Backpacking" },
      { id: "21-4", title: "博览会和综合度假区", titleEn: "Expos and resorts" },
      { id: "21-5", title: "美国和欧洲", titleEn: "The US and Europe" },
      { id: "21-6", title: "中国", titleEn: "China" },
      { id: "21-7", title: "台湾", titleEn: "Taiwan" },
      { id: "21-8", title: "移民", titleEn: "Immigration" },
      { id: "21-9", title: "国际婚姻和移工", titleEn: "International marriage and migrant work" },
    ],
  },
  {
    id: 22,
    title: "照片故事",
    titleEn: "Photo stories",
    status: "planned",
    lessonCount: 9,
    topics: [
      { id: "22-1", title: "天空之镜", titleEn: "Mirror of the sky" },
      { id: "22-2", title: "森林浴", titleEn: "Forest bathing" },
      { id: "22-3", title: "做粽子", titleEn: "Making zongzi" },
      { id: "22-4", title: "鱼疗", titleEn: "Fish spa" },
      { id: "22-5", title: "七爷八爷", titleEn: "The Seventh and Eighth Lords" },
      { id: "22-6", title: "意大利料理", titleEn: "Italian food abroad" },
      { id: "22-7", title: "待用餐", titleEn: "Pending meals" },
      { id: "22-8", title: "卤蛋便当", titleEn: "Braised-egg bento" },
      { id: "22-9", title: "无人车送货", titleEn: "Driverless delivery" },
    ],
  },
]

export function getUnit(id: number) {
  return UNITS.find((unit) => unit.id === id)
}

export function totalTopics() {
  return UNITS.reduce((sum, unit) => sum + unit.topics.length, 0)
}
