/**
 * RULE: every dialogue line is built with notedLine(LESSON_X_Y_LINE_NOTES, …).
 * Do not add a local line() helper that skips mini lessons. Keys must match 汉字 exactly.
 */
import {
  LESSON_1_1_CHUNKS,
  LESSON_1_1_CORE_VOCAB,
  LESSON_1_1_FILL_BLANKS,
  LESSON_1_1_GRAMMAR_FOCUS,
  LESSON_1_1_LINE_NOTES,
  LESSON_1_1_PRACTICE,
  LESSON_1_1_SLEEP_FAMILY,
} from "@/content/lessons/1-1-notes"
import {
  LESSON_1_2_CHUNKS,
  LESSON_1_2_CORE_VOCAB,
  LESSON_1_2_FAMILY,
  LESSON_1_2_FILL_BLANKS,
  LESSON_1_2_GRAMMAR_FOCUS,
  LESSON_1_2_LINE_NOTES,
  LESSON_1_2_PRACTICE,
} from "@/content/lessons/1-2-notes"
import {
  LESSON_1_3_CHUNKS,
  LESSON_1_3_CORE_VOCAB,
  LESSON_1_3_FAMILY,
  LESSON_1_3_FILL_BLANKS,
  LESSON_1_3_GRAMMAR_FOCUS,
  LESSON_1_3_LINE_NOTES,
  LESSON_1_3_PRACTICE,
} from "@/content/lessons/1-3-notes"
import {
  LESSON_1_4_CHUNKS,
  LESSON_1_4_CORE_VOCAB,
  LESSON_1_4_FAMILY,
  LESSON_1_4_FILL_BLANKS,
  LESSON_1_4_GRAMMAR_FOCUS,
  LESSON_1_4_LINE_NOTES,
  LESSON_1_4_PRACTICE,
} from "@/content/lessons/1-4-notes"
import {
  LESSON_1_5_CHUNKS,
  LESSON_1_5_CORE_VOCAB,
  LESSON_1_5_FAMILY,
  LESSON_1_5_FILL_BLANKS,
  LESSON_1_5_GRAMMAR_FOCUS,
  LESSON_1_5_LINE_NOTES,
  LESSON_1_5_PRACTICE,
} from "@/content/lessons/1-5-notes"
import { notedLine } from "@/content/lessons/note-helpers"
import type { Lesson, Question, VocabItem } from "@/lib/types"

function v(hanzi: string, en: string): VocabItem {
  return { hanzi, en }
}

function q(n: number, hanzi: string, en: string, kind?: Question["kind"]): Question {
  return kind ? { n, hanzi, en, kind } : { n, hanzi, en }
}

export const UNIT_1_LESSONS: Lesson[] = [
  {
    id: "1-1",
    unitId: 1,
    title: "休息睡觉",
    titleEn: "Rest and sleep",
    pageStart: 2,
    audioId: "1-1",
    scenario: {
      time: "早上9点前",
      timeEn: "Before 9 a.m.",
      location: "公司茶水间",
      locationEn: "Office pantry",
      participants: "和同事",
      participantsEn: "With a colleague",
      topic: "喝咖啡聊睡眠",
      topicEn: "Coffee and chatting about sleep",
    },
    dialogue: [
      notedLine(LESSON_1_1_LINE_NOTES, "stage", "（打呵欠）", "(Yawns)"),
      notedLine(LESSON_1_1_LINE_NOTES, "B", "怎么一大早就打呵欠？", "Why are you yawning so early in the morning?"),
      notedLine(LESSON_1_1_LINE_NOTES, "A", "昨天没睡好。", "I didn’t sleep well last night."),
      notedLine(LESSON_1_1_LINE_NOTES, "B", "怎么了？", "What happened? / What’s wrong?"),
      notedLine(LESSON_1_1_LINE_NOTES,
        "A",
        "我做了个恶梦，梦见有人在追我，一直追、一直追，我拼命跑，最后掉进一个山谷。",
        "I had a nightmare. I dreamed that someone was chasing me. They kept chasing and chasing me. I ran for my life, and eventually I fell into a valley.",
      ),
      notedLine(LESSON_1_1_LINE_NOTES,
        "B",
        "是不是压力太大了？你平常睡得好吗？",
        "Could it be that you’re under too much stress? Do you normally sleep well?",
      ),
      notedLine(LESSON_1_1_LINE_NOTES, "A", "不太好，总是觉得睡眠不足。", "Not very well. I always feel like I don’t get enough sleep."),
      notedLine(LESSON_1_1_LINE_NOTES,
        "B",
        "我听一个睡眠专家的医生说，早上多晒太阳，可以帮助睡眠。",
        "I heard a doctor who specializes in sleep say that getting more sunlight in the morning can help with sleep.",
      ),
      notedLine(LESSON_1_1_LINE_NOTES,
        "A",
        "真的吗？我可能真的太阳晒不够。你呢？你都睡得好吗？",
        "Really? Maybe I really don’t get enough sunlight. What about you? Do you usually sleep well?",
      ),
      notedLine(LESSON_1_1_LINE_NOTES,
        "B",
        "几乎都是5分钟内睡着，一觉到天亮。",
        "I almost always fall asleep within five minutes and sleep straight through until morning.",
      ),
      notedLine(LESSON_1_1_LINE_NOTES, "A", "真羡慕！", "I’m so jealous!"),
    ],
    coreVocabulary: LESSON_1_1_CORE_VOCAB,
    chunks: LESSON_1_1_CHUNKS,
    expressionFamily: {
      title: "一套睡眠说法",
      titleEn: "One family of sleep expressions — learn them together",
      items: LESSON_1_1_SLEEP_FAMILY,
    },
    grammarFocus: LESSON_1_1_GRAMMAR_FOCUS,
    practiceSentences: LESSON_1_1_PRACTICE,
    fillBlanks: LESSON_1_1_FILL_BLANKS,
    vocabulary: [
      v("失眠", "insomnia"),
      v("深度睡眠", "deep sleep"),
      v("很好睡", "easy to sleep / a good sleeper"),
      v("不好睡", "hard to sleep"),
      v("睡得着", "able to fall asleep"),
      v("睡不着", "unable to fall asleep"),
      v("数羊", "count sheep"),
      v("打鼾", "snore"),
      v("认床", "unable to sleep in a new bed"),
      v("精油", "essential oil"),
      v("被追的梦", "a dream of being chased"),
      v("周公解梦", "dream interpretation"),
      v("入睡", "fall asleep"),
      v("床垫", "mattress"),
      v("枕头", "pillow"),
    ],
    questions: [
      q(1, "你每晚大约睡几个小时？", "About how many hours do you sleep each night?"),
      q(2, "打鼾是什么？你或你家人打鼾吗？", "What is snoring? Do you or anyone in your family snore?"),
      q(3, "你是浅眠者还是深眠者？", "Are you a light sleeper or a deep sleeper?"),
      q(4, "你曾经失眠吗？有失眠症吗？", "Have you ever had insomnia? Do you have insomnia?"),
      q(5, "你曾经因失眠去看医生吗？", "Have you ever seen a doctor because of insomnia?"),
      q(
        6,
        "什么会让你在晚上醒来？（例如：太多事、咖啡、伴侣的打鼾、邻居的声音、不舒服的床、炎热的夏天……）",
        "What wakes you up at night? (Too much on your mind, coffee, a partner’s snoring, neighbors, an uncomfortable bed, a hot summer…)",
      ),
      q(7, "在看电视或阅读时你常睡着吗？", "Do you often fall asleep while watching TV or reading?"),
      q(8, "你常常觉得睡眠不足吗？", "Do you often feel you don’t get enough sleep?"),
      q(9, "你是否正在使用或曾经使用过任何帮助睡觉的特殊方法？（什么？）", "Are you using or have you used any special methods to help you sleep? What?"),
      q(10, "朋友失眠的话，你会给什么建议？", "If a friend has insomnia, what advice would you give?"),
      q(11, "你需要闹钟来唤醒吗？", "Do you need an alarm clock to wake up?"),
      q(12, "你有没有睡午觉的习惯？（有的话，在哪里？睡多久？）", "Do you nap? If so, where, and for how long?"),
      q(13, "你睡床还是在地板或榻榻米上铺垫被睡？", "Do you sleep in a bed, or on a futon on the floor or tatami?"),
      q(14, "什么是认床？你会认床吗？", "What does “认床” mean? Do you have trouble sleeping in a new bed?"),
      q(15, "你有一个经常做的梦吗？", "Do you have a recurring dream?"),
      q(16, "你小时候或你孩子有没有“睡前仪式”？", "Did you or your child have a bedtime ritual?"),
      q(17, "你做过恶梦吗？", "Have you had nightmares?"),
      q(18, "你曾经梦游过吗？你有亲戚或朋友梦游过吗？", "Have you ever sleepwalked? Have relatives or friends?"),
      q(19, "看到别人梦游你会怎么做？", "What would you do if you saw someone sleepwalking?"),
      q(20, "你相信可以解释梦吗？你曾经为了解释自己的梦去找资料或问人吗？", "Do you believe dreams can be interpreted? Have you ever looked things up or asked someone about a dream?"),
      q(21, "请说一个你做过的愉快或奇怪的梦。", "Tell a pleasant or strange dream you have had."),
      q(22, "你很重视床垫和枕头的品质〔质量〕和设计吗？", "Do you care a lot about the quality and design of mattresses and pillows?"),
      q(23, "你知道几点左右入睡是最健康的吗？你做得到吗？", "Do you know the healthiest time to fall asleep? Can you do it?"),
      q(24, "有些大企业设有午休室，给员工睡午觉，你觉得怎么样？", "Some big companies have nap rooms for staff. What do you think?"),
      q(25, "如果要设计一间午休室，你会怎么设计？", "If you were designing a nap room, how would you design it?"),
      q(26, "如果不用考虑金钱和房间大小，你理想中的寝室是什么样的？", "If money and room size didn’t matter, what would your ideal bedroom be like?"),
    ],
  },
  {
    id: "1-2",
    unitId: 1,
    title: "作息时间",
    titleEn: "Daily schedule",
    pageStart: 4,
    audioId: "1-2",
    scenario: {
      time: "下午4点刚下课",
      timeEn: "Just after class at 4 p.m.",
      location: "教室",
      locationEn: "Classroom",
      participants: "和大学同学",
      participantsEn: "With a university classmate",
      topic: "聊时间规划",
      topicEn: "Chatting about time planning",
    },
    dialogue: [
      notedLine(LESSON_1_2_LINE_NOTES, "A", "你交报告了吗？", "Have you turned in the report?"),
      notedLine(LESSON_1_2_LINE_NOTES, "B", "还没，我的坏习惯，都要拖到最后一刻。你呢？", "Not yet. My bad habit — I always drag it out until the last minute. How about you?"),
      notedLine(LESSON_1_2_LINE_NOTES, "A", "交了。我都是按时完成的，不早一点做完不安心。", "I turned it in. I always finish on time. I don’t feel at ease if I don’t finish a bit early."),
      notedLine(LESSON_1_2_LINE_NOTES, "B", "如果一天有25个小时就好了。", "If only a day had 25 hours."),
      notedLine(LESSON_1_2_LINE_NOTES, "A", "如果一天有25个小时，你要用多的那一小时做什么？", "If a day had 25 hours, what would you do with the extra hour?"),
      notedLine(LESSON_1_2_LINE_NOTES, "B", "可以看电影、睡觉。", "Watch movies, sleep."),
      notedLine(LESSON_1_2_LINE_NOTES, "A", "结果报告还是最后一刻才完成？", "So the report would still get finished at the last minute?"),
      notedLine(LESSON_1_2_LINE_NOTES, "B", "我得向你学习学习。你都怎么规划时间的？我总觉得时间不够用。", "I should learn from you. How do you plan your time? I always feel there isn’t enough."),
      notedLine(LESSON_1_2_LINE_NOTES, "A", "我习惯用记事手册手写，你看。", "I’m used to writing in a paper planner. Look."),
      notedLine(LESSON_1_2_LINE_NOTES, "B", "真有条理，好像用写的比用手机更能提醒自己。我也去买一本好了。", "So organized. Writing it down seems more of a reminder than a phone. I’ll go buy one too."),
    ],
    coreVocabulary: LESSON_1_2_CORE_VOCAB,
    chunks: LESSON_1_2_CHUNKS,
    expressionFamily: {
      title: "一套完成／拖延说法",
      titleEn: "One family of finish / put-off expressions — learn them together",
      items: LESSON_1_2_FAMILY,
    },
    grammarFocus: LESSON_1_2_GRAMMAR_FOCUS,
    practiceSentences: LESSON_1_2_PRACTICE,
    fillBlanks: LESSON_1_2_FILL_BLANKS,
    vocabulary: [
      v("守时", "punctual"),
      v("夜猫子", "night owl"),
      v("猫头鹰", "owl"),
      v("时光机", "time machine"),
      v("按时", "on time"),
      v("作息正常", "a regular routine"),
      v("时间", "time"),
      v("计划表", "schedule / planner"),
      v("格言", "saying / proverb"),
      v("日出而作，日入而息", "work at sunrise, rest at sunset"),
    ],
    questions: [
      q(1, "请描述你一天的作息。", "Describe your daily routine."),
      q(2, "你几点睡觉？几点起床？", "What time do you go to bed? What time do you get up?"),
      q(3, "你善于利用时间或管理时间吗？", "Are you good at using or managing time?"),
      q(4, "贵国人民普遍喜欢迟到还是早到？", "In your country, do people tend to arrive late or early?"),
      q(5, "在贵国文化中，太早到和太晚到哪个比较没有礼貌？", "In your culture, which is ruder: arriving too early or too late?"),
      q(6, "你一天中最忙的时候是？最喜欢的时间是？", "When is the busiest part of your day? Your favorite time?"),
      q(7, "什么事情占用你大部分的时间？", "What takes up most of your time?"),
      q(8, "你是否每周都做时间规划？（用什么工具？手机、计算机，还是记事本？）", "Do you plan your week? With what — phone, computer, or notebook?"),
      q(9, "你总是守时吗？", "Are you always punctual?"),
      q(10, "普通朋友迟到多久你会生气？如果是男／女朋友呢？", "How late can a regular friend be before you get angry? What about a boyfriend or girlfriend?"),
      q(11, "约会时等多久你会离开？", "How long will you wait for a date before leaving?"),
      q(12, "你的工作（或学校）几点开始，几点结束？", "What time does work or school start and end?"),
      q(13, "你是夜猫子还是喜欢早起？", "Are you a night owl or a morning person?"),
      q(14, "如果一天有25个小时，你要用多的那一小时做什么？", "If a day had 25 hours, what would you do with the extra hour?"),
      q(15, "你想要有更多的时间还是更多的钱？为什么？", "Would you rather have more time or more money? Why?"),
      q(16, "你觉得一周工作四天怎么样？", "What do you think of a four-day work week?"),
      q(17, "你最喜欢星期几？最不喜欢星期几？", "Which day of the week do you like most? Least?"),
      q(18, "如果你有时光机，可以选择到过去或未来的一段时间，你要选什么？为什么？", "If you had a time machine to a stretch of the past or future, which would you choose, and why?"),
      q(19, "如果能回到过去，你想做什么？", "If you could go back to the past, what would you want to do?"),
      q(20, "如果能到未来，你想做什么？", "If you could go to the future, what would you want to do?"),
      q(21, "如果你的时光机是一去不回的，你想去过去还是未来？为什么？", "If the time machine were one-way, would you go to the past or the future? Why?"),
      q(22, "你知道哪些有关时间的格言？", "What proverbs about time do you know?"),
      q(23, "你通常会尽早把事情做完还是拖到最后一刻？", "Do you usually finish things early or leave them until the last minute?"),
      q(
        24,
        "如果你是一个守时的人，而你的伴侣不是，参加聚会时，常因为等伴侣而迟到和吵架。你会怎么做？",
        "If you are punctual and your partner isn’t, and you often argue after waiting and arriving late to parties, what would you do?",
      ),
    ],
  },
  {
    id: "1-3",
    unitId: 1,
    title: "家务",
    titleEn: "Housework",
    pageStart: 6,
    audioId: "1-3",
    scenario: {
      time: "5点半下班前",
      timeEn: "Before leaving work at 5:30",
      location: "办公室",
      locationEn: "Office",
      participants: "和同事",
      participantsEn: "With a colleague",
      topic: "因家务拒绝邀约",
      topicEn: "Turning down an invite because of housework",
    },
    dialogue: [
      notedLine(LESSON_1_3_LINE_NOTES, "A", "下班后去喝一杯吧？", "Want to grab a drink after work?"),
      notedLine(LESSON_1_3_LINE_NOTES, "B", "不好意思，今天轮到我煮饭。", "Sorry — it’s my turn to cook today."),
      notedLine(LESSON_1_3_LINE_NOTES, "A", "你家用轮的？你负责星期几的？", "You take turns at home? Which days are yours?"),
      notedLine(LESSON_1_3_LINE_NOTES, "B", "周末。你呢？你帮忙家务吗？", "Weekends. What about you? Do you help with housework?"),
      notedLine(LESSON_1_3_LINE_NOTES, "A", "我负责洗碗和倒垃圾。我太太喜欢煮饭，可是不爱洗碗。", "I do the dishes and take out the trash. My wife likes cooking but hates washing dishes."),
      notedLine(LESSON_1_3_LINE_NOTES, "B", "买一台洗碗机吧，很方便。", "Buy a dishwasher. It’s convenient."),
      notedLine(LESSON_1_3_LINE_NOTES, "A", "还有我们都不喜欢熨衣服，熨衣服是最没有意思的家务。", "And neither of us likes ironing. Ironing is the most boring chore."),
      notedLine(LESSON_1_3_LINE_NOTES, "B", "我也不喜欢熨衣服，要是有个机器人就好了！", "I don’t like ironing either. If only we had a robot!"),
      notedLine(LESSON_1_3_LINE_NOTES,
        "A",
        "应该在不久后的未来就会有了，现在不是已经有扫地机器人、煮饭机器人，和照护老人的机器人了？",
        "There probably will be, soon. Don’t we already have robot vacuums, cooking robots, and robots that care for the elderly?",
      ),
      notedLine(LESSON_1_3_LINE_NOTES, "B", "我希望有机器人包办所有的家务！", "I wish a robot would take over all the housework!"),
    ],
    coreVocabulary: LESSON_1_3_CORE_VOCAB,
    chunks: LESSON_1_3_CHUNKS,
    expressionFamily: {
      title: "一套家务说法",
      titleEn: "One family of housework expressions — learn them together",
      items: LESSON_1_3_FAMILY,
    },
    grammarFocus: LESSON_1_3_GRAMMAR_FOCUS,
    practiceSentences: LESSON_1_3_PRACTICE,
    fillBlanks: LESSON_1_3_FILL_BLANKS,
    vocabulary: [
      v("家务", "housework"),
      v("职责", "duty / responsibility"),
      v("报酬", "pay / compensation"),
      v("喜欢", "to like"),
      v("厌恶", "to dislike / loathe"),
      v("值多少钱", "how much it’s worth"),
      v("打扫", "to clean"),
      v("熨衣服", "to iron clothes"),
      v("佣人", "domestic helper"),
      v("机器人", "robot"),
      v("外劳", "migrant worker"),
      v("帮忙", "to help"),
      v("家电", "home appliances"),
      v("吸尘器", "vacuum cleaner"),
      v("收纳整理", "storage and organizing"),
    ],
    questions: [
      q(1, "你能说出一些每天需要做的家务吗？", "Can you name some chores that need doing every day?"),
      q(2, "你负责什么家务？", "Which chores are you responsible for?"),
      q(3, "你不喜欢做哪些家务？", "Which chores do you dislike?"),
      q(4, "依照你喜欢和厌恶的程度，给各项家务分级。（1是最讨厌，10是最喜欢。）", "Rate chores from 1 (hate most) to 10 (like most)."),
      q(5, "你如何决定孩子的家务活？", "How do you decide children’s chores?"),
      q(6, "你的家人如何决定由谁来做家务？", "How does your family decide who does the housework?"),
      q(7, "你做家务有报酬吗？你觉得做家务应该有报酬吗？", "Are you paid for housework? Should housework be paid?"),
      q(8, "如果做家务可以得到报酬，做一个表格标示每一项家务值多少钱。", "If housework were paid, make a table of how much each chore is worth."),
      q(9, "你平常几点回家？回家后第一件事是做什么？", "What time do you usually get home? What’s the first thing you do?"),
      q(10, "回家后最讨厌做的事是什么？", "What’s the thing you hate doing most after getting home?"),
      q(11, "你喜欢打扫房间吗？", "Do you like cleaning the house?"),
      q(12, "你家通常是谁做菜洗碗？", "Who usually cooks and does the dishes at your house?"),
      q(13, "你自己的衣服自己洗吗？你给家人洗衣服吗？", "Do you wash your own clothes? Do you wash clothes for family?"),
      q(14, "你的祖父母会帮忙做家务吗？", "Do your grandparents help with housework?"),
      q(15, "你会熨衣服吗？你经常熨衣服吗？", "Can you iron? Do you iron often?"),
      q(16, "你在屋外做哪些家务活？", "What outdoor chores do you do?"),
      q(17, "你能想到一些小孩不能做的危险家务吗？", "What dangerous chores should children not do?"),
      q(18, "如果你只能买这两种东西中的一种，你会选择洗碗机还是洗衣机？", "If you could buy only one, dishwasher or washing machine?"),
      q(19, "如果你只能买这两种东西中的一种，你会选择洗衣机还是电冰箱？", "If you could buy only one, washing machine or fridge?"),
      q(20, "如果没有佣人或其他人在家里帮助你，你认为你能活多久？", "If no helper or anyone else at home helped you, how long do you think you’d last?"),
      q(21, "小孩做家务应该给钱吗？", "Should children be paid for chores?"),
      q(22, "如果你可以让一个机器人来做你所有的家务，你会要它做什么？", "If a robot did all your housework, what would you have it do?"),
      q(23, "你曾经自己一个人在家，找不到东西吗？最常找不到的是什么？", "Have you ever been home alone and couldn’t find something? What do you lose most often?"),
      q(24, "交往中的男女朋友去对方家庭做客，应该主动帮忙做家事吗？", "When dating, should you help with chores when visiting the other person’s family?"),
      q(25, "你家请过佣人吗？如果不考虑金钱，你想请佣人吗？", "Has your family hired a helper? If money weren’t an issue, would you want one?"),
      q(26, "推荐一种你觉得最好用的、可以提高家务效率的秘诀或工具。", "Recommend a trick or tool that makes housework more efficient."),
    ],
  },
  {
    id: "1-4",
    unitId: 1,
    title: "婚姻",
    titleEn: "Marriage",
    pageStart: 8,
    audioId: "1-4",
    scenario: {
      time: "晚上8点",
      timeEn: "8 p.m.",
      location: "餐厅",
      locationEn: "Restaurant",
      participants: "和朋友",
      participantsEn: "With a friend",
      topic: "邀约参加未婚联谊活动",
      topicEn: "Inviting someone to a singles mixer",
    },
    dialogue: [
      notedLine(LESSON_1_4_LINE_NOTES, "A", "你现在有女朋友吗？这周末有个未婚联谊要不要一起去？", "Do you have a girlfriend now? There’s a singles mixer this weekend — want to go together?"),
      notedLine(LESSON_1_4_LINE_NOTES, "B", "联谊？听起来挺好玩的，可是我还不想结婚。", "A mixer? Sounds fun, but I don’t want to get married yet."),
      notedLine(LESSON_1_4_LINE_NOTES,
        "A",
        "不一定要急着结婚，先交个朋友也不错。我想看看能不能在35岁前找到另一半。",
        "You don’t have to rush into marriage. Making friends is fine too. I want to see if I can find a partner before 35.",
      ),
      notedLine(LESSON_1_4_LINE_NOTES, "B", "你理想伴侣的条件是什么？", "What are your conditions for an ideal partner?"),
      notedLine(LESSON_1_4_LINE_NOTES, "A", "温柔体贴、个性好就好了。", "Gentle, considerate, a good personality — that’s enough."),
      notedLine(LESSON_1_4_LINE_NOTES,
        "B",
        "同意，我听说女生可挑了，要高富帅、体贴耐心、有房有车、有好婆婆等等，我们可能都不够格。",
        "Agreed. I hear women can be picky: tall, rich, handsome, considerate, patient, house, car, a good mother-in-law… we might not qualify.",
      ),
      notedLine(LESSON_1_4_LINE_NOTES, "A", "缘分吧，不是每一个女生都那么势利眼的。怎么样，一起去看看吧。", "It’s fate. Not every woman is that snobbish. Come on, let’s go take a look."),
      notedLine(LESSON_1_4_LINE_NOTES, "B", "好吧，几点？", "Fine. What time?"),
      notedLine(LESSON_1_4_LINE_NOTES, "A", "周六上午11点我去你家接你。", "Saturday at 11 a.m. I’ll pick you up at your place."),
    ],
    coreVocabulary: LESSON_1_4_CORE_VOCAB,
    chunks: LESSON_1_4_CHUNKS,
    expressionFamily: {
      title: "一套相处／结婚说法",
      titleEn: "One family of dating and marriage expressions — learn them together",
      items: LESSON_1_4_FAMILY,
    },
    grammarFocus: LESSON_1_4_GRAMMAR_FOCUS,
    practiceSentences: LESSON_1_4_PRACTICE,
    fillBlanks: LESSON_1_4_FILL_BLANKS,
    vocabulary: [
      v("婆媳问题", "mother-in-law / daughter-in-law conflict"),
      v("配偶", "spouse"),
      v("媒妁之言", "a matchmaker’s arrangement"),
      v("相亲", "arranged date / blind date"),
      v("度蜜月", "go on a honeymoon"),
      v("婚姻仲介〔中介〕", "marriage agency"),
      v("未婚联谊", "singles mixer"),
      v("三观接近", "similar values and worldview"),
      v("挑", "to pick / be picky"),
      v("够格", "qualified / good enough"),
      v("缘分", "fate / affinity"),
      v("势利眼", "snobbish / status-conscious"),
    ],
    questions: [
      q(1, "贵国的平均结婚年龄大概几岁？你觉得什么时候结婚好？", "What’s the average marriage age in your country? When do you think is a good time to marry?"),
      q(2, "说说你梦想中的求婚。", "Describe your dream proposal."),
      q(3, "你会考虑国际婚姻吗？国际婚姻有什么优缺点？", "Would you consider an international marriage? Pros and cons?"),
      q(4, "你觉得理想的情人和理想的结婚对象一样吗？为什么？", "Is an ideal lover the same as an ideal spouse? Why?"),
      q(5, "如何维持幸福婚姻或与伴侣维持良好关系？", "How do you keep a happy marriage or a good relationship?"),
      q(6, "你参加过婚姻仲介〔中介〕的活动或相亲、未婚联谊吗？", "Have you been to a matchmaking event, arranged date, or singles mixer?"),
      q(7, "若婚姻出现问题，你会怎么处理？", "If problems appeared in a marriage, what would you do?"),
      q(8, "你对晚年离婚或在配偶死后办离婚的人有什么看法？", "What do you think of people who divorce late in life, or after a spouse has died?"),
      q(9, "越来越多年轻人不想结婚，你的看法？", "More and more young people don’t want to marry. Your view?"),
      q(10, "请描述贵国的传统婚礼，和现代婚礼有什么不同？", "Describe a traditional wedding in your country. How is it different from a modern one?"),
      q(11, "你理想中的婚礼是什么样的？", "What would your ideal wedding be like?"),
      q(12, "你对同性结婚的看法？", "What’s your view on same-sex marriage?"),
      q(13, "人们离婚的一些主要原因是什么？", "What are some main reasons people divorce?"),
      q(14, "你觉得夫妇年龄差距很大的婚姻如何？你可以接受女大男小吗？", "What do you think of a large age gap? Could you accept the woman being older?"),
      q(15, "你有朋友是因为父母之命或媒妁之言而结婚的吗？", "Do you have friends who married because of their parents or a matchmaker?"),
      q(16, "你想去哪里度蜜月？（如果已经去了，哪里？）", "Where would you want to honeymoon? (If you already went, where?)"),
      q(17, "你认为结婚后人们会改变吗？", "Do you think people change after marriage?"),
      q(18, "你的父母不喜欢你想结婚的对象，你会怎么做？", "If your parents disliked the person you wanted to marry, what would you do?"),
      q(19, "“三观接近”是选择结婚对象的必要条件吗？为什么？", "Are similar values a must when choosing a spouse? Why?"),
      q(20, "如果你经营婚姻仲介〔中介〕，你觉得AI还是人工配对容易成功？为什么？", "If you ran a matchmaking agency, would AI or human matching work better? Why?"),
      q(
        21,
        "贵国也有给结婚纪念年命名的习惯吗？在台湾，第一年是纸婚，二十年瓷婚，三十年珍珠婚，五十年金婚，六十年钻石婚。",
        "Does your country name wedding anniversaries? In Taiwan: year 1 paper, 20 porcelain, 30 pearl, 50 gold, 60 diamond.",
      ),
      q(22, "你和你的伴侣会在结婚前立下契约吗？会的话是什么样的内容？", "Would you and your partner sign an agreement before marriage? What would it say?"),
      q(23, "你认同先“试婚”再结婚的做法吗？", "Do you agree with living together as a trial before marriage?"),
      q(24, "你家会庆祝结婚纪念日吗？怎么庆祝？", "Does your family celebrate wedding anniversaries? How?"),
      q(25, "你听过婆媳问题吗？如果有婆媳问题，你会怎么做？", "Have you heard of mother-in-law / daughter-in-law conflict? If you had it, what would you do?"),
    ],
  },
  {
    id: "1-5",
    unitId: 1,
    title: "家人和家庭活动",
    titleEn: "Family and family activities",
    pageStart: 10,
    audioId: "1-5",
    scenario: {
      time: "上午10点",
      timeEn: "10 a.m.",
      location: "电话",
      locationEn: "On the phone",
      participants: "和好友太太",
      participantsEn: "With a close friend’s wife",
      topic: "家庭派对邀请",
      topicEn: "Inviting someone to a family party",
    },
    dialogue: [
      notedLine(LESSON_1_5_LINE_NOTES, "stage", "（电话铃声）", "(Phone rings)"),
      notedLine(LESSON_1_5_LINE_NOTES, "B", "喂？", "Hello?"),
      notedLine(LESSON_1_5_LINE_NOTES, "A", "喂，琳姐，我是小芳。下周末有空吗？带小孩来我家玩吧！", "Hi, Sister Lin, it’s Xiaofang. Free next weekend? Bring the kids over!"),
      notedLine(LESSON_1_5_LINE_NOTES, "B", "哇，怎么这么好！", "Wow, that’s so nice of you!"),
      notedLine(LESSON_1_5_LINE_NOTES, "A", "在我家庭院烤肉，人多热闹！", "We’ll barbecue in the yard. The more people, the livelier!"),
      notedLine(LESSON_1_5_LINE_NOTES, "B", "有大庭院真好！你不用太麻烦，我带两道菜过去吧。", "A big yard is wonderful! Don’t go to too much trouble. I’ll bring two dishes."),
      notedLine(LESSON_1_5_LINE_NOTES, "A", "你负责沙拉和水果拼盘就好，其他我弄。", "Just take the salad and fruit platter. I’ll handle the rest."),
      notedLine(LESSON_1_5_LINE_NOTES, "B", "好。饭后给小孩玩什么？", "Okay. What will the kids do after the meal?"),
      notedLine(LESSON_1_5_LINE_NOTES, "A", "如果喜欢画图的话，可以在庭院写生。也可以折纸、打牌、玩积木、打游戏。", "If they like drawing, they can sketch in the yard. Or origami, cards, blocks, video games."),
      notedLine(LESSON_1_5_LINE_NOTES, "B", "最好别打游戏，我想一些创意活动吧。", "Better not video games. Let me think of some creative activities."),
      notedLine(LESSON_1_5_LINE_NOTES, "A", "你是幼教老师，活动就交给你啦。", "You’re a preschool teacher — I’ll leave the activities to you."),
      notedLine(LESSON_1_5_LINE_NOTES, "B", "我们学校有个老师会变魔术，要不也邀请他来？教魔术。", "A teacher at our school does magic. Want to invite him too, to teach magic?"),
      notedLine(LESSON_1_5_LINE_NOTES, "A", "好耶！我不曾这么近距离地看魔术，小孩们一定超兴奋的！", "Yes! I’ve never seen magic that close. The kids will be thrilled!"),
    ],
    coreVocabulary: LESSON_1_5_CORE_VOCAB,
    chunks: LESSON_1_5_CHUNKS,
    expressionFamily: {
      title: "一套家庭活动说法",
      titleEn: "One family of hosting and family-activity expressions — learn them together",
      items: LESSON_1_5_FAMILY,
    },
    grammarFocus: LESSON_1_5_GRAMMAR_FOCUS,
    practiceSentences: LESSON_1_5_PRACTICE,
    fillBlanks: LESSON_1_5_FILL_BLANKS,
    notes: [
      {
        hanzi: "沙拉又称色拉、沙律，凉拌菜的意思。",
        en: "沙拉 is also written 色拉 or 沙律; it means a cold tossed dish.",
      },
    ],
    vocabulary: [
      v("家庭活动", "family activity"),
      v("休闲娱乐", "leisure and entertainment"),
      v("家庭聚会", "family gathering"),
      v("折纸", "origami"),
      v("车库", "garage"),
      v("跳蚤市场", "flea market"),
      v("花", "flower"),
      v("园", "garden / yard"),
      v("园艺", "gardening"),
      v("魔术", "magic"),
      v("马戏团", "circus"),
      v("郊游", "outing"),
      v("登山", "hiking / mountain climbing"),
      v("烤肉", "barbecue"),
      v("家规", "family rules"),
      v("门禁", "curfew"),
    ],
    questions: [
      q(1, "介绍你的家人。", "Introduce your family."),
      q(2, "你最常做的家庭活动是什么？", "What family activity do you do most often?"),
      q(3, "你喜欢和家人一起出游吗？多久出游一次？", "Do you like going out with family? How often?"),
      q(4, "你下雨天会在家里做什么？", "What do you do at home on rainy days?"),
      q(5, "你会和家人一起看电视吗？看什么节目？", "Do you watch TV with family? Which shows?"),
      q(6, "你的文化一般来说和家人的关系亲密吗？", "In your culture, are family relationships generally close?"),
      q(7, "你们家都一起吃饭吗？还是各吃各的？", "Does your family eat together, or does everyone eat separately?"),
      q(8, "周末和长假时你家通常做什么？", "What does your family usually do on weekends and long holidays?"),
      q(9, "你们最近的一次家庭活动是什么？", "What was your most recent family activity?"),
      q(10, "你喜欢家庭聚会吗？", "Do you like family gatherings?"),
      q(11, "你会折纸吗？你喜欢折纸吗？", "Can you do origami? Do you like it?"),
      q(12, "你家院子或附近可以烤肉吗？", "Can you barbecue in your yard or nearby?"),
      q(13, "你最喜欢和不喜欢的家庭活动是什么？为什么？", "Favorite and least favorite family activities? Why?"),
      q(14, "你家曾经在车库或在跳蚤市场卖旧物吗？（你买卖过旧物吗？）", "Has your family sold old things at a garage sale or flea market? Have you bought or sold used things?"),
      q(15, "你家有家规吗？（什么？）最严格的处罚是什么？", "Does your family have rules? What’s the strictest punishment?"),
      q(16, "你家有门禁吗？（几点？）你觉得应该要有门禁吗？", "Is there a curfew? What time? Should there be one?"),
      q(17, "你家有庭院吗？你的家人谁喜欢园艺？", "Do you have a yard? Who in the family likes gardening?"),
      q(18, "你会和家人一起做菜吗？", "Do you cook with your family?"),
      q(19, "你会和家人一起打游戏吗？", "Do you play games with your family?"),
      q(20, "你家曾经一起去看过魔术和马戏团吗？", "Has your family been to a magic show or circus together?"),
      q(21, "如果可能，你愿意当一次世界级魔术大师的助手吗？", "If you could, would you be a world-class magician’s assistant once?"),
      q(22, "你想被催眠漂浮看看吗？", "Would you want to be hypnotized and levitated?"),
      q(23, "你家喜欢去主题乐园吗？（哪一个？）", "Does your family like theme parks? Which one?"),
      q(24, "你喜欢去别人家玩吗？", "Do you like going over to other people’s homes?"),
      q(25, "你家曾经邀请别人来玩吗？", "Has your family invited others over?"),
      q(26, "你在家中最喜欢的角落是哪里？你喜欢在那里做什么？", "What’s your favorite corner at home? What do you like to do there?"),
    ],
  },
]
