/**
 * RULE: every dialogue line is built with notedLine(LESSON_X_Y_LINE_NOTES, …).
 * Keys must match 汉字 exactly, including 〔网络〕 / 〔营销〕 / 〔堵车〕 / 〔搜索〕,
 * Latin hmm, spaces around 12 / 1974 / 11 / 7 / 8, and “不一样” / “当归鸭” quotes.
 */
import {
  LESSON_6_1_CHUNKS,
  LESSON_6_1_CORE_VOCAB,
  LESSON_6_1_FAMILY,
  LESSON_6_1_FILL_BLANKS,
  LESSON_6_1_GRAMMAR_FOCUS,
  LESSON_6_1_LINE_NOTES,
  LESSON_6_1_PRACTICE,
} from "@/content/lessons/6-1-notes"
import {
  LESSON_6_2_CHUNKS,
  LESSON_6_2_CORE_VOCAB,
  LESSON_6_2_FAMILY,
  LESSON_6_2_FILL_BLANKS,
  LESSON_6_2_GRAMMAR_FOCUS,
  LESSON_6_2_LINE_NOTES,
  LESSON_6_2_PRACTICE,
} from "@/content/lessons/6-2-notes"
import {
  LESSON_6_3_CHUNKS,
  LESSON_6_3_CORE_VOCAB,
  LESSON_6_3_FAMILY,
  LESSON_6_3_FILL_BLANKS,
  LESSON_6_3_GRAMMAR_FOCUS,
  LESSON_6_3_LINE_NOTES,
  LESSON_6_3_PRACTICE,
} from "@/content/lessons/6-3-notes"
import {
  LESSON_6_4_CHUNKS,
  LESSON_6_4_CORE_VOCAB,
  LESSON_6_4_FAMILY,
  LESSON_6_4_FILL_BLANKS,
  LESSON_6_4_GRAMMAR_FOCUS,
  LESSON_6_4_LINE_NOTES,
  LESSON_6_4_PRACTICE,
} from "@/content/lessons/6-4-notes"
import {
  LESSON_6_5_CHUNKS,
  LESSON_6_5_CORE_VOCAB,
  LESSON_6_5_FAMILY,
  LESSON_6_5_FILL_BLANKS,
  LESSON_6_5_GRAMMAR_FOCUS,
  LESSON_6_5_LINE_NOTES,
  LESSON_6_5_PRACTICE,
} from "@/content/lessons/6-5-notes"
import { assertLessonReady, notedLine } from "@/content/lessons/note-helpers"
import type { Lesson, Question, VocabItem } from "@/lib/types"

function v(hanzi: string, en: string): VocabItem {
  return { hanzi, en }
}

function q(n: number, hanzi: string, en: string, kind?: Question["kind"]): Question {
  return kind ? { n, hanzi, en, kind } : { n, hanzi, en }
}

export const UNIT_6: Lesson[] = [
  {
    id: "6-1",
    unitId: 6,
    title: "各国节日庆典",
    titleEn: "Festivals around the world",
    pageStart: 74,
    audioId: "6-1",
    scenario: {
      time: "万圣节前",
      timeEn: "Before Halloween",
      location: "网路〔网络〕电话",
      locationEn: "A phone call online",
      participants: "和朋友",
      participantsEn: "With a friend",
      topic: "聊化妆舞会",
      topicEn: "Talking about a costume party",
    },
    dialogue: [
      notedLine(LESSON_6_1_LINE_NOTES, "A", "陈哥家的万圣节化妆舞会，你要打扮成什么？", "Chen-ge’s Halloween costume party — what are you dressing as?"),
      notedLine(LESSON_6_1_LINE_NOTES, "B", "还没想到，你呢？", "Haven’t thought of it yet. You?"),
      notedLine(LESSON_6_1_LINE_NOTES, "A", "我懒得去买，有什么就穿什么，可能会穿旗袍戴面具吧。", "I can’t be bothered to shop. I’ll wear whatever I have — maybe a qipao and a mask."),
      notedLine(LESSON_6_1_LINE_NOTES, "B", "旗袍不可怕啊。", "A qipao isn’t scary."),
      notedLine(
        LESSON_6_1_LINE_NOTES,
        "A",
        "没人说一定要穿得很可怕啊，跟平常“不一样”就好了，我那件旗袍是紧身开高衩的，平常不敢穿，也大概只有这种场合敢牺牲色相。",
        "Nobody said it has to be scary. Just “different from usual” is enough. That qipao of mine is tight with a high slit — I wouldn’t dare wear it normally. Only this kind of occasion I’d dare show off.",
      ),
      notedLine(LESSON_6_1_LINE_NOTES, "B", "你身材好！我第一次参加，没点子，帮我想一下吧。", "You have a great figure! It’s my first time — I have no ideas. Help me think of something."),
      notedLine(
        LESSON_6_1_LINE_NOTES,
        "A",
        "如果没有什么特别的衣服，又懒得做的话，最简单的方法就是去大卖场买一套巫婆、仙女、南瓜装什么的。",
        "If you don’t have special clothes and can’t be bothered to make any, the easiest way is to buy a witch, fairy, or pumpkin set at a hypermarket.",
      ),
      notedLine(LESSON_6_1_LINE_NOTES, "B", "南瓜装？听起来很可爱！穿起来像南瓜吗？", "A pumpkin costume? That sounds cute! Do you look like a pumpkin in it?"),
      notedLine(LESSON_6_1_LINE_NOTES, "A", "对，身体就像一个万圣节南瓜灯，还有帽子。", "Yes — the body is just like a Halloween pumpkin lantern, plus a hat."),
      notedLine(LESSON_6_1_LINE_NOTES, "B", "就它了！谢啦！", "That’s the one! Thanks!"),
    ],
    notes: [{ hanzi: "牺牲色相：开玩笑说为了好看而大胆穿。", en: "牺牲色相 is self-teasing: daring to look hot for the occasion." }],
    coreVocabulary: LESSON_6_1_CORE_VOCAB,
    chunks: LESSON_6_1_CHUNKS,
    expressionFamily: { title: "一套节日庆典说法", titleEn: "One family of festival expressions", items: LESSON_6_1_FAMILY },
    grammarFocus: LESSON_6_1_GRAMMAR_FOCUS,
    practiceSentences: LESSON_6_1_PRACTICE,
    fillBlanks: LESSON_6_1_FILL_BLANKS,
    vocabulary: [
      v("节日庆典", "festival celebration"),
      v("假日", "holiday"),
      v("万圣节", "Halloween"),
      v("化妆舞会", "costume / masquerade party"),
      v("牺牲色相", "to show off one’s looks (self-teasing)"),
      v("嘉年华会", "carnival"),
      v("连假", "long weekend / consecutive holidays"),
      v("行销〔营销〕", "marketing"),
      v("消费", "to consume; spending"),
      v("祭典", "festival rite; matsuri"),
      v("请假", "to ask for leave"),
      v("连休", "to take consecutive days off"),
      v("弹性放假", "bridge / flexible holiday"),
    ],
    questions: [
      q(1, "你喜欢过节或参加庆典吗？", "Do you like celebrating holidays or going to festivals?"),
      q(2, "贵国最重要的国定假日是什么？", "What’s the most important national holiday in your country?"),
      q(3, "你最喜欢或是觉得最重要的节日是什么？", "What’s your favorite or most important festival?"),
      q(4, "贵国有什么特别的节庆食物吗？", "Does your country have special festival food?"),
      q(5, "介绍你们国家的特殊节庆。", "Introduce a special festival from your country."),
      q(6, "你住的城市有什么特别的庆典吗？", "Does the city you live in have a special celebration?"),
      q(7, "你参加过万圣节化妆舞会吗？", "Have you been to a Halloween costume party?"),
      q(8, "参加过化妆舞会的话，你打扮成什么？没参加过的话，你想打扮成什么？", "If you’ve been to a costume party, what did you dress as? If not, what would you want to be?"),
      q(9, "你参加过嘉年华会吗？", "Have you been to a carnival?"),
      q(10, "你听说过西班牙的番茄〔西红柿〕节吗？你想参加吗？", "Have you heard of Spain’s tomato festival? Would you go?"),
      q(11, "下一个节庆是什么？你要怎么过？", "What’s the next festival? How will you spend it?"),
      q(12, "如果你是老板，你同意让你的员工为了传统节日请假吗？", "If you were the boss, would you let staff take leave for a traditional festival?"),
      q(13, "你期待连假吗？", "Do you look forward to long weekends?"),
      q(14, "连假你通常做什么？", "What do you usually do on a long weekend?"),
      q(15, "如果可以参加世界上任何一个节庆活动，你想参加哪一国的什么节庆？", "If you could join any festival in the world, which country’s, and which one?"),
      q(16, "你听说过特殊的庆典活动吗？你参加过最特别的节庆是什么？", "Have you heard of an unusual festival? What’s the most special one you’ve been to?"),
      q(17, "日本的三大祭是什么？你想参加哪一个？", "What are Japan’s three great festivals? Which would you join?"),
      q(18, "哪些国家有泼水节？泼水节的由来？", "Which countries have a water-splashing festival? What’s the origin?"),
      q(19, "如果要介绍外国人参加贵国的传统节庆，你会建议哪一个节庆？", "If you were introducing a foreigner to a traditional festival in your country, which would you recommend?"),
      q(20, "如果可以订定一个节日，让全世界放假，你想要什么节日？", "If you could create a holiday for the whole world, what would it be?"),
      q(21, "中国的“双十一”是什么？", "What is China’s Double Eleven?"),
      q(22, "搜寻〔搜索〕世界最奇特的十个节庆，你想体验哪一个？", "Look up the world’s ten strangest festivals. Which would you try?"),
      q(23, "什么是台风假？贵国有台风假吗？", "What is a typhoon day off? Does your country have that?"),
      q(24, "你曾经在节庆特卖时网购吗？", "Have you ever shopped online during a festival sale?"),
      q(25, "你曾经策划过节日行销〔营销〕吗？", "Have you ever planned a festival marketing campaign?"),
    ],
  },
  {
    id: "6-2",
    unitId: 6,
    title: "华人的节日",
    titleEn: "Chinese festivals",
    pageStart: 76,
    audioId: "6-2",
    scenario: {
      time: "中秋节",
      timeEn: "Mid-Autumn Festival",
      location: "朋友家门口",
      locationEn: "At a friend’s doorstep",
      participants: "日本人和台湾朋友",
      participantsEn: "A Japanese person and a Taiwanese friend",
      topic: "烤肉聊中秋",
      topicEn: "Barbecue and talking about Mid-Autumn",
    },
    dialogue: [
      notedLine(LESSON_6_2_LINE_NOTES, "A", "谢谢！谢谢！台湾香肠真好吃！跟日本不一样。", "Thank you! Taiwanese sausage is so good — not the same as Japan."),
      notedLine(LESSON_6_2_LINE_NOTES, "B", "对，这是台湾特色，其实台湾南北的香肠口味也不太一样。", "Yes — that’s a Taiwan specialty. Actually north and south sausages don’t taste the same either."),
      notedLine(LESSON_6_2_LINE_NOTES, "A", "好热闹啊！家家户户都在烤肉，而且都在门口！", "So lively! Every household is barbecuing — and right at the door!"),
      notedLine(LESSON_6_2_LINE_NOTES, "B", "对啊，这也是台湾特色，每到中秋节，大街小巷都是烤肉味。", "Yes — that’s Taiwan too. Every Mid-Autumn, every street smells of barbecue."),
      notedLine(LESSON_6_2_LINE_NOTES, "A", "真好玩，可惜日本不能这样做。", "So fun. A pity Japan can’t do this."),
      notedLine(LESSON_6_2_LINE_NOTES, "B", "日本不能在家门口烤肉吗？为什么？", "Japan can’t barbecue at the door? Why?"),
      notedLine(LESSON_6_2_LINE_NOTES, "A", "大概怕影响邻居吧，味道、噪音什么的，还有怕火灾。", "Probably afraid of bothering the neighbors — the smell, the noise, and fire."),
      notedLine(LESSON_6_2_LINE_NOTES, "B", "我听说日本也有中秋节，你们在中秋节会做什么？", "I heard Japan has Mid-Autumn too. What do you do?"),
      notedLine(LESSON_6_2_LINE_NOTES, "A", "我们也会看月亮、吃圆圆的麻糬。", "We also gaze at the moon and eat round mochi."),
      notedLine(LESSON_6_2_LINE_NOTES, "B", "来，吃这个柚子，也叫文旦，这样吃。你们有柚子吗？", "Here — try this pomelo, also called wendan. Eat it like this. Do you have pomelo?"),
      notedLine(LESSON_6_2_LINE_NOTES, "A", "我那里没有，四国有，hmm～好甜！", "We don’t have it where I am. Shikoku does. Hmm — so sweet!"),
    ],
    notes: [{ hanzi: "文旦：柚子的一种，中秋常吃。", en: "文旦 is a pomelo. Mid-Autumn food in Taiwan." }],
    coreVocabulary: LESSON_6_2_CORE_VOCAB,
    chunks: LESSON_6_2_CHUNKS,
    expressionFamily: { title: "一套华人节日说法", titleEn: "One family of Chinese-festival expressions", items: LESSON_6_2_FAMILY },
    grammarFocus: LESSON_6_2_GRAMMAR_FOCUS,
    practiceSentences: LESSON_6_2_PRACTICE,
    fillBlanks: LESSON_6_2_FILL_BLANKS,
    vocabulary: [
      v("扫墓", "to sweep tombs"),
      v("灯会", "lantern festival (event)"),
      v("文旦", "wendan pomelo"),
      v("柚子", "pomelo"),
      v("嫦娥奔月", "Chang’e flies to the moon"),
      v("后羿", "Hou Yi"),
      v("长生不老药", "elixir of immortality"),
      v("中秋", "Mid-Autumn"),
      v("清明", "Qingming"),
      v("端午", "Dragon Boat Festival"),
      v("国庆", "National Day"),
    ],
    questions: [
      q(1, "看看月历，你知道哪些华人节日？哪一个最重要？", "Look at the calendar. Which Chinese festivals do you know? Which is most important?"),
      q(2, "元宵节是什么时候？怎么庆祝？", "When is the Lantern Festival? How is it celebrated?"),
      q(3, "贵国有灯会吗？", "Does your country have lantern festivals?"),
      q(4, "端午节是什么时候？怎么庆祝？", "When is the Dragon Boat Festival? How is it celebrated?"),
      q(5, "你知道端午节的传说吗？", "Do you know the Dragon Boat Festival legend?"),
      q(6, "清明节是什么时候？华人会在清明节做什么？", "When is Qingming? What do Chinese people do then?"),
      q(7, "台湾和中国的母亲节和父亲节是什么时候？", "When are Mother’s Day and Father’s Day in Taiwan and China?"),
      q(8, "你知道哪些华人的节庆食物？", "What Chinese festival foods do you know?"),
      q(9, "如果你必须学一道华人的节庆料理，你想学什么？", "If you had to learn one Chinese festival dish, which would it be?"),
      q(10, "你知道中秋节的传说吗？", "Do you know the Mid-Autumn legend?"),
      q(11, "搜寻〔搜索〕台湾中秋节的图片，会看到很多在家门口烤肉的照片，为什么台湾人中秋节喜欢烤肉？", "Look up Taiwan Mid-Autumn photos. Why do people barbecue at the door?"),
      q(12, "贵国可以在门口、路边烤肉吗？", "Can you barbecue at the door or roadside in your country?"),
      q(13, "你知道华人怎么庆祝中秋节吗？", "How do Chinese people celebrate Mid-Autumn?"),
      q(14, "贵国有中秋节吗？有没有跟月亮或太阳有关的节日？怎么庆祝？", "Does your country have Mid-Autumn? Any moon or sun festivals? How are they celebrated?"),
      q(15, "你吃过文旦（柚子）吗？", "Have you eaten wendan (pomelo)?"),
      q(16, "你吃过月饼吗？喜欢什么口味的？", "Have you eaten mooncakes? Which flavor do you like?"),
      q(17, "你听说过哪些中国少数民族的节庆活动？（如：彝族火把节）", "Which Chinese ethnic-minority festivals have you heard of? (e.g. the Yi Torch Festival)"),
      q(18, "贵国有没有少数民族的节庆活动？", "Does your country have ethnic-minority festivals?"),
      q(19, "中国的情人节是什么时候？你知道七夕的故事吗？", "When is Chinese Valentine’s Day? Do you know the Qixi story?"),
      q(20, "你会庆祝情人节吗？", "Do you celebrate Valentine’s Day?"),
      q(21, "国庆是什么时候？你知道国庆的由来吗？", "When is National Day? Do you know its origin?"),
      q(22, "贵国有扫墓的节日或文化吗？", "Does your country have a tomb-sweeping festival or custom?"),
      q(23, "中元节是什么时候？要做什么？", "When is the Ghost Festival? What do people do?"),
      q(24, "现在大家庆祝的节日中什么节日不是传统节日？你觉得有没有受别国文化或商战的影响？", "Which festivals people celebrate now aren’t traditional? Influenced by other cultures or marketing wars?"),
    ],
  },
  {
    id: "6-3",
    unitId: 6,
    title: "圣诞节",
    titleEn: "Christmas",
    pageStart: 78,
    audioId: "6-3",
    scenario: {
      time: "12 月 24 日",
      timeEn: "December 24",
      location: "日本大阪街上",
      locationEn: "A street in Osaka, Japan",
      participants: "和朋友",
      participantsEn: "With a friend",
      topic: "聊圣诞节吃鸡",
      topicEn: "Talking about eating chicken at Christmas",
    },
    dialogue: [
      notedLine(LESSON_6_3_LINE_NOTES, "A", "欸？肯德基怎么这么多人？在排什么啊？", "Eh? Why so many people at KFC? What are they queuing for?"),
      notedLine(LESSON_6_3_LINE_NOTES, "B", "他们在排队买炸鸡，过圣诞节。", "They’re queuing for fried chicken for Christmas."),
      notedLine(LESSON_6_3_LINE_NOTES, "A", "日本人圣诞节吃炸鸡？！", "Japanese people eat fried chicken at Christmas?!"),
      notedLine(
        LESSON_6_3_LINE_NOTES,
        "B",
        "听说是肯德基在 1974 年推出的。他们把“圣诞节就是要吃炸鸡”当作口号，成功行销〔营销〕。现在每到圣诞节的前两个月，就有人开始预订全家桶了。",
        "I heard KFC launched it in 1974. They used “Christmas means fried chicken” as a slogan and marketed it well. Now, two months before Christmas, people start pre-ordering family buckets.",
      ),
      notedLine(LESSON_6_3_LINE_NOTES, "A", "两个月前就开始预订？夸张！", "Pre-ordering two months ahead? That’s over the top!"),
      notedLine(
        LESSON_6_3_LINE_NOTES,
        "B",
        "我老公很无聊，每年都为了赠品买炸鸡，我最受不了那个附赠的盘子，超占空间的。",
        "My husband’s so boring — every year he buys fried chicken just for the free gifts. I can’t stand those extra plates. They take up so much space.",
      ),
      notedLine(LESSON_6_3_LINE_NOTES, "A", "真的是！不用的东西放在家里还要断舍离，麻烦！", "Tell me about it! Keeping unused stuff means you have to declutter. What a hassle!"),
      notedLine(LESSON_6_3_LINE_NOTES, "B", "我们去买全鸡回家烤吧，平常超市都买不到整只鸡。", "Let’s buy a whole chicken and roast it at home. Usually you can’t even find a whole chicken at the supermarket."),
      notedLine(LESSON_6_3_LINE_NOTES, "A", "日本小家庭，整只鸡吃不完吧。你烤鸡，我做蛋糕！", "Small Japanese families — you probably can’t finish a whole chicken. You roast the chicken, I’ll make a cake!"),
      notedLine(LESSON_6_3_LINE_NOTES, "B", "好，再做个沙拉就可以了。", "Okay — and just make a salad and we’re done."),
    ],
    notes: [{ hanzi: "断舍离：日语借词，丢掉不用的东西。", en: "断舍离 is dan-sha-ri: declutter unused stuff." }],
    coreVocabulary: LESSON_6_3_CORE_VOCAB,
    chunks: LESSON_6_3_CHUNKS,
    expressionFamily: { title: "一套圣诞节说法", titleEn: "One family of Christmas expressions", items: LESSON_6_3_FAMILY },
    grammarFocus: LESSON_6_3_GRAMMAR_FOCUS,
    practiceSentences: LESSON_6_3_PRACTICE,
    fillBlanks: LESSON_6_3_FILL_BLANKS,
    vocabulary: [
      v("圣诞节", "Christmas"),
      v("贺卡", "greeting card"),
      v("庆祝", "to celebrate"),
      v("装饰", "to decorate; decoration"),
      v("圣诞老人", "Santa Claus"),
      v("宗教仪式", "religious ceremony"),
      v("炸鸡", "fried chicken"),
      v("火鸡", "turkey"),
      v("礼物", "gift"),
      v("点灯", "to light up; illuminations"),
      v("姜饼人", "gingerbread man"),
    ],
    questions: [
      q(1, "你家庆祝圣诞节吗？", "Does your family celebrate Christmas?"),
      q(2, "圣诞节期间你是否会参加特别的宗教仪式？", "Do you go to a special religious service at Christmas?"),
      q(3, "你所住的地方圣诞节下过雪吗？", "Has it snowed at Christmas where you live?"),
      q(4, "你小的时候，相信圣诞老人吗？", "When you were little, did you believe in Santa?"),
      q(5, "你喜欢圣诞节吗？圣诞节在你的文化中很重要吗？", "Do you like Christmas? Is it important in your culture?"),
      q(6, "在圣诞节前夕，你会装饰房子吗？", "Do you decorate the house on Christmas Eve?"),
      q(7, "如果你可以去任何地方过圣诞假期，你要去哪里？", "If you could spend the Christmas holiday anywhere, where?"),
      q(8, "贵国庆祝圣诞节吗？如何庆祝？吃什么？", "Does your country celebrate Christmas? How, and what do you eat?"),
      q(9, "你会吃特别的圣诞晚餐吗？", "Do you have a special Christmas dinner?"),
      q(10, "你曾经和朋友玩交换礼物吗？", "Have you done a gift exchange with friends?"),
      q(11, "你曾经为了礼物而挂起袜子吗？", "Have you ever hung a stocking for gifts?"),
      q(12, "你曾参加学校或朋友的圣诞派对吗？", "Have you been to a school or friends’ Christmas party?"),
      q(13, "你今年有计划去参加圣诞派对吗？", "Are you planning a Christmas party this year?"),
      q(14, "你会在家里举行圣诞派对吗？", "Would you host a Christmas party at home?"),
      q(15, "你知道圣诞节的由来和传说吗？", "Do you know the origin and legends of Christmas?"),
      q(16, "你寄过或收过圣诞贺卡吗？", "Have you sent or received a Christmas card?"),
      q(17, "圣诞节的传统食物中你最喜欢哪一个？你会做吗？（烤火鸡、浓汤、蛋糕、布丁、姜饼屋……）", "Which traditional Christmas food do you like best? Can you make it? (roast turkey, soup, cake, pudding, gingerbread house…)"),
      q(18, "你想要圣诞老人带给你什么样的圣诞节？", "What kind of Christmas would you want Santa to bring you?"),
      q(19, "如果你也必须送一个礼物给圣诞老公公，你要送他什么？", "If you had to give Santa a gift, what would it be?"),
      q(20, "你曾经收到过最好的圣诞礼物是什么？", "What’s the best Christmas gift you’ve received?"),
      q(21, "如果可以许愿，你想收到什么圣诞礼物？", "If you could wish, what Christmas gift would you want?"),
      q(22, "人们通常会在圣诞节做什么？", "What do people usually do at Christmas?"),
      q(23, "如果你有一百万美元，圣诞节你会做什么？", "If you had a million dollars, what would you do at Christmas?"),
      q(24, "南半球的圣诞节是夏天，如果你住北半球，想象一下，你的感觉？", "Christmas in the southern hemisphere is summer. If you live in the north, imagine how that would feel."),
      q(25, "如果你必须当一天圣诞老人，不用考虑金钱和交通，你想要送谁什么礼物？", "If you had to be Santa for a day, money and travel no object, who would you gift, and what?"),
    ],
  },
  {
    id: "6-4",
    unitId: 6,
    title: "新年",
    titleEn: "New Year",
    pageStart: 80,
    audioId: "6-4",
    scenario: {
      time: "农历新年前",
      timeEn: "Before Lunar New Year",
      location: "健身中心",
      locationEn: "A gym",
      participants: "和朋友",
      participantsEn: "With a friend",
      topic: "聊过年回老家",
      topicEn: "Talking about going home for New Year",
    },
    dialogue: [
      notedLine(LESSON_6_4_LINE_NOTES, "A", "你今年过年也不回家吗？", "You’re not going home for New Year this year either?"),
      notedLine(LESSON_6_4_LINE_NOTES, "B", "没办法，要加班，我家人也理解。你呢？你不用加班吧？", "No choice — I have to work overtime. My family understands. You? You don’t have to work overtime, right?"),
      notedLine(LESSON_6_4_LINE_NOTES, "A", "我跟我妈说要加班，其实是不想回去。", "I told Mum I have overtime, but I just don’t want to go back."),
      notedLine(LESSON_6_4_LINE_NOTES, "B", "不想回去？", "You don’t want to go back?"),
      notedLine(LESSON_6_4_LINE_NOTES, "A", "第一，到处塞车〔堵车〕，身体累；第二，应付聊天，心累。", "First, traffic jams everywhere — body tired. Second, dealing with the chat — mind tired."),
      notedLine(LESSON_6_4_LINE_NOTES, "B", "哈！我知道！是不是交往对象、结婚生子、薪水年终？", "Ha! I know! Is it dating, getting married and having kids, salary and year-end bonus?"),
      notedLine(LESSON_6_4_LINE_NOTES, "A", "哎，对啊，压力超大。", "Sigh — exactly. The pressure is huge."),
      notedLine(LESSON_6_4_LINE_NOTES, "B", "真的是，难得团圆，就不能说些别的话题吗？", "Tell me about it. It’s a rare reunion — can’t they talk about something else?"),
      notedLine(LESSON_6_4_LINE_NOTES, "A", "还有，第三，我家亲戚小孩超多的，荷包有可能大失血。", "And third: my relatives have so many kids. The wallet might bleed heavily."),
      notedLine(
        LESSON_6_4_LINE_NOTES,
        "B",
        "虽然如此，我是真的加班没办法，一年就一次，我还是很想回去看看我爸妈。",
        "Even so, I really do have overtime and no choice. It’s only once a year. I still really want to go back and see my parents.",
      ),
    ],
    notes: [{ hanzi: "荷包失血：过年发红包、给压岁钱，钱包大出血。", en: "荷包失血 is wallet-bleed: red envelopes and New Year money." }],
    coreVocabulary: LESSON_6_4_CORE_VOCAB,
    chunks: LESSON_6_4_CHUNKS,
    expressionFamily: { title: "一套过年说法", titleEn: "One family of New Year expressions", items: LESSON_6_4_FAMILY },
    grammarFocus: LESSON_6_4_GRAMMAR_FOCUS,
    practiceSentences: LESSON_6_4_PRACTICE,
    fillBlanks: LESSON_6_4_FILL_BLANKS,
    vocabulary: [
      v("习俗", "custom"),
      v("年菜", "New Year dishes"),
      v("老家", "hometown; family home"),
      v("年终奖金", "year-end bonus"),
      v("尾牙", "year-end banquet"),
      v("抽奖", "lucky draw"),
      v("倒数", "countdown"),
      v("烟火", "fireworks"),
      v("跨年", "to see in the New Year"),
      v("荷包失血", "wallet-bleed (heavy spending)"),
      v("红包", "red envelope"),
      v("压岁钱", "New Year money for children"),
      v("放鞭炮", "to set off firecrackers"),
      v("岁末联欢", "year-end party / gala"),
    ],
    questions: [
      q(1, "贵国有独特的日历吗？贵国的新年是什么时候？", "Does your country have its own calendar? When is New Year?"),
      q(2, "请介绍贵国的新年习俗。", "Introduce New Year customs in your country."),
      q(3, "请介绍贵国过年吃的年菜。", "Introduce the New Year dishes in your country."),
      q(4, "贵国过年吃的年菜有什么特别意义吗？有的话请举例说明。", "Do those dishes have special meanings? Give an example."),
      q(5, "你最喜欢和不喜欢的年菜是什么？", "Which New Year dish do you like most, and which least?"),
      q(6, "如果可以去任何地方，你想去哪一国跨年或过新年？", "If you could go anywhere, which country would you pick for New Year?"),
      q(7, "贵国有没有新年的禁忌？", "Does your country have New Year taboos?"),
      q(8, "你知道中国和台湾的过年习俗和年菜意义吗？", "Do you know Chinese and Taiwan New Year customs and dish meanings?"),
      q(9, "你家年终都会大扫除吗？", "Does your family do a year-end deep clean?"),
      q(10, "你会回老家过年吗？回老家过年做什么？", "Do you go home for New Year? What do you do there?"),
      q(11, "你们家过年谁最忙？", "Who is busiest in your family at New Year?"),
      q(12, "你知道华人回老家过年，常和亲友聊什么话题吗？", "What do Chinese people often talk about with relatives when they go home for New Year?"),
      q(13, "你公司有年终大扫除吗？", "Does your company do a year-end deep clean?"),
      q(14, "你年底会特别忙吗？为什么？", "Are you extra busy at year-end? Why?"),
      q(15, "什么是“尾牙”？贵国有类似尾牙的文化吗？", "What is 尾牙? Does your country have something similar?"),
      q(16, "公司的年终晚会有抽奖、礼物、节目表演等等吗？", "Does the company year-end party have lucky draws, gifts, performances?"),
      q(17, "你期待过年吗？为什么？", "Do you look forward to New Year? Why?"),
      q(18, "你喜欢利用年假出国旅游吗？", "Do you like using New Year leave to travel abroad?"),
      q(19, "一般公司的年终奖金有几个月？", "How many months’ year-end bonus do companies usually give?"),
      q(20, "你看过台北 101 的跨年烟火吗？怎么样？（可以在网上看）", "Have you seen Taipei 101 New Year fireworks? How were they? (You can watch online.)"),
      q(21, "你会看除夕特别节目吗？", "Do you watch the New Year’s Eve specials?"),
      q(22, "你想去参加跨年倒数派对或集会吗？", "Would you go to a New Year countdown party or gathering?"),
      q(23, "贵国人民跨年大概会做什么？", "What do people in your country usually do at New Year?"),
      q(24, "你参加过哪里的跨年晚会吗？你喜欢吗？", "Have you been to a New Year party somewhere? Did you like it?"),
      q(25, "你听说过什么特别的跨年活动吗？", "Have you heard of an unusual New Year event?"),
      q(26, "如果你负责为公司策划一个新年活动吸引人潮，你要做什么？", "If you had to plan a company New Year event to draw a crowd, what would you do?"),
    ],
  },
  {
    id: "6-5",
    unitId: 6,
    title: "节气",
    titleEn: "Solar terms",
    pageStart: 82,
    audioId: "6-5",
    scenario: {
      time: "立冬的早上",
      timeEn: "The morning of Start of Winter",
      location: "菜市场",
      locationEn: "A vegetable market",
      participants: "德国女生和卖菜阿姨",
      participantsEn: "A German woman and a vegetable-seller auntie",
      topic: "买菜、聊节气",
      topicEn: "Buying vegetables and talking about solar terms",
    },
    dialogue: [
      notedLine(LESSON_6_5_LINE_NOTES, "A", "哈啰，美女，来哦，今天立冬补冬哦！", "Hello, miss — come on over. Today is Start of Winter: time to nourish!"),
      notedLine(LESSON_6_5_LINE_NOTES, "B", "阿姨，什么冬？", "Auntie, what winter?"),
      notedLine(LESSON_6_5_LINE_NOTES, "A", "立冬是节气，每一年的 11 月 7 号或 8 号。", "Start of Winter is a solar term, every year on November 7 or 8."),
      notedLine(LESSON_6_5_LINE_NOTES, "B", "节气？", "Solar term?"),
      notedLine(LESSON_6_5_LINE_NOTES, "A", "古时候的人的日历，日历你知道吗？一年有二十四个节气。", "The old calendar — you know calendars? There are 24 solar terms in a year."),
      notedLine(LESSON_6_5_LINE_NOTES, "B", "立冬要做什么？", "What do you do at Start of Winter?"),
      notedLine(
        LESSON_6_5_LINE_NOTES,
        "A",
        "补冬，就是要吃好一点，营养一点，准备过冬啊。今天鸡鸭都特价，做个“当归鸭”吧。“当归鸭”（放慢语速）。",
        "Nourish for winter — eat a bit better, a bit more nourishing, get ready for winter. Chicken and duck are on special today. Make angelica duck. “Angelica duck.” (Said slowly.)",
      ),
      notedLine(LESSON_6_5_LINE_NOTES, "B", "我不会。", "I don’t know how."),
      notedLine(
        LESSON_6_5_LINE_NOTES,
        "A",
        "很简单啦，买一只鸭，加这一包中药包和姜片、米酒，放到电锅煮就可以了。可以去对面买一包面线，加面线很好吃！",
        "It’s easy. Buy a duck, add this medicine packet, ginger, and rice wine, put it in the rice cooker. You can buy misua across the aisle — adding noodles is delicious!",
      ),
      notedLine(LESSON_6_5_LINE_NOTES, "B", "好，那我要一只，小一点的。", "Okay — then I’ll take one, a smaller one."),
    ],
    notes: [{ hanzi: "补冬：立冬吃得营养一点，准备过冬。", en: "补冬 is eating richer food at Start of Winter to get through the cold." }],
    coreVocabulary: LESSON_6_5_CORE_VOCAB,
    chunks: LESSON_6_5_CHUNKS,
    expressionFamily: { title: "一套节气说法", titleEn: "One family of solar-term expressions", items: LESSON_6_5_FAMILY },
    grammarFocus: LESSON_6_5_GRAMMAR_FOCUS,
    practiceSentences: LESSON_6_5_PRACTICE,
    fillBlanks: LESSON_6_5_FILL_BLANKS,
    vocabulary: [
      v("节气", "solar term"),
      v("历法", "calendar system"),
      v("很准", "very accurate"),
      v("不准", "inaccurate"),
      v("养生之道", "the way of nourishing life"),
      v("在意", "to care about; to mind"),
      v("当季", "in season"),
      v("盛产", "to produce in abundance"),
      v("补冬", "to nourish for winter"),
      v("人类非物质文化遗产", "UNESCO Intangible Cultural Heritage"),
      v("夏练三伏", "train through the hottest days"),
      v("冬练三九", "train through the coldest days"),
    ],
    questions: [
      q(1, "什么是节气？节气是怎么制定的？", "What is a solar term? How were they set?"),
      q(2, "一年有几个节气？（读读看）", "How many solar terms are there in a year? (Try reading them.)", "reading"),
      q(3, "现在是什么节气？要注意什么或吃什么？", "What solar term is it now? What should you watch or eat?"),
      q(4, "贵国有类似的历法吗？", "Does your country have a similar calendar?"),
      q(5, "你听说过依据节气的养生之道吗？你相信吗？", "Have you heard of solar-term health advice? Do you believe it?"),
      q(6, "你喜欢哪些节气？", "Which solar terms do you like?"),
      q(7, "你不喜欢哪些节气？", "Which solar terms don’t you like?"),
      q(8, "你觉得节气准吗？为什么？", "Do you think solar terms are accurate? Why?"),
      q(9, "你在买菜或外食的时候，会在意是否为当季盛产的食物吗？（你觉得冬天吃西瓜怎么样？）", "When you shop or eat out, do you care if food is in season? (Winter watermelon?)"),
      q(10, "贵国有依据季节的饮食习惯吗？（某个季节吃什么？不吃什么？）", "Does your country eat by season? What do you eat, or not eat, in a given season?"),
      q(11, "贵国人很热的时候会吃什么？怎么降温？", "What do people in your country eat when it’s hot? How do they cool down?"),
      q(12, "贵国人很冷的时候会吃什么？怎么保暖？", "What do people eat when it’s cold? How do they stay warm?"),
      q(13, "为什么说“每个节气日都是一堂自然和文化课”？", "Why say “every solar-term day is a nature-and-culture class”?"),
      q(14, "贵国有不同于公历的特殊历法吗？", "Does your country have a calendar besides the Gregorian one?"),
      q(15, "“仙草”（或称凉粉草）是什么节气吃的？", "At which solar term do people eat grass jelly (仙草 / 凉粉草)?"),
      q(16, "什么时候要“补冬”？", "When do you 补冬?"),
      q(17, "吃什么补冬？", "What do you eat to nourish for winter?"),
      q(18, "山东南部地区为什么会在大暑日喝滚烫的羊肉汤？", "Why do people in southern Shandong drink boiling lamb soup on Major Heat?"),
      q(19, "节气饮食各地不尽相同，调查一下中国南北冬至吃什么？", "Solar-term food differs by region. Look up what north and south China eat at Winter Solstice."),
      q(20, "什么是夏练三伏？", "What is 夏练三伏?"),
      q(21, "什么是冬练三九？", "What is 冬练三九?"),
      q(22, "二十四节气已被列入人类非物质文化遗产代表作名录，你还知道哪些人类非物质文化遗产？", "The 24 solar terms are UNESCO Intangible Cultural Heritage. What other items do you know?"),
      q(23, "搜寻〔搜索〕网上二十四节气的图，选择一个最喜欢的或者尝试自己画一个。", "Look up pictures of the 24 solar terms. Pick a favorite, or try drawing one."),
    ],
  },
]

for (const lesson of UNIT_6) assertLessonReady(lesson)
