/**
 * RULE: every dialogue line is built with notedLine(LESSON_X_Y_LINE_NOTES, …).
 * Keys must match 汉字 exactly, including 〔简历〕 / 〔公交车〕 / 〔数字〕 and spaces around 15 / 24%.
 */
import {
  LESSON_3_1_CHUNKS,
  LESSON_3_1_CORE_VOCAB,
  LESSON_3_1_FAMILY,
  LESSON_3_1_FILL_BLANKS,
  LESSON_3_1_GRAMMAR_FOCUS,
  LESSON_3_1_LINE_NOTES,
  LESSON_3_1_PRACTICE,
} from "@/content/lessons/3-1-notes"
import {
  LESSON_3_2_CHUNKS,
  LESSON_3_2_CORE_VOCAB,
  LESSON_3_2_FAMILY,
  LESSON_3_2_FILL_BLANKS,
  LESSON_3_2_GRAMMAR_FOCUS,
  LESSON_3_2_LINE_NOTES,
  LESSON_3_2_PRACTICE,
} from "@/content/lessons/3-2-notes"
import {
  LESSON_3_3_CHUNKS,
  LESSON_3_3_CORE_VOCAB,
  LESSON_3_3_FAMILY,
  LESSON_3_3_FILL_BLANKS,
  LESSON_3_3_GRAMMAR_FOCUS,
  LESSON_3_3_LINE_NOTES,
  LESSON_3_3_PRACTICE,
} from "@/content/lessons/3-3-notes"
import { assertLessonReady, notedLine } from "@/content/lessons/note-helpers"
import type { Lesson, Question, VocabItem } from "@/lib/types"

function v(hanzi: string, en: string): VocabItem {
  return { hanzi, en }
}

function q(n: number, hanzi: string, en: string, kind?: Question["kind"]): Question {
  return kind ? { n, hanzi, en, kind } : { n, hanzi, en }
}

export const UNIT_3: Lesson[] = [
  {
    id: "3-1",
    unitId: 3,
    title: "工作",
    titleEn: "Work",
    pageStart: 38,
    audioId: "3-1",
    scenario: {
      time: "周一早上",
      timeEn: "Monday morning",
      location: "职业介绍所",
      locationEn: "Employment agency",
      participants: "和职业指导师",
      participantsEn: "With a career counselor",
      topic: "找工作",
      topicEn: "Finding a job",
    },
    dialogue: [
      notedLine(
        LESSON_3_1_LINE_NOTES,
        "A",
        "我看过你的履历〔简历〕和经历了，你会四国语言，机会应该满多的。为什么想留在台湾呢？",
        "I’ve looked at your résumé and experience. You speak four languages — there should be quite a few opportunities. Why do you want to stay in Taiwan?",
      ),
      notedLine(
        LESSON_3_1_LINE_NOTES,
        "B",
        "我喜欢台湾，希望能永久定居，最好能在这里成家立业。",
        "I like Taiwan. I hope I can settle here for good — ideally start a family and a career here.",
      ),
      notedLine(LESSON_3_1_LINE_NOTES, "A", "台湾企业和外商公司，你比较喜欢哪一个？", "Taiwanese companies or foreign ones — which do you prefer?"),
      notedLine(LESSON_3_1_LINE_NOTES, "B", "最好是台湾的，外商公司也可以考虑。", "A Taiwanese one would be best. A foreign company is also worth considering."),
      notedLine(LESSON_3_1_LINE_NOTES, "A", "你介意加班时间吗？", "Do you mind overtime hours?"),
      notedLine(LESSON_3_1_LINE_NOTES, "B", "一个月 15 个小时内可以接受。", "Up to 15 hours a month is acceptable."),
      notedLine(LESSON_3_1_LINE_NOTES, "A", "你曾经用中文进行商务谈判吗？", "Have you ever done business negotiations in Chinese?"),
      notedLine(
        LESSON_3_1_LINE_NOTES,
        "B",
        "以前中文不好，不曾，现在比较好了，我愿意挑战。",
        "My Chinese wasn’t good before, so no. It’s better now — I’m willing to take that on.",
      ),
      notedLine(
        LESSON_3_1_LINE_NOTES,
        "A",
        "好的，我这里有两个机会，你先看一下，我再跟你介绍。",
        "Alright. I have two openings here. Look them over first, then I’ll walk you through them.",
      ),
      notedLine(LESSON_3_1_LINE_NOTES, "B", "好，谢谢。", "OK — thank you."),
    ],
    notes: [
      { hanzi: "履历〔简历〕：台湾说履历，大陆说简历。", en: "履历 is the Taiwan word for a résumé; 简历 is the mainland note in 〔〕." },
      { hanzi: "满多的：口语里满＝蛮，表示相当多。", en: "满多的 is spoken 蛮多的 — quite a lot." },
    ],
    coreVocabulary: LESSON_3_1_CORE_VOCAB,
    chunks: LESSON_3_1_CHUNKS,
    expressionFamily: {
      title: "一套找工作说法",
      titleEn: "One family of job-hunt expressions",
      items: LESSON_3_1_FAMILY,
    },
    grammarFocus: LESSON_3_1_GRAMMAR_FOCUS,
    practiceSentences: LESSON_3_1_PRACTICE,
    fillBlanks: LESSON_3_1_FILL_BLANKS,
    vocabulary: [
      v("通勤", "to commute; commute"),
      v("薪水〔工资〕", "salary / wages"),
      v("前景", "prospects; outlook"),
      v("公职", "public office; government job"),
      v("办公度假", "workcation"),
      v("人际关系", "interpersonal relationships"),
      v("长寿企业", "long-lived company"),
      v("介意", "to mind; to object to"),
      v("外资", "foreign capital / foreign-invested"),
      v("业绩", "performance; results"),
      v("考核", "performance review; to assess"),
      v("终身雇用", "lifetime employment"),
      v("成家立业", "to start a family and a career"),
    ],
    questions: [
      q(1, "你在哪工作？你在现在的公司做了多久了？", "Where do you work? How long have you been at your current company?"),
      q(2, "你每天的通勤时间？贵国一般来说可以自己选择通勤方式吗？", "What’s your daily commute? In your country, can people generally choose how they commute?"),
      q(3, "你的工作上最大的挑战是？", "What’s the biggest challenge in your work?"),
      q(4, "可以在办公室吃早餐和吃点心吗？", "Can you eat breakfast and snacks in the office?"),
      q(
        5,
        "如果有一份工作，薪水是你现在的十倍，但是你不喜欢的工作内容，你愿意做吗？",
        "If a job paid ten times your current salary but you disliked the work itself, would you take it?",
      ),
      q(6, "你喜欢在家工作还是在公司工作？为什么？", "Do you like working from home or in the office? Why?"),
      q(7, "你换过工作吗？（为什么换？）", "Have you changed jobs? (Why?)"),
      q(8, "你选择工作时会考虑的条件，照重要性排列是？", "When you choose a job, what conditions do you consider, ranked by importance?"),
      q(9, "二选一，你会选择贷款自己创业还是为别人工作赚钱？", "Would you rather take a loan and start your own business, or work for someone else to earn money?"),
      q(10, "你什么时候决定从事现在的工作？怎么找，在哪里找的工作？", "When did you decide on your current work? How and where did you find the job?"),
      q(11, "如果你能做地球上任何一份工作一年，你想试做什么工作？", "If you could do any job on earth for one year, what would you try?"),
      q(12, "什么工作是给你再高的薪水你也不想做的？", "What job would you refuse no matter how high the salary?"),
      q(13, "如果你的伴侣在另外一个国家获得了一份很好的工作，你会怎么做？", "If your partner got a great job in another country, what would you do?"),
      q(14, "你的工作常需要加班和出差吗？", "Does your work often need overtime and business trips?"),
      q(15, "你对终身雇用制的看法？", "What’s your view of the lifetime-employment system?"),
      q(16, "本国大企业和外资大企业，你比较喜欢去哪一种公司上班？", "A big domestic firm or a big foreign-invested one — which would you rather work for?"),
      q(17, "在贵国，妇女们结婚后通常会工作还是做全职主妇？", "In your country, do women usually keep working after marriage, or become full-time homemakers?"),
      q(18, "如果能够，你愿意担任公职吗？", "If you could, would you take a government job?"),
      q(19, "你打过工吗？什么工作？", "Have you ever worked a part-time or casual job? Doing what?"),
      q(20, "996 是什么？在贵国 996 是违法的吗？", "What is 996? Is 996 illegal in your country?"),
      q(21, "你比较喜欢按照年资还是按照业绩考核调升薪水？为什么？", "Would you rather get raises by seniority or by performance review? Why?"),
      q(22, "言语暴力是职场霸凌中最常见的形式，你的上司经常使用言语暴力吗？", "Verbal abuse is the most common form of workplace bullying. Does your boss often use it?"),
      q(23, "你或你朋友遭受过职场霸凌吗？", "Have you or a friend experienced workplace bullying?"),
      q(24, "你对打工度假 (working holiday) 的看法？", "What’s your view of a working holiday?"),
      q(25, "什么是办公度假 (workcation) ？你想办公度假吗？去哪里？", "What is a workcation? Would you want one? Where?"),
      q(26, "将来哪些工作会被 AI 取代？哪些工作比较难被取代？", "Which jobs will AI replace in the future? Which are harder to replace?"),
    ],
  },
  {
    id: "3-2",
    unitId: 3,
    title: "人格特质和智商",
    titleEn: "Personality and intelligence",
    pageStart: 40,
    audioId: "3-2",
    scenario: {
      time: "划手机等公车〔公交车〕时",
      timeEn: "While scrolling the phone, waiting for the bus",
      location: "公车〔公交车〕站牌",
      locationEn: "Bus stop",
      participants: "和朋友",
      participantsEn: "With a friend",
      topic: "聊人格特质测验",
      topicEn: "Chatting about a personality quiz",
    },
    dialogue: [
      notedLine(
        LESSON_3_2_LINE_NOTES,
        "A",
        "这个心理测验很有意思——你是三国演义中的哪个人物？",
        "This personality quiz is really interesting — which Three Kingdoms character are you?",
      ),
      notedLine(LESSON_3_2_LINE_NOTES, "B", "传连结给我，我也来做做看。", "Send me the link. I’ll try it too."),
      notedLine(
        LESSON_3_2_LINE_NOTES,
        "A",
        "我是张飞，敢爱敢恨，有时粗鲁莽撞，有时懂得算计。",
        "I’m Zhang Fei: I love and hate out in the open — sometimes reckless, sometimes calculating.",
      ),
      notedLine(LESSON_3_2_LINE_NOTES, "B", "挺准的！我是司马懿。", "Pretty accurate! I’m Sima Yi."),
      notedLine(LESSON_3_2_LINE_NOTES, "A", "司马懿？！他冷酷残忍哦。", "Sima Yi?! He’s cold and cruel, you know."),
      notedLine(
        LESSON_3_2_LINE_NOTES,
        "B",
        "生性多疑，但是也是一个雄才大略、才智过人的大将。",
        "Suspicious by nature — but also a general of great vision and extraordinary mind.",
      ),
      notedLine(LESSON_3_2_LINE_NOTES, "A", "三国演义中你最喜欢谁？", "Who do you like most in Romance of the Three Kingdoms?"),
      notedLine(
        LESSON_3_2_LINE_NOTES,
        "B",
        "当然是诸葛亮，他太聪明了，我要是也料事如神就好了。",
        "Zhuge Liang, of course. He’s so smart. If only I could see things coming like that too.",
      ),
      notedLine(
        LESSON_3_2_LINE_NOTES,
        "A",
        "我喜欢赵云，他能独立思考，有自己的见解，有才智，有胆识。",
        "I like Zhao Yun. He can think independently, has his own views, brains, and guts.",
      ),
      notedLine(LESSON_3_2_LINE_NOTES, "B", "公车〔公交车〕来了！", "The bus is here!"),
    ],
    notes: [
      { hanzi: "连结：台湾说法，大陆多说链接。", en: "连结 is the Taiwan word for a URL / link; mainland speech usually uses 链接." },
      { hanzi: "三国演义人物常被拿来当人格标签：张飞、司马懿、诸葛亮、赵云。", en: "Three Kingdoms characters are used here as personality labels." },
    ],
    coreVocabulary: LESSON_3_2_CORE_VOCAB,
    chunks: LESSON_3_2_CHUNKS,
    expressionFamily: {
      title: "一套人格和智商说法",
      titleEn: "One family of personality and IQ expressions",
      items: LESSON_3_2_FAMILY,
    },
    grammarFocus: LESSON_3_2_GRAMMAR_FOCUS,
    practiceSentences: LESSON_3_2_PRACTICE,
    fillBlanks: LESSON_3_2_FILL_BLANKS,
    vocabulary: [
      v("人格特质", "personality trait"),
      v("敬佩", "to admire"),
      v("历史英雄", "historical hero"),
      v("粗鲁莽撞", "rough and reckless"),
      v("冷酷", "cold; callous"),
      v("残忍", "cruel"),
      v("算计", "to calculate; to scheme"),
      v("才智过人", "extraordinarily intelligent"),
      v("胆识", "courage and judgment"),
      v("雄才大略", "great talent and bold vision"),
      v("智商", "IQ"),
      v("情商", "EQ; emotional intelligence"),
      v("逆境", "adversity"),
      v("财商", "financial intelligence"),
    ],
    questions: [
      q(1, "请用三个词形容你自己。", "Describe yourself in three words."),
      q(2, "你喜欢和不喜欢什么样的人？", "What kind of people do you like and dislike?"),
      q(3, "说说你最敬佩的人。", "Talk about the person you admire most."),
      q(4, "你觉得公司老板要有什么人格特质？", "What personality traits does a company boss need?"),
      q(5, "当国家领袖要有什么人格特质？", "What personality traits does a national leader need?"),
      q(6, "你不喜欢和什么样的人一起工作？", "What kind of person do you dislike working with?"),
      q(7, "你曾经因为人际关系问题辞职吗？", "Have you ever resigned because of relationship problems at work?"),
      q(8, "请介绍一位你们国家的历史英雄。", "Introduce a historical hero from your country."),
      q(9, "如果你是老板，选员工时你注重什么样的人格特质？", "If you were the boss, what traits would you look for when hiring?"),
      q(10, "选未来伴侣时，你注重什么样的人格特质？", "When choosing a future partner, what traits do you care about?"),
      q(11, "你遇到过你觉得“最好的好人”是谁，为什么？", "Who is the “best good person” you’ve met, and why?"),
      q(12, "你觉得你有领导力吗？", "Do you think you have leadership?"),
      q(13, "如果你是时代杂志编辑，你要选谁当“21 世纪代表人物”的封面？", "If you edited Time, who would you put on a “21st-century representative” cover?"),
      q(14, "你觉得先天智商和后天环境哪一个影响人的成就比较大？", "Which shapes achievement more: inborn IQ or later environment?"),
      q(15, "什么是情商？你的情商高吗？", "What is EQ? Is yours high?"),
      q(16, "什么是文化智商？你的文化智商高吗？", "What is cultural intelligence? Is yours high?"),
      q(17, "什么是逆境智商？你的逆境智商高吗？", "What is adversity quotient? Is yours high?"),
      q(18, "什么是财商？你的财商高吗？", "What is financial intelligence? Is yours high?"),
      q(19, "你现在的工作最需要哪种“商”（quotient）高？", "Which “quotient” does your current job need most?"),
      q(20, "你想增进你的什么商？", "Which quotient do you want to improve?"),
      q(21, "你觉得哪个明星或名人的情商高？为什么？", "Which celebrity do you think has high EQ? Why?"),
      q(22, "你如何评价自己的沟通能力？", "How do you rate your own communication skill?"),
      q(23, "你觉得你有自信吗？0～100 分，给自己的自信打分。", "Do you think you have confidence? Score yourself from 0 to 100."),
      q(24, "如果来世可以选择人格特质，你想要较高的什么商？（按照顺序）", "If you could choose traits in a next life, which quotients would you want higher? (In order.)"),
    ],
  },
  {
    id: "3-3",
    unitId: 3,
    title: "模拟求职面试",
    titleEn: "Mock job interview",
    pageStart: 42,
    audioId: "3-3",
    scenario: {
      time: "下午2点",
      timeEn: "2 p.m.",
      location: "办公室",
      locationEn: "Office",
      participants: "和面试官",
      participantsEn: "With the interviewer",
      topic: "面试",
      topicEn: "Interview",
    },
    dialogue: [
      notedLine(LESSON_3_3_LINE_NOTES, "A", "为什么我们公司要用你而不是其他人？", "Why should our company use you rather than someone else?"),
      notedLine(
        LESSON_3_3_LINE_NOTES,
        "B",
        "贵公司需要对数位〔数字〕领域充满热情及经验的行销〔营销〕人员。在我之前的工作中，我成功地提升了公司社群媒体广告 24% 的成效。因此，我很希望也可以在这里贡献自己的创意与热情。",
        "Your company needs marketers with passion and experience in the digital field. In my last job I raised social-media ad results by 24%. So I very much hope I can contribute my creativity and passion here too.",
      ),
      notedLine(LESSON_3_3_LINE_NOTES, "A", "如果一直达不到工作目标时，你会怎么办？", "If you keep missing the work target, what will you do?"),
      notedLine(
        LESSON_3_3_LINE_NOTES,
        "B",
        "我会花更多的时间，去观察现象、寻找有效方法，充实自己，勇敢尝试。",
        "I’ll spend more time observing what’s going on, looking for methods that work, upskilling myself, and trying bravely.",
      ),
      notedLine(LESSON_3_3_LINE_NOTES, "A", "你觉得你的缺点是什么？", "What do you think your weakness is?"),
      notedLine(
        LESSON_3_3_LINE_NOTES,
        "B",
        "我简报还做得不够好，所以最近上了很多简报训练课。",
        "My presentations still aren’t good enough, so lately I’ve taken a lot of presentation-training classes.",
      ),
      notedLine(LESSON_3_3_LINE_NOTES, "A", "为什么想来我们公司？", "Why do you want to come to our company?"),
      notedLine(
        LESSON_3_3_LINE_NOTES,
        "B",
        "因为贵公司的创业历史让我很感动，还有贵公司的文化与风格跟我个人的态度非常相似，都是热爱帮助他人解决问题。",
        "Because your founding story really moved me, and your culture and style are very like my own attitude — we’re both passionate about helping others solve problems.",
      ),
      notedLine(LESSON_3_3_LINE_NOTES, "A", "对于我们公司或这个职位，你有什么问题？", "Do you have any questions about our company or this role?"),
      notedLine(
        LESSON_3_3_LINE_NOTES,
        "B",
        "有什么您正在寻找的特质与能力，是在我身上没看到的吗？",
        "Is there a trait or skill you’re looking for that you haven’t seen in me?",
      ),
    ],
    notes: [
      { hanzi: "数位〔数字〕、行销〔营销〕：台湾用语，括号里是大陆说法。", en: "数位 and 行销 are Taiwan words; 〔数字〕 and 〔营销〕 are the mainland notes." },
      { hanzi: "简报：台湾对 presentation / slides 的说法。", en: "简报 is the Taiwan word for a (slide) presentation." },
    ],
    coreVocabulary: LESSON_3_3_CORE_VOCAB,
    chunks: LESSON_3_3_CHUNKS,
    expressionFamily: {
      title: "一套面试说法",
      titleEn: "One family of interview expressions",
      items: LESSON_3_3_FAMILY,
    },
    grammarFocus: LESSON_3_3_GRAMMAR_FOCUS,
    practiceSentences: LESSON_3_3_PRACTICE,
    fillBlanks: LESSON_3_3_FILL_BLANKS,
    vocabulary: [
      v("模拟求职", "mock job hunt / mock application"),
      v("成就", "achievement"),
      v("应征", "to apply for (a job)"),
      v("负责", "to be responsible for"),
      v("直属", "direct (supervisor / report)"),
      v("上司", "boss; supervisor"),
      v("福利", "benefits; perks"),
      v("职位", "position; post"),
      v("管理风格", "management style"),
      v("实质", "substance; real / substantial"),
      v("领导力", "leadership"),
      v("职业生涯规划", "career planning"),
      v("家属", "family dependents"),
      v("调职", "to transfer (jobs / posts)"),
    ],
    questions: [
      q(1, "搜寻〔搜索〕人力银行或招聘网，找一份你有兴趣的工作。为什么想应征这份工作？", "Search a job bank or hiring site, find a job you like. Why apply for it?"),
      q(2, "搜寻〔搜索〕“令人心动的 offer”影片，体演模拟面试。1 分钟自我介绍。", "Search “令人心动的 offer” videos and act out a mock interview. One-minute self-intro."),
      q(3, "为什么我们公司要用你而不是其他人？", "Why should our company use you rather than someone else?"),
      q(4, "你到目前为止最大的失败经验是什么？", "What’s your biggest failure so far?"),
      q(5, "你最大的成就是什么？", "What’s your biggest achievement?"),
      q(6, "你的短期、中期和长期目标各是什么？", "What are your short-, mid-, and long-term goals?"),
      q(7, "小组工作中你想当负责人吗？", "In group work, do you want to be the person in charge?"),
      q(8, "你喜欢一个人工作还是小组工作？", "Do you like working alone or in a group?"),
      q(9, "你理想的公司是什么样的？你期待的福利？", "What’s your ideal company like? What benefits do you expect?"),
      q(10, "你现在的老板怎么样？你希望你的直属上司是什么样的人？", "What’s your current boss like? What do you want your direct supervisor to be like?"),
      q(11, "如果你是人事主管，你想雇用什么样的员工？", "If you were in HR, what kind of employee would you want to hire?"),
      q(12, "你的管理风格是什么？", "What’s your management style?"),
      q(13, "你是否曾在工作中遇到过困难？如果是，你是如何克服的？", "Have you hit difficulties at work? If so, how did you get through them?"),
      q(14, "你需要多长时间才能为我们公司做出实质贡献？", "How long would you need before you could make a real contribution here?"),
      q(15, "如果可以改善你现在的公司，你最想改善的是什么？", "If you could improve your current company, what would you change first?"),
      q(16, "你下个月想做的两件事。", "Two things you want to do next month."),
      q(17, "对于我们公司或这个职位，你有什么问题？", "Do you have any questions about our company or this role?"),
      q(18, "未来十二个月你想做的三件事。", "Three things you want to do in the next twelve months."),
      q(19, "你最近完成的三件事。", "Three things you finished recently."),
      q(20, "你曾经用中文进行商务谈判吗？", "Have you ever done business negotiations in Chinese?"),
      q(21, "你愿意被调到外地或国外吗？", "Would you be willing to be transferred elsewhere in the country or abroad?"),
      q(22, "你认为我们这个行业的重要趋势是什么？", "What do you think are the important trends in this industry?"),
    ],
  },
]

for (const lesson of UNIT_3) assertLessonReady(lesson)
