/**
 * RULE: every dialogue line is built with notedLine(LESSON_X_Y_LINE_NOTES, …).
 * Keys must match 汉字 exactly, including 〔菠萝〕 / 〔盒饭〕 / 〔搜索〕, Latin Balut / OKOK / Er / Hmm / Cultural Appropriation, spaces around 10, and —— / …… / ？！
 */
import {
  LESSON_5_1_CHUNKS,
  LESSON_5_1_CORE_VOCAB,
  LESSON_5_1_FAMILY,
  LESSON_5_1_FILL_BLANKS,
  LESSON_5_1_GRAMMAR_FOCUS,
  LESSON_5_1_LINE_NOTES,
  LESSON_5_1_PRACTICE,
} from "@/content/lessons/5-1-notes"
import {
  LESSON_5_2_CHUNKS,
  LESSON_5_2_CORE_VOCAB,
  LESSON_5_2_FAMILY,
  LESSON_5_2_FILL_BLANKS,
  LESSON_5_2_GRAMMAR_FOCUS,
  LESSON_5_2_LINE_NOTES,
  LESSON_5_2_PRACTICE,
} from "@/content/lessons/5-2-notes"
import {
  LESSON_5_3_CHUNKS,
  LESSON_5_3_CORE_VOCAB,
  LESSON_5_3_FAMILY,
  LESSON_5_3_FILL_BLANKS,
  LESSON_5_3_GRAMMAR_FOCUS,
  LESSON_5_3_LINE_NOTES,
  LESSON_5_3_PRACTICE,
} from "@/content/lessons/5-3-notes"
import {
  LESSON_5_4_CHUNKS,
  LESSON_5_4_CORE_VOCAB,
  LESSON_5_4_FAMILY,
  LESSON_5_4_FILL_BLANKS,
  LESSON_5_4_GRAMMAR_FOCUS,
  LESSON_5_4_LINE_NOTES,
  LESSON_5_4_PRACTICE,
} from "@/content/lessons/5-4-notes"
import {
  LESSON_5_5_CHUNKS,
  LESSON_5_5_CORE_VOCAB,
  LESSON_5_5_FAMILY,
  LESSON_5_5_FILL_BLANKS,
  LESSON_5_5_GRAMMAR_FOCUS,
  LESSON_5_5_LINE_NOTES,
  LESSON_5_5_PRACTICE,
} from "@/content/lessons/5-5-notes"
import { assertLessonReady, notedLine } from "@/content/lessons/note-helpers"
import type { Lesson, Question, VocabItem } from "@/lib/types"

function v(hanzi: string, en: string): VocabItem {
  return { hanzi, en }
}

function q(n: number, hanzi: string, en: string, kind?: Question["kind"]): Question {
  return kind ? { n, hanzi, en, kind } : { n, hanzi, en }
}

export const UNIT_5: Lesson[] = [
  {
    id: "5-1",
    unitId: 5,
    title: "饮食习惯",
    titleEn: "Eating habits",
    pageStart: 62,
    audioId: "5-1",
    scenario: {
      time: "周末下午",
      timeEn: "Weekend afternoon",
      location: "摄影俱乐部",
      locationEn: "A photography club",
      participants: "和朋友",
      participantsEn: "With a friend",
      topic: "聊毛蛋",
      topicEn: "Talking about balut",
    },
    dialogue: [
      notedLine(LESSON_5_1_LINE_NOTES, "A", "你去菲律宾回来啦？拍得怎么样？", "You’re back from the Philippines? How did the photos turn out?"),
      notedLine(LESSON_5_1_LINE_NOTES, "B", "很不错，运气好，天气都很好。", "Pretty good — lucky, the weather was great the whole time."),
      notedLine(LESSON_5_1_LINE_NOTES, "A", "看一下相片吧。", "Let’s look at the photos."),
      notedLine(LESSON_5_1_LINE_NOTES, "B", "这是长滩岛，这是马尼拉，这是传统市场的小吃。", "This is Boracay, this is Manila, this is a snack from a traditional market."),
      notedLine(LESSON_5_1_LINE_NOTES, "A", "天啊，你敢吃毛蛋？！", "Oh my god — you dared to eat balut?!"),
      notedLine(LESSON_5_1_LINE_NOTES, "B", "Balut，我看当地人都在吃，很好奇，试了一个。", "Balut. The locals were all eating it, so I was curious and tried one."),
      notedLine(LESSON_5_1_LINE_NOTES, "A", "（惊恐）那里面有刚孵化的小鸭吧？怎么吃啊？！", "(Horrified) There’s a duckling that just hatched in there, right? How do you even eat that?!"),
      notedLine(LESSON_5_1_LINE_NOTES, "B", "就一口吸进去啊。（发出吸的声音）", "You just suck it down in one go. (Makes a sucking sound.)"),
      notedLine(LESSON_5_1_LINE_NOTES, "A", "我快反胃了。", "I’m about to throw up."),
      notedLine(
        LESSON_5_1_LINE_NOTES,
        "B",
        "这还好啦，东南亚还有更恐怖的料理，烤蜘蛛啦、油炸蝙蝠啦……",
        "This is nothing. Southeast Asia has even scarier dishes — grilled spider, deep-fried bat…",
      ),
      notedLine(LESSON_5_1_LINE_NOTES, "A", "OKOK！我刚吃饱。看风景照就好。", "OK OK! I just ate. Let’s stick to the landscape shots."),
    ],
    notes: [{ hanzi: "毛蛋：菲律宾 Balut，孵化中的鸭蛋。", en: "毛蛋 is balut — a fertilized duck egg eaten in the Philippines." }],
    coreVocabulary: LESSON_5_1_CORE_VOCAB,
    chunks: LESSON_5_1_CHUNKS,
    expressionFamily: { title: "一套饮食习惯说法", titleEn: "One family of eating-habit expressions", items: LESSON_5_1_FAMILY },
    grammarFocus: LESSON_5_1_GRAMMAR_FOCUS,
    practiceSentences: LESSON_5_1_PRACTICE,
    fillBlanks: LESSON_5_1_FILL_BLANKS,
    vocabulary: [
      v("下厨", "to cook; to go into the kitchen"),
      v("拿手菜", "signature dish"),
      v("料理", "cuisine; a dish"),
      v("讲究", "particular about"),
      v("余生", "the rest of one’s life"),
      v("特色菜", "specialty dish"),
      v("主食", "staple food"),
      v("奇特", "unusual; peculiar"),
      v("过敏", "allergy; allergic"),
      v("做菜", "to cook a dish"),
      v("反胃", "to feel nauseous"),
      v("堆肥", "compost"),
      v("农业", "agriculture"),
      v("产地", "place of origin"),
      v("餐桌", "dining table"),
      v("小菜", "side dish"),
    ],
    questions: [
      q(1, "贵国的主食是什么？", "What is the staple food in your country?"),
      q(2, "你喜欢下厨吗？你的拿手菜是什么？", "Do you like to cook? What’s your signature dish?"),
      q(3, "你最常喝的饮料是什么？你会喝酒吗？（什么酒？）", "What drink do you have most often? Do you drink alcohol? (What kind?)"),
      q(4, "你常和公司同事或朋友聚餐吗？", "Do you often eat out with coworkers or friends?"),
      q(5, "你讲究饮食吗？", "Are you particular about food?"),
      q(6, "你不敢吃什么？你很能吃辣吗？", "What don’t you dare eat? Can you handle spice?"),
      q(7, "你敢吃昆虫吗？昆虫食有分级，1是粉末加工品，5是炸整只虫，你敢吃第几级？", "Do you dare eat insects? Insect food has levels: 1 is powder, 5 is a whole fried insect. Which level would you try?"),
      q(8, "外出用餐时你喜欢去哪种餐厅？", "When you eat out, what kind of restaurant do you like?"),
      q(9, "除了本国菜以外，你喜欢吃哪一国的菜？", "Besides your own country’s food, which country’s food do you like?"),
      q(10, "如果在你余生里只能吃一种食物（假设不会影响你的健康），你会选择哪种食物？", "If you could eat only one food for the rest of your life (and it wouldn’t hurt your health), which would you pick?"),
      q(11, "现在流行什么饮食方式？或举例说明现在流行吃什么？", "What eating styles are in now? Or give an example of what’s trendy to eat."),
      q(12, "你有没有食物过敏？", "Do you have any food allergies?"),
      q(13, "你吃过最奇特的食物是什么？", "What’s the most unusual food you’ve eaten?"),
      q(14, "你吃过最好的一餐是在哪里吃什么？", "Where was the best meal you’ve had, and what was it?"),
      q(15, "你家乡的特色菜是什么？你最怀念哪一道菜？", "What’s a specialty dish from your hometown? Which dish do you miss most?"),
      q(16, "你喜欢任你吃到饱的自助餐吗？为什么？", "Do you like all-you-can-eat buffets? Why?"),
      q(17, "你觉得未来的饮食文化趋势是什么？试从产地到餐桌阶段讨论。（堆肥、农业、贸易、饮食）", "What do you think the future of food culture is? Talk from farm to table (compost, farming, trade, eating)."),
      q(18, "你住的地方，当地人早餐大多吃什么？", "Where you live, what do locals usually eat for breakfast?"),
      q(19, "你妈妈的拿手菜是什么？你会做吗？", "What’s your mum’s signature dish? Can you cook it?"),
      q(20, "如果现在你可以立刻吃到一道菜，你想吃什么？", "If you could eat one dish right now, what would it be?"),
      q(21, "你的文化在碗盘内残留食物是没礼貌的吗？", "In your culture, is leaving food on the plate rude?"),
      q(22, "你曾经一个人去酒吧喝酒吗？", "Have you ever gone to a bar alone for a drink?"),
      q(23, "请用一句话形容你们当地的食物特色。", "Describe your local food in one sentence."),
      q(24, "举例说明贵国出名的料理。", "Give an example of a famous dish from your country."),
      q(25, "如果你能选择任何一种食物，人生的最后一餐你想吃什么？", "If you could choose any food, what would you want for your last meal?"),
    ],
  },
  {
    id: "5-2",
    unitId: 5,
    title: "披萨",
    titleEn: "Pizza",
    pageStart: 64,
    audioId: "5-2",
    scenario: {
      time: "午餐叫外送",
      timeEn: "Ordering delivery for lunch",
      location: "台湾的旅馆",
      locationEn: "A hotel in Taiwan",
      participants: "背包客（意大利人和中国人）",
      participantsEn: "Backpackers (an Italian and a Chinese person)",
      topic: "谈披萨口味",
      topicEn: "Talking about pizza flavors",
    },
    dialogue: [
      notedLine(LESSON_5_2_LINE_NOTES, "A", "午餐吃什么？我们一起叫外送吧？", "What for lunch? Shall we order delivery together?"),
      notedLine(LESSON_5_2_LINE_NOTES, "B", "好啊，这家披萨怎么样？买二送一呢！", "Sure — how about this pizza place? It’s buy two, get one free!"),
      notedLine(LESSON_5_2_LINE_NOTES, "A", "好，我看。天啊，网上说的是真的，居然有凤梨〔菠萝〕披萨！", "Okay, let me look. Oh my god — what they say online is true. There’s actually pineapple pizza!"),
      notedLine(
        LESSON_5_2_LINE_NOTES,
        "B",
        "叫“夏威夷”，很有热带风情吧！还有其他台湾特色披萨哦，这个，珍珠奶茶披萨……",
        "It’s called Hawaiian — very tropical, right? There are other Taiwan-specialty pizzas too. Look, bubble-tea pizza…",
      ),
      notedLine(LESSON_5_2_LINE_NOTES, "A", "我受不了，这怎么能叫“披萨”？这不是披萨！", "I can’t stand it. How can this be called pizza? This is not pizza!"),
      notedLine(LESSON_5_2_LINE_NOTES, "B", "看起来像披萨啊，料不同而已，这是当地特色，很正常吧？", "It looks like pizza — just different toppings. It’s a local specialty. That’s normal, right?"),
      notedLine(LESSON_5_2_LINE_NOTES, "A", "这是食物犯罪！Cultural Appropriation，“文化挪用”？", "This is a food crime! Cultural appropriation?"),
      notedLine(
        LESSON_5_2_LINE_NOTES,
        "B",
        "你们太神经质了，这么严格的话，要我说外国所谓的中国料理没几家合格的。",
        "You’re too sensitive. If we’re being that strict, I’d say hardly any so-called Chinese places abroad are authentic.",
      ),
      notedLine(LESSON_5_2_LINE_NOTES, "A", "还有你们煮的意大利面也不及格！", "And the pasta you cook doesn’t pass either!"),
      notedLine(LESSON_5_2_LINE_NOTES, "B", "算了，我们叫便当〔盒饭〕好了。", "Forget it. Let’s just order boxed lunches."),
    ],
    notes: [{ hanzi: "披萨，也称为比萨或比萨饼。", en: "披萨 is also written 比萨 or 比萨饼." }],
    coreVocabulary: LESSON_5_2_CORE_VOCAB,
    chunks: LESSON_5_2_CHUNKS,
    expressionFamily: { title: "一套披萨说法", titleEn: "One family of pizza expressions", items: LESSON_5_2_FAMILY },
    grammarFocus: LESSON_5_2_GRAMMAR_FOCUS,
    practiceSentences: LESSON_5_2_PRACTICE,
    fillBlanks: LESSON_5_2_FILL_BLANKS,
    vocabulary: [
      v("披萨", "pizza"),
      v("饼皮厚度", "crust thickness"),
      v("口味", "flavor; topping"),
      v("叫外送", "to order delivery"),
      v("凤梨〔菠萝〕", "pineapple"),
      v("火腿", "ham"),
      v("无法忍受", "unable to stand"),
      v("甩", "to toss (dough)"),
      v("无形文化遗产", "intangible cultural heritage"),
      v("申遗", "to apply for World Heritage status"),
      v("起源", "origin"),
      v("创意", "creative; creativity"),
      v("文化挪用", "cultural appropriation"),
    ],
    questions: [
      q(1, "你喜欢披萨吗？意大利料理中你最喜欢什么？", "Do you like pizza? What’s your favorite Italian dish?"),
      q(2, "你喜欢薄皮的还是厚皮的披萨？", "Do you like thin-crust or thick-crust pizza?"),
      q(3, "你最喜欢的披萨口味是什么？（馅料 / 酱）", "What’s your favorite pizza flavor? (toppings / sauce)"),
      q(4, "你做过披萨吗？", "Have you ever made pizza?"),
      q(5, "你大约多久吃一次披萨？", "About how often do you eat pizza?"),
      q(6, "你通常什么时候吃披萨？（正餐 / 点心 / 宵夜 / 聚会……）", "When do you usually eat pizza? (meal / snack / late-night / party…)"),
      q(7, "你最后一次叫外送披萨是什么时候？", "When was the last time you ordered pizza delivery?"),
      q(8, "你家附近有披萨店吗？你最喜欢哪一家的披萨？", "Is there a pizza place near you? Which one do you like best?"),
      q(9, "除了披萨，你还吃过什么类似的饼食？你最喜欢什么饼食？", "Besides pizza, what similar flatbreads have you had? Which do you like best?"),
      q(10, "你去意大利吃过披萨吗？有什么不一样吗？", "Have you eaten pizza in Italy? How was it different?"),
      q(11, "听说意大利人无法忍受亚洲的“夏威夷风披萨”（凤梨〔菠萝〕火腿），你有没有无法忍受的披萨口味？", "Italians are said to hate Asian Hawaiian pizza (pineapple ham). Is there a pizza flavor you can’t stand?"),
      q(12, "你吃过最特别的披萨是什么？", "What’s the most unusual pizza you’ve eaten?"),
      q(13, "你喜欢吃披萨时喝什么饮料？", "What do you like to drink with pizza?"),
      q(14, "是谁发明了披萨？（你听过披萨起源和中国有关的故事吗？）", "Who invented pizza? (Have you heard the story that pizza’s origin is connected to China?)"),
      q(15, "你觉得披萨受欢迎的原因是什么？", "Why do you think pizza is so popular?"),
      q(16, "贵国有类似披萨的食物吗？怎么做？跟披萨一样受欢迎吗？", "Does your country have a pizza-like food? How is it made? Is it as popular?"),
      q(17, "如果你可以做一张创意披萨，那将会是什么样的？", "If you could make a creative pizza, what would it be?"),
      q(18, "搜寻〔搜索〕台湾的特色披萨：大肠面线披萨、香菜皮蛋猪血糕披萨、臭豆腐披萨、珍奶披萨、肉圆披萨……等，你想吃吗？", "Look up Taiwan specialty pizzas: oyster-vermicelli, cilantro–century-egg–blood-cake, stinky tofu, bubble-tea, meatball… Would you try them?"),
      q(19, "正宗的拿坡里披萨是有证书的，搜寻〔搜索〕符合 STG 认证的条件是什么？", "Authentic Neapolitan pizza is certified. Look up what STG certification requires."),
      q(20, "为什么要把面团甩上空而不用擀面棍？", "Why toss the dough in the air instead of using a rolling pin?"),
      q(21, "意大利拿坡里披萨被联合国教科文组织（UNESCO）列为世界“无形文化遗产”，还有哪些美食被认定？", "Neapolitan pizza is UNESCO intangible cultural heritage. What other foods have that status?"),
      q(22, "你觉得贵国的什么美食应该要列为无形文化遗产？", "What food from your country should be listed as intangible cultural heritage?"),
      q(23, "为什么中华美食还没有申遗成功？", "Why hasn’t Chinese cuisine succeeded in the World Heritage application?"),
    ],
  },
  {
    id: "5-3",
    unitId: 5,
    title: "茶和咖啡",
    titleEn: "Tea and coffee",
    pageStart: 66,
    audioId: "5-3",
    scenario: {
      time: "周末下午",
      timeEn: "Weekend afternoon",
      location: "台湾朋友家",
      locationEn: "A Taiwanese friend’s home",
      participants: "和英国朋友",
      participantsEn: "With a British friend",
      topic: "品茶",
      topicEn: "Tasting tea",
    },
    dialogue: [
      notedLine(LESSON_5_3_LINE_NOTES, "A", "来，请喝。这是闻香杯，这样子，盖住，立刻翻过去，小心。", "Here — please drink. This is an aroma cup. Like this: cover it, flip it right away. Careful."),
      notedLine(LESSON_5_3_LINE_NOTES, "B", "Er……这样……", "Er… like this…"),
      notedLine(LESSON_5_3_LINE_NOTES, "A", "对，很好！先闻这个杯子，再喝。怎么样？", "Yes — good! Smell this cup first, then drink. How is it?"),
      notedLine(LESSON_5_3_LINE_NOTES, "B", "Hmm～好香啊！看起来颜色很浅，可是很香，嘴巴内很甜！", "Hmm — so fragrant! The color looks light, but it smells strong, and it’s sweet in the mouth."),
      notedLine(LESSON_5_3_LINE_NOTES, "A", "我们叫“甘”，吞下后，喉咙会一直甜甜的，叫回甘。", "We call that 甘. After you swallow, the throat stays sweet — that’s 回甘."),
      notedLine(LESSON_5_3_LINE_NOTES, "B", "太赞了，我应该买高山茶回去，泡给我家人喝！", "Amazing. I should buy high-mountain tea and brew it for my family!"),
      notedLine(LESSON_5_3_LINE_NOTES, "A", "英国人平常喝红茶吧？你们也有茶道吗？", "The British usually drink black tea, right? Do you have a tea ceremony too?"),
      notedLine(
        LESSON_5_3_LINE_NOTES,
        "B",
        "没有，就是喝茶吃点心而已，有的高级餐厅在下午茶时间会有竖琴演奏。",
        "No — it’s just tea and snacks. Some fancy restaurants have a harp at afternoon tea.",
      ),
      notedLine(
        LESSON_5_3_LINE_NOTES,
        "A",
        "我们也有点心，跟你们不一样。你尝尝看，这是瓜子、花生、绿豆糕、核桃糕。",
        "We have snacks too, different from yours. Try some — melon seeds, peanuts, mung-bean cake, walnut cake.",
      ),
    ],
    notes: [{ hanzi: "闻香杯：闻茶香的杯子，盖住后立刻翻过去再闻。", en: "An aroma cup is for smelling tea: cover it, flip it, then smell." }],
    coreVocabulary: LESSON_5_3_CORE_VOCAB,
    chunks: LESSON_5_3_CHUNKS,
    expressionFamily: { title: "一套茶和咖啡说法", titleEn: "One family of tea-and-coffee expressions", items: LESSON_5_3_FAMILY },
    grammarFocus: LESSON_5_3_GRAMMAR_FOCUS,
    practiceSentences: LESSON_5_3_PRACTICE,
    fillBlanks: LESSON_5_3_FILL_BLANKS,
    vocabulary: [
      v("泡茶", "to brew tea"),
      v("招待", "to host; to treat a guest"),
      v("茶道", "tea ceremony"),
      v("茶会", "tea gathering"),
      v("茶点", "tea snacks"),
      v("茶具", "tea ware"),
      v("讲究", "particular about"),
      v("手冲咖啡", "pour-over coffee"),
      v("焙煎", "roasting (coffee/tea)"),
      v("滤泡", "drip brew"),
      v("三合一", "3-in-1 instant coffee"),
      v("挂耳", "drip-bag coffee"),
      v("渣", "dregs; grounds"),
      v("花道", "flower arranging"),
      v("书道", "calligraphy (as a way)"),
    ],
    questions: [
      q(1, "你的文化喜欢喝茶吗？大多数人喜欢喝什么茶？怎么喝？", "Does your culture like tea? What tea do most people drink, and how?"),
      q(2, "你家喝茶吗？如果不喝，会喝什么饮料？如果喝，喝什么？怎么喝？", "Does your family drink tea? If not, what do you drink? If yes, what tea, and how?"),
      q(3, "你喜欢咖啡还是茶？", "Do you prefer coffee or tea?"),
      q(4, "你什么时候喝茶？茶里加什么？配茶点吗？", "When do you drink tea? What do you add? Do you have snacks with it?"),
      q(5, "贵国有传统的泡茶法或“茶道”吗？你会吗？", "Does your country have a traditional brewing method or tea ceremony? Can you do it?"),
      q(6, "你去过中国大陆或台湾的茶馆吗？喝过功（工）夫茶吗？", "Have you been to a teahouse in mainland China or Taiwan? Have you had gongfu tea?"),
      q(7, "你知道哪些茶的名字？喝过什么特别的茶？", "Which tea names do you know? What’s a special tea you’ve tried?"),
      q(8, "选择饮料时，你觉得好喝重要还是健康重要？", "When you pick a drink, is taste more important, or health?"),
      q(9, "你平时怎么选择饮料？（依考虑先后排序：口味、健康、价钱）", "How do you usually choose a drink? (Rank: flavor, health, price)"),
      q(10, "贵国会用茶招待客人吗？茶也是待客和送礼的一部分吗？", "Does your country host guests with tea? Is tea also for gifts?"),
      q(11, "你知道如何辨别好茶吗？举例说明贵国的好茶。", "Do you know how to tell good tea? Give an example from your country."),
      q(12, "你听说过台湾和中国的什么茶？你喝过吗？喜欢吗？", "What Taiwan or China teas have you heard of? Have you tried them? Did you like them?"),
      q(13, "你参加过茶会吗？参加过的话，请描述一个茶会。", "Have you been to a tea gathering? If yes, describe one."),
      q(14, "马黛茶是哪里的茶饮？你喝过吗？", "Where is yerba mate from? Have you tried it?"),
      q(15, "你喜欢喝什么样的咖啡？你会手冲咖啡吗？", "What kind of coffee do you like? Can you make pour-over?"),
      q(16, "你对咖啡或茶很讲究吗？", "Are you particular about coffee or tea?"),
      q(17, "喝茶和喝咖啡时你喜欢配什么样的点心？", "What snacks do you like with tea or coffee?"),
      q(18, "你听说过有关茶或者咖啡品牌的故事吗？", "Have you heard a story about a tea or coffee brand?"),
      q(19, "你觉得茶叶渣和咖啡渣可以做什么？", "What can you do with tea leaves and coffee grounds?"),
      q(20, "搜寻〔搜索〕日本人伊藤笃臣的台湾阿里山咖啡梦的故事，你的感想？", "Look up Atsuo Ito’s Alishan coffee-dream story. What’s your reaction?"),
      q(21, "比较各国的茶和咖啡文化，你喜欢什么样的？", "Compare tea and coffee cultures. Which style do you like?"),
      q(22, "星巴克为什么会成功？", "Why did Starbucks succeed?"),
      q(23, "蓝瓶咖啡（Blue Bottle Coffee）为什么会被称为咖啡界的 Apple？", "Why is Blue Bottle called the Apple of coffee?"),
      q(24, "你听说过麝香猫咖啡吗？你喝过吗？怎么样？没有的话想喝喝看吗？", "Have you heard of civet coffee? Have you tried it? If not, would you?"),
      q(25, "如果必须开一家咖啡店，你想开什么样的咖啡店？开在哪里？主打什么目标族群？", "If you had to open a café, what kind, where, and for whom?"),
    ],
  },
  {
    id: "5-4",
    unitId: 5,
    title: "摊贩夜市小吃",
    titleEn: "Street food and night markets",
    pageStart: 68,
    audioId: "5-4",
    scenario: {
      time: "逛夜市时",
      timeEn: "While visiting a night market",
      location: "夜市",
      locationEn: "A night market",
      participants: "和朋友",
      participantsEn: "With a friend",
      topic: "买小吃",
      topicEn: "Buying snacks",
    },
    dialogue: [
      notedLine(LESSON_5_4_LINE_NOTES, "A", "都 10 点半了还人山人海！", "It’s already 10:30 and still packed!"),
      notedLine(LESSON_5_4_LINE_NOTES, "B", "那里好多人在排队啊！排什么去看看！", "So many people queuing over there! Let’s see what it’s for!"),
      notedLine(LESSON_5_4_LINE_NOTES, "A", "鸡排，要排吗？", "Chicken cutlet — want to queue?"),
      notedLine(LESSON_5_4_LINE_NOTES, "B", "这么多人在排一定很好吃，当然要排！", "This many people in line — it must be good. Of course we queue!"),
      notedLine(
        LESSON_5_4_LINE_NOTES,
        "A",
        "你们女人就是好奇，对“排队的店”和“限定”毫无招架之力。要排很久啊！",
        "You women are just curious — powerless against shops with queues and limited editions. That’s a long wait!",
      ),
      notedLine(LESSON_5_4_LINE_NOTES, "B", "要不我排就好，你先去买别的。", "How about I queue, and you go buy something else first."),
      notedLine(LESSON_5_4_LINE_NOTES, "A", "那我先去买卤味。你要什么？", "Then I’ll go buy braised snacks first. What do you want?"),
      notedLine(LESSON_5_4_LINE_NOTES, "B", "当然是我的最爱——豆干！黑的黄的各一份。", "Of course my favorite — dried tofu! One black and one yellow."),
      notedLine(LESSON_5_4_LINE_NOTES, "A", "豆花要不要？", "Want tofu pudding?"),
      notedLine(LESSON_5_4_LINE_NOTES, "B", "不用，冬瓜茶一杯。", "No — one winter-melon tea."),
      notedLine(LESSON_5_4_LINE_NOTES, "A", "好，可能我买回来了还没轮到你。", "Okay. I’ll probably be back before it’s your turn."),
    ],
    notes: [{ hanzi: "毫无招架之力：完全没有办法抵抗诱惑。", en: "毫无招架之力 = no defense — used for queues, limited editions, and cravings." }],
    coreVocabulary: LESSON_5_4_CORE_VOCAB,
    chunks: LESSON_5_4_CHUNKS,
    expressionFamily: { title: "一套夜市小吃说法", titleEn: "One family of night-market expressions", items: LESSON_5_4_FAMILY },
    grammarFocus: LESSON_5_4_GRAMMAR_FOCUS,
    practiceSentences: LESSON_5_4_PRACTICE,
    fillBlanks: LESSON_5_4_FILL_BLANKS,
    vocabulary: [
      v("摊贩", "street vendor"),
      v("取缔", "to crack down on; to ban"),
      v("夜市", "night market"),
      v("小吃", "snack; street food"),
      v("逛", "to stroll; to browse"),
      v("税金", "tax"),
      v("排队", "to queue"),
      v("甜度", "sweetness level"),
      v("冰块", "ice cubes"),
      v("毫无招架之力", "no way to resist"),
      v("打弹珠", "to play pinball / marbles"),
      v("臭豆腐", "stinky tofu"),
      v("刨冰", "shaved ice"),
      v("路边摊", "roadside stall"),
    ],
    questions: [
      q(1, "什么是摊贩？", "What is a street vendor?"),
      q(2, "你住的城市有摊贩吗？", "Are there street vendors in the city you live in?"),
      q(3, "为什么人们要摆摊贩而不是开店卖东西？", "Why set up a stall instead of opening a shop?"),
      q(4, "在贵国可以在街上摆摊吗？", "Is street vending allowed in your country?"),
      q(5, "你买过街上摊贩的东西吗？", "Have you bought something from a street vendor?"),
      q(6, "你喜欢摊贩或夜市的小吃吗？", "Do you like street-vendor or night-market snacks?"),
      q(7, "摊贩小吃安全吗？", "Is street food safe?"),
      q(8, "你逛过夜市吗？去过夜市的话，你买了什么？", "Have you been to a night market? If yes, what did you buy?"),
      q(9, "如果你必须摆摊卖东西，你要在哪里卖什么？", "If you had to run a stall, where and what would you sell?"),
      q(10, "你觉得政府应该取缔摊贩吗？", "Should the government ban street vendors?"),
      q(11, "你到一个新的城市，如果有夜市，会想去逛逛吗？", "In a new city, if there’s a night market, would you go?"),
      q(12, "贵国有夜市吗？在哪里？", "Does your country have night markets? Where?"),
      q(13, "在陌生的地方看到很多人排队买路边小吃，你会想吃吃看吗？", "In an unfamiliar place, if lots of people queue for roadside snacks, would you try?"),
      q(14, "你觉得摊贩应该缴交税金吗？贵国的摊贩需要缴交税金吗？", "Should vendors pay tax? Do they in your country?"),
      q(15, "你知道中国哪些地方的什么小吃？", "What snacks from which places in China do you know?"),
      q(16, "你知道台湾哪些地方的什么小吃？", "What snacks from which places in Taiwan do you know?"),
      q(17, "你吃过什么小吃？想尝尝什么小吃？", "What snacks have you tried? What do you want to try?"),
      q(18, "你最晚曾经晚上几点去吃宵夜？", "What’s the latest you’ve gone out for a late-night snack?"),
      q(19, "饭店餐厅和摊贩小吃，你喜欢哪一个？", "Restaurant or street food — which do you prefer?"),
      q(20, "你敢吃菲律宾的毛蛋 (Balut) 吗？", "Do you dare eat Filipino balut?"),
      q(21, "你敢吃臭豆腐、香菜吗？", "Do you dare eat stinky tofu and cilantro?"),
      q(22, "你的老家有什么小吃？", "What snacks are there in your hometown?"),
      q(23, "如果得卖一种小吃，你想卖什么？", "If you had to sell one snack, what would it be?"),
      q(24, "你还吃过哪一国的小吃你觉得不错的？", "Which other country’s snacks have you tried and liked?"),
      q(25, "你喝过台湾的手摇饮吗？你喜欢喝什么？", "Have you had a Taiwan hand-shaken drink? What do you like?"),
      q(26, "体演：买珍珠奶茶。", "Role-play: buying pearl milk tea.", "roleplay"),
    ],
  },
  {
    id: "5-5",
    unitId: 5,
    title: "素食",
    titleEn: "Vegetarian food",
    pageStart: 70,
    audioId: "5-5",
    scenario: {
      time: "聚餐企划会议",
      timeEn: "A dinner-planning meeting",
      location: "办公室",
      locationEn: "The office",
      participants: "和同事",
      participantsEn: "With colleagues",
      topic: "因荤素食口角",
      topicEn: "A quarrel over meat vs vegetarian food",
    },
    dialogue: [
      notedLine(LESSON_5_5_LINE_NOTES, "A", "我们今天得交周年庆聚餐企划案。先选餐厅吧。", "We have to submit the anniversary-dinner plan today. Let’s pick a restaurant first."),
      notedLine(LESSON_5_5_LINE_NOTES, "B", "素食餐厅吧，不要杀生啦！", "A vegetarian restaurant — don’t take life!"),
      notedLine(LESSON_5_5_LINE_NOTES, "A", "每个人都有自己的饮食习惯，可以特别准备一桌素食。", "Everyone has their own eating habits. We can specially prepare one vegetarian table."),
      notedLine(LESSON_5_5_LINE_NOTES, "B", "你们吃的都是生命。", "What you eat is all life."),
      notedLine(LESSON_5_5_LINE_NOTES, "A", "你不知道植物受伤的时候也有反应吗？", "Don’t you know plants also react when they’re hurt?"),
      notedLine(LESSON_5_5_LINE_NOTES, "B", "你们吃的都是有灵魂的。", "What you eat all have souls."),
      notedLine(LESSON_5_5_LINE_NOTES, "A", "你知不知道你加的汽油是恐龙的生命换来的？", "Do you even know the gasoline you put in is bought with dinosaurs’ lives?"),
      notedLine(LESSON_5_5_LINE_NOTES, "B", "本来活得好好的动物为了人们的口腹之欲牺牲，好可怜！", "Animals that were living just fine are sacrificed for people’s appetite — so sad!"),
      notedLine(
        LESSON_5_5_LINE_NOTES,
        "A",
        "我们不反对你们吃素，但不要讲得像圣人一样，吃荤吃素没有贵贱之分，只是每个人的选择罢了。",
        "We don’t oppose you eating vegetarian, but don’t talk like a saint. Meat or vegetarian — there’s no high or low. It’s just each person’s choice.",
      ),
      notedLine(LESSON_5_5_LINE_NOTES, "B", "南无阿弥陀佛。", "Amitabha."),
    ],
    notes: [{ hanzi: "口腹之欲：只为了嘴巴和肚子的欲望。", en: "口腹之欲 is appetite as a moral charge — eating for pleasure." }],
    coreVocabulary: LESSON_5_5_CORE_VOCAB,
    chunks: LESSON_5_5_CHUNKS,
    expressionFamily: { title: "一套荤素说法", titleEn: "One family of meat-and-veg expressions", items: LESSON_5_5_FAMILY },
    grammarFocus: LESSON_5_5_GRAMMAR_FOCUS,
    practiceSentences: LESSON_5_5_PRACTICE,
    fillBlanks: LESSON_5_5_FILL_BLANKS,
    vocabulary: [
      v("素食者", "vegetarian"),
      v("纯素主义者", "vegan"),
      v("蛋素", "ovo-vegetarian"),
      v("奶素", "lacto-vegetarian"),
      v("奶蛋素", "lacto-ovo vegetarian"),
      v("植物五辛素", "vegetarian diet that includes the five pungent plants"),
      v("锅边素", "eating only the vegetables from a meat dish"),
      v("口腹之欲", "appetite; craving for food"),
      v("口角", "a quarrel"),
      v("佛教", "Buddhism"),
    ],
    questions: [
      q(1, "你吃素吗？（从什么时候开始的？）", "Are you vegetarian? (Since when?)"),
      q(2, "你知道哪位名人吃素或者认识任何吃素的人吗？", "Do you know a famous vegetarian, or anyone who eats vegetarian?"),
      q(3, "如果你不是素食者，你考虑过成为素食者吗？为什么？", "If you’re not vegetarian, have you thought about becoming one? Why?"),
      q(4, "你最久可以吃多久的素？", "What’s the longest you could eat vegetarian?"),
      q(5, "如果你必须成为素食者，你会最怀念什么荤食？", "If you had to become vegetarian, what meat dish would you miss most?"),
      q(6, "人们为什么吃素？", "Why do people eat vegetarian?"),
      q(7, "五辛是哪五种植物？为什么有些人不吃五辛？", "What are the five pungent plants? Why do some people avoid them?"),
      q(8, "锅边素或方便素是什么？你有吃锅边素的朋友吗？", "What is 锅边素 or convenience vegetarian? Do you have a friend who eats that way?"),
      q(9, "纯素主义者和其他素食者有什么区别？", "What’s the difference between vegans and other vegetarians?"),
      q(10, "鱼素和果素是什么？你认识吃这些素的人吗？", "What are pescatarian and fruitarian diets? Do you know anyone who eats that way?"),
      q(11, "如果你必须选择吃素，你想吃哪一种素？", "If you had to eat vegetarian, which kind would you choose?"),
      q(12, "你曾经因为饮食习惯不同而在生活上感到不便吗？", "Have different eating habits ever made daily life inconvenient?"),
      q(13, "你最喜欢的素食料理是什么？", "What’s your favorite vegetarian dish?"),
      q(14, "贵国有很多素食餐厅吗？你去过吗？感觉怎么样？", "Does your country have many vegetarian restaurants? Have you been? How were they?"),
      q(15, "少吃肉和环保有什么关联？", "What’s the link between eating less meat and the environment?"),
      q(16, "吃肉有没有吃素无法取代的好处？", "Does eating meat have benefits vegetarian food can’t replace?"),
      q(17, "你认为所有餐馆是否应该在菜单上提供一到两道素食菜肴？", "Should every restaurant offer one or two vegetarian dishes?"),
      q(18, "如果你的伴侣和你的饮食习惯截然不同，你还是会结婚吗？", "If your partner’s eating habits were totally different, would you still marry?"),
      q(19, "有些人坚决不打疫苗，说疫苗开发阶段利用了动物，你的看法？", "Some people refuse vaccines because animals were used in development. What’s your view?"),
      q(20, "杏鲍菇（或称蚝菇）会打猎捉昆虫，你觉得它是素的吗？", "King oyster mushrooms hunt insects. Do you still count them as vegetarian?"),
      q(21, "很多华人不吃牛肉，除了宗教因素还有什么原因？", "Many Chinese people don’t eat beef. Besides religion, why?"),
      q(22, "素食餐厅常把素食做成动物状，你觉得是因为他们想吃肉吗？", "Vegetarian restaurants often shape food like animals. Is that because they miss meat?"),
      q(23, "你会为来你家吃饭的素食者准备什么饭菜甜点？", "What meal and dessert would you cook for a vegetarian guest?"),
      q(24, "搜寻〔搜索〕网上的素食餐厅，你想去哪一家吃吃看？为什么？", "Look up vegetarian restaurants online. Which one would you try, and why?"),
      q(25, "你觉得成为素食者的最好理由是什么？健康原因还是动物权利？", "What’s the best reason to be vegetarian — health or animal rights?"),
      q(26, "哲学辩论：“素食是对的。”", "Philosophy debate: “Vegetarianism is right.”", "debate"),
    ],
  },
]

for (const lesson of UNIT_5) assertLessonReady(lesson)
