/**
 * RULE: every dialogue line is built with notedLine(LESSON_X_Y_LINE_NOTES, …).
 * Keys must match 汉字 exactly, including 〔盒饭〕 and Latin lines like Hmm.
 */
import {
  LESSON_2_1_CHUNKS,
  LESSON_2_1_CORE_VOCAB,
  LESSON_2_1_FAMILY,
  LESSON_2_1_FILL_BLANKS,
  LESSON_2_1_GRAMMAR_FOCUS,
  LESSON_2_1_LINE_NOTES,
  LESSON_2_1_PRACTICE,
} from "@/content/lessons/2-1-notes"
import {
  LESSON_2_2_CHUNKS,
  LESSON_2_2_CORE_VOCAB,
  LESSON_2_2_FAMILY,
  LESSON_2_2_FILL_BLANKS,
  LESSON_2_2_GRAMMAR_FOCUS,
  LESSON_2_2_LINE_NOTES,
  LESSON_2_2_PRACTICE,
} from "@/content/lessons/2-2-notes"
import {
  LESSON_2_3_CHUNKS,
  LESSON_2_3_CORE_VOCAB,
  LESSON_2_3_FAMILY,
  LESSON_2_3_FILL_BLANKS,
  LESSON_2_3_GRAMMAR_FOCUS,
  LESSON_2_3_LINE_NOTES,
  LESSON_2_3_PRACTICE,
} from "@/content/lessons/2-3-notes"
import {
  LESSON_2_4_CHUNKS,
  LESSON_2_4_CORE_VOCAB,
  LESSON_2_4_FAMILY,
  LESSON_2_4_FILL_BLANKS,
  LESSON_2_4_GRAMMAR_FOCUS,
  LESSON_2_4_LINE_NOTES,
  LESSON_2_4_PRACTICE,
} from "@/content/lessons/2-4-notes"
import {
  LESSON_2_5_CHUNKS,
  LESSON_2_5_CORE_VOCAB,
  LESSON_2_5_FAMILY,
  LESSON_2_5_FILL_BLANKS,
  LESSON_2_5_GRAMMAR_FOCUS,
  LESSON_2_5_LINE_NOTES,
  LESSON_2_5_PRACTICE,
} from "@/content/lessons/2-5-notes"
import {
  LESSON_2_6_CHUNKS,
  LESSON_2_6_CORE_VOCAB,
  LESSON_2_6_FAMILY,
  LESSON_2_6_FILL_BLANKS,
  LESSON_2_6_GRAMMAR_FOCUS,
  LESSON_2_6_LINE_NOTES,
  LESSON_2_6_PRACTICE,
} from "@/content/lessons/2-6-notes"
import { assertLessonReady, notedLine } from "@/content/lessons/note-helpers"
import type { Lesson, Question, VocabItem } from "@/lib/types"

function v(hanzi: string, en: string): VocabItem {
  return { hanzi, en }
}

function q(n: number, hanzi: string, en: string, kind?: Question["kind"]): Question {
  return kind ? { n, hanzi, en, kind } : { n, hanzi, en }
}

export const UNIT_2: Lesson[] = [
  {
    id: "2-1",
    unitId: 2,
    title: "老师同学",
    titleEn: "Teachers and classmates",
    pageStart: 24,
    audioId: "2-1",
    scenario: {
      time: "下课时间",
      timeEn: "After class",
      location: "大学教室",
      locationEn: "University classroom",
      participants: "和同学",
      participantsEn: "With a classmate",
      topic: "聊老师",
      topicEn: "Chatting about teachers",
    },
    dialogue: [
      notedLine(LESSON_2_1_LINE_NOTES, "A", "天啊，终于下课了，我都快睡着了！", "Oh my god, class is finally over — I was almost falling asleep!"),
      notedLine(LESSON_2_1_LINE_NOTES, "B", "真的！去年的老师有趣多了！", "Right? Last year’s teacher was much more interesting!"),
      notedLine(
        LESSON_2_1_LINE_NOTES,
        "A",
        "去年的不错，但是我遇到过最好的英语老师是高中时的，教得超好，而且很会鼓励学生，我想她影响了我的一生。",
        "Last year’s was fine, but the best English teacher I ever had was in high school. She taught extremely well and really knew how to encourage students. I think she influenced my whole life.",
      ),
      notedLine(LESSON_2_1_LINE_NOTES, "B", "怪不得你英语这么好。我都没遇到过好的英语老师。", "No wonder your English is so good. I’ve never had a good English teacher."),
      notedLine(LESSON_2_1_LINE_NOTES, "A", "你没有特别喜欢的老师吗？", "Isn’t there a teacher you especially like?"),
      notedLine(LESSON_2_1_LINE_NOTES, "B", "小学的班导吧，很温柔慈祥，像妈妈一样照顾学生。", "My elementary homeroom teacher, I guess. She was gentle and kindly, and looked after us like a mom."),
      notedLine(LESSON_2_1_LINE_NOTES, "A", "你以后想教书吗？", "Do you want to teach later on?"),
      notedLine(LESSON_2_1_LINE_NOTES, "B", "不想，现在的学生太难管了。你呢？", "No. Students nowadays are too hard to manage. How about you?"),
      notedLine(
        LESSON_2_1_LINE_NOTES,
        "A",
        "我一直都在当家教，明年想修教育学分，有机会的话想教中小学英语。",
        "I’ve been tutoring all along. Next year I want to take education credits. If I get the chance, I want to teach English in primary and secondary school.",
      ),
      notedLine(LESSON_2_1_LINE_NOTES, "B", "你以后一定会是个好老师！", "You’ll definitely be a good teacher someday!"),
    ],
    notes: [{ hanzi: "翘课：逃课、旷课。", en: "翘课 means to skip class; also 逃课 / 旷课." }],
    coreVocabulary: LESSON_2_1_CORE_VOCAB,
    chunks: LESSON_2_1_CHUNKS,
    expressionFamily: {
      title: "一套师生说法",
      titleEn: "One family of teacher–student expressions",
      items: LESSON_2_1_FAMILY,
    },
    grammarFocus: LESSON_2_1_GRAMMAR_FOCUS,
    practiceSentences: LESSON_2_1_PRACTICE,
    fillBlanks: LESSON_2_1_FILL_BLANKS,
    vocabulary: [
      v("家教", "private tutor; tutoring"),
      v("年纪", "age (of a person)"),
      v("科目", "school subject"),
      v("特质", "quality; trait"),
      v("翘课", "to skip class"),
      v("值日生", "student on duty"),
      v("模范生", "model student"),
      v("班导", "homeroom teacher"),
      v("友谊", "friendship"),
      v("温柔", "gentle"),
      v("慈祥", "kindly; benevolent"),
      v("至圣先师", "the Greatest Sage and First Teacher (Confucius)"),
      v("监考", "to proctor an exam"),
      v("找家长", "to call a student’s parents in"),
      v("校长", "principal"),
    ],
    questions: [
      q(1, "你最喜欢的老师是谁？为什么？（分别谈谈小学、中学、高中、大学时代）", "Who is your favorite teacher? Why? (Talk about elementary, middle, high school, and university separately.)"),
      q(2, "你曾遇到不好的老师吗？为什么不好？", "Have you ever had a bad teacher? Why were they bad?"),
      q(3, "有老师影响你的一生吗？", "Has a teacher influenced your life?"),
      q(4, "贵国老师的退休年龄是几岁？", "What is the retirement age for teachers in your country?"),
      q(5, "你喜欢年轻的老师还是上年纪的老师？", "Do you prefer young teachers or older teachers?"),
      q(6, "如果你要当老师，你想当什么科的老师？", "If you were going to be a teacher, what subject would you want to teach?"),
      q(7, "如果你得当老师，你要教什么年纪的学生？", "If you had to be a teacher, what age students would you teach?"),
      q(8, "如果有一位同学在考试时问你答案，而监考老师不在，你会怎么做？", "If a classmate asked you for the answer during an exam and the proctor wasn’t there, what would you do?"),
      q(9, "小老师是什么？你曾经当过小老师吗？", "What is a “little teacher”? Have you ever been one?"),
      q(10, "你做过家教吗？", "Have you ever been a tutor?"),
      q(11, "当老师要有什么特质？你对好老师的定义？", "What qualities does a teacher need? What’s your definition of a good teacher?"),
      q(12, "贵国有尊师重道的文化吗？", "Does your country have a culture of respecting teachers?"),
      q(13, "你对好学生／模范生的定义？", "What’s your definition of a good student / model student?"),
      q(14, "你是好学生／模范生吗？", "Are you a good student / model student?"),
      q(15, "你觉得什么样的学生是坏学生？", "What kind of student do you think is a bad student?"),
      q(16, "学生时代你有几个非常要好的朋友？你们会一起做什么？", "In your school years, how many close friends did you have? What did you do together?"),
      q(17, "你喜欢上学吗？你翘过课吗？", "Do you like going to school? Have you ever skipped class?"),
      q(18, "你喜欢跟用功的同学一起还是跟爱玩的同学一起？", "Do you prefer being with hardworking classmates or classmates who like to play?"),
      q(19, "什么是值日生？你们学校有没有值日生？", "What is a student on duty? Did your school have students on duty?"),
      q(20, "你曾经被“找家长”吗？", "Have you ever had the school call your parents?"),
      q(21, "描述你最要好的同学。", "Describe your closest classmate."),
      q(22, "如果你可以上任何人的一堂课，你想请谁来教室讲哪方面的课？", "If you could take a class from anyone, who would you invite, and what would they teach?"),
      q(23, "孔子为什么是至圣先师？你想当孔子的学生吗？", "Why is Confucius called the Greatest Sage and First Teacher? Would you want to be his student?"),
      q(24, "如果你可以和古今中外任何一个人一起学习，你想要谁当你同学？为什么？", "If you could study with anyone from any time or place, who would you want as your classmate? Why?"),
    ],
  },
  {
    id: "2-2",
    unitId: 2,
    title: "作业",
    titleEn: "Homework",
    pageStart: 26,
    audioId: "2-2",
    scenario: {
      time: "下午5点半",
      timeEn: "5:30 p.m.",
      location: "家里小孩房间",
      locationEn: "The child’s room at home",
      participants: "妈妈和小一的小孩",
      participantsEn: "Mom and a first-grader",
      topic: "妈妈问小孩作业完成状况",
      topicEn: "Mom asks whether the homework is done",
    },
    dialogue: [
      notedLine(LESSON_2_2_LINE_NOTES, "A", "学校作业写完了吗？", "Have you finished your school homework?"),
      notedLine(LESSON_2_2_LINE_NOTES, "B", "写完了。", "I finished it."),
      notedLine(LESSON_2_2_LINE_NOTES, "A", "我看。这里怎么这么脏？擦干净一点重写。", "Let me see. Why is it so messy here? Erase it cleaner and rewrite it."),
      notedLine(LESSON_2_2_LINE_NOTES, "B", "Hmm", "Hmm."),
      notedLine(LESSON_2_2_LINE_NOTES, "A", "安亲班有作业吗？", "Does after-school care have homework?"),
      notedLine(LESSON_2_2_LINE_NOTES, "B", "没有。", "No."),
      notedLine(LESSON_2_2_LINE_NOTES, "A", "那做这个参考书，从这里到第30页。", "Then do this workbook, from here to page 30."),
      notedLine(LESSON_2_2_LINE_NOTES, "B", "哪有这样子的！你说做完学校作业就可以玩游戏的！", "That’s not fair! You said I could play games after I finished school homework!"),
      notedLine(LESSON_2_2_LINE_NOTES, "A", "要月考了，加油一点！", "Monthly exams are coming — work a bit harder!"),
      notedLine(LESSON_2_2_LINE_NOTES, "B", "（小声嘀咕）说话不算话！", "(Muttering) You don’t keep your word!"),
    ],
    coreVocabulary: LESSON_2_2_CORE_VOCAB,
    chunks: LESSON_2_2_CHUNKS,
    expressionFamily: {
      title: "一套作业说法",
      titleEn: "One family of homework expressions",
      items: LESSON_2_2_FAMILY,
    },
    grammarFocus: LESSON_2_2_GRAMMAR_FOCUS,
    practiceSentences: LESSON_2_2_PRACTICE,
    fillBlanks: LESSON_2_2_FILL_BLANKS,
    vocabulary: [
      v("留作业", "to assign homework"),
      v("写作业", "to do written homework"),
      v("做作业", "to do homework"),
      v("补习班", "cram school"),
      v("安亲班", "after-school care"),
      v("心算", "mental arithmetic"),
      v("写作", "writing; composition"),
      v("辅导课", "remedial / tutoring class"),
      v("考试", "exam"),
      v("模拟考", "mock exam"),
      v("考卷", "exam paper"),
      v("及格", "to pass (a test)"),
      v("报告", "report"),
      v("磨磨蹭蹭", "to dawdle"),
    ],
    questions: [
      q(1, "为什么要有家庭作业？", "Why should there be homework?"),
      q(2, "你在学生时代通常做什么样的家庭作业？", "What kind of homework did you usually do as a student?"),
      q(3, "除了学校的功课，父母或其他人会给你功课吗？", "Besides schoolwork, do parents or others give you assignments?"),
      q(4, "你通常在哪里完成作业？安亲班、补习班，还是家里？", "Where do you usually finish homework? After-school care, cram school, or at home?"),
      q(5, "你喜欢做功课吗？你通常会主动做功课吗？", "Do you like doing schoolwork? Do you usually start it on your own?"),
      q(6, "你什么时候做作业？", "When do you do homework?"),
      q(7, "你有自己的学习空间吗？你的书桌上有什么？", "Do you have your own study space? What is on your desk?"),
      q(8, "你帮别人做过作业吗？你抄过别人的作业吗？", "Have you ever done homework for someone else? Have you ever copied someone else’s?"),
      q(9, "你在学习时会听音乐或吃东西吗？", "Do you listen to music or eat while studying?"),
      q(10, "论文期限到了但是你还没完成，网上有代写的，一行1元，你会不会利用？", "The paper is due and you haven’t finished. Online ghostwriting is 1 yuan a line. Would you use it?"),
      q(11, "你习惯一次完成所有作业还是拖到最后才做？", "Do you usually finish all homework at once, or put it off until the last minute?"),
      q(12, "你觉得寒暑假应该要有作业吗？为什么？", "Should there be homework over winter and summer vacation? Why?"),
      q(13, "没写作业时，你用过什么借口？你曾听过有趣的借口吗？（如：本子被狗吃了／被风吹了……）", "What excuses have you used for not doing homework? Heard any funny ones?"),
      q(14, "你常觉得你有太多的功课吗？", "Do you often feel you have too much schoolwork?"),
      q(15, "你喜欢和朋友一起做作业吗？", "Do you like doing homework with friends?"),
      q(16, "你喜欢在哪里学习？自己的房间？自习室？图书馆？咖啡馆？速食店〔快餐店〕？朋友家？", "Where do you like to study? Your room, a study hall, library, café, fast-food place, or a friend’s?"),
      q(17, "你做过有趣或印象深刻的家庭作业吗？", "Have you ever done interesting or memorable homework?"),
      q(18, "你喜欢和讨厌什么科的作业？为什么？", "Which subjects’ homework do you like and dislike? Why?"),
      q(19, "如果你是老师，你想给学生留什么样的作业？（可以分科举例，或选一科自己喜欢的学科举例）", "If you were a teacher, what homework would you assign?"),
      q(20, "你觉得华语老师应该留什么样的作业给学生？", "What homework should a Chinese teacher assign?"),
      q(21, "小孩不想做作业，你怎么办？", "If a child doesn’t want to do homework, what do you do?"),
      q(22, "小时候除了上学以外，你玩什么？", "Besides school, what did you play when you were little?"),
      q(23, "辩论：作业应该在学校做完，回家不该有作业。", "Debate: Homework should be finished at school; there should be none at home.", "debate"),
    ],
  },
  {
    id: "2-3",
    unitId: 2,
    title: "课外活动",
    titleEn: "Extracurriculars",
    pageStart: 28,
    audioId: "2-3",
    scenario: {
      time: "下午6点",
      timeEn: "6:00 p.m.",
      location: "家门口",
      locationEn: "At the doorway",
      participants: "和小孩同学的妈妈",
      participantsEn: "With a classmate’s mom",
      topic: "聊小孩的才艺班",
      topicEn: "Chatting about the child’s talent classes",
    },
    dialogue: [
      notedLine(LESSON_2_3_LINE_NOTES, "A", "安安妈妈！出去啊？", "An’an’s mom! Heading out?"),
      notedLine(LESSON_2_3_LINE_NOTES, "B", "去接小孩。", "Going to pick up my kid."),
      notedLine(LESSON_2_3_LINE_NOTES, "A", "安亲班吗？", "After-school care?"),
      notedLine(LESSON_2_3_LINE_NOTES, "B", "不是，我最近给他报了才艺班。", "No — I recently signed him up for talent classes."),
      notedLine(LESSON_2_3_LINE_NOTES, "A", "才艺班？学什么？", "Talent classes? What’s he studying?"),
      notedLine(LESSON_2_3_LINE_NOTES, "B", "一周三天，上英语、创作思考和围棋。", "Three days a week: English, creative thinking, and Go."),
      notedLine(LESSON_2_3_LINE_NOTES, "A", "这么多！创作思考是什么课？", "So many! What kind of class is creative thinking?"),
      notedLine(LESSON_2_3_LINE_NOTES, "B", "说是儿童哲学，每周给一个主题讨论后画图或创作。", "They say it’s philosophy for children — each week they get a theme, discuss it, then draw or make something."),
      notedLine(LESSON_2_3_LINE_NOTES, "A", "听起来很有意思，我再跟你请教，你先去忙吧。", "That sounds really interesting. I’ll ask you more later — you go ahead."),
      notedLine(LESSON_2_3_LINE_NOTES, "B", "好，Bye Bye!", "Okay, bye-bye!"),
    ],
    coreVocabulary: LESSON_2_3_CORE_VOCAB,
    chunks: LESSON_2_3_CHUNKS,
    expressionFamily: {
      title: "一套才艺班说法",
      titleEn: "One family of extracurricular expressions",
      items: LESSON_2_3_FAMILY,
    },
    grammarFocus: LESSON_2_3_GRAMMAR_FOCUS,
    practiceSentences: LESSON_2_3_PRACTICE,
    fillBlanks: LESSON_2_3_FILL_BLANKS,
    vocabulary: [
      v("课外活动", "extracurricular activities"),
      v("围棋", "Go"),
      v("重返儿时", "return to childhood"),
      v("多元", "diverse; multifaceted"),
      v("钥匙儿", "latchkey kid"),
      v("接送", "pick up and drop off"),
      v("唠叨", "to nag"),
      v("辩论", "debate"),
      v("冥想", "meditation"),
      v("升学", "advance to a higher school"),
      v("学费", "tuition"),
      v("哲学", "philosophy"),
      v("才艺班", "talent / enrichment class"),
    ],
    questions: [
      q(1, "下课后你通常会做什么？立刻回家吗？", "What do you usually do after class? Do you go home right away?"),
      q(2, "学生时代你参加过什么社团？你每星期花多少时间在社团活动上？", "What clubs did you join as a student? How much time each week?"),
      q(3, "你喜欢什么课外活动？", "What extracurricular activities do you like?"),
      q(4, "什么是补习班？贵国有补习班吗？", "What is a cram school? Are there cram schools in your country?"),
      q(5, "你上过补习班吗？补什么？", "Have you attended a cram school? What did you study?"),
      q(6, "你喜欢补习班吗？", "Do you like cram school?"),
      q(7, "为什么亚洲有这么多补习班？", "Why are there so many cram schools in Asia?"),
      q(8, "什么是才艺班？贵国有才艺班吗？", "What are talent classes? Does your country have them?"),
      q(9, "你上过什么才艺班？你喜欢吗？", "What talent classes have you taken? Did you like them?"),
      q(10, "你参加过或想参加什么夏令营和冬令营？", "What summer or winter camps have you joined, or would you like to?"),
      q(11, "如果可以重返儿时，你希望你父母给你学什么才艺？", "If you could return to childhood, what talent would you want your parents to have you learn?"),
      q(12, "什么是安亲班？贵国有安亲班或托管班吗？", "What is after-school care? Does your country have it?"),
      q(13, "什么是钥匙儿童？你曾经是钥匙儿童吗？", "What is a latchkey child? Were you ever one?"),
      q(14, "贵国的父母需要接送小孩上下学吗？（需要的话大概接送到多大？）", "Do parents in your country drop off and pick up children? Until what age?"),
      q(15, "现在大学入试都要求看课外活动的表现，你觉得这是增加学生压力还是鼓励学生多元发展？", "University admissions now look at extracurriculars. Does that add pressure, or encourage diverse development?"),
      q(16, "你觉得学校应该规定每个学生都至少要参加一个社团吗？为什么？", "Should schools require every student to join at least one club? Why?"),
      q(17, "社团活动与上课时间冲突时，你怎么办？", "What do you do when club activities conflict with class?"),
      q(18, "学生时代你喜欢远足和参观吗？你印象最深的是去哪里？", "As a student, did you like hikes and field trips? Which place left the deepest impression?"),
      q(19, "学生时代你平均每周花多长时间在课外活动上？", "On average, how much time per week did you spend on extracurriculars?"),
      q(20, "你的小孩每天打球4小时，回家就吃饭睡觉不自主学习，你会唠叨吗？", "If your child played ball four hours a day and only ate and slept at home, would you nag?"),
      q(21, "社团六选一：辩论社、冥想社、茶道社、拉拉队、点心制作、诗词社。", "Pick one of six clubs: debate, meditation, tea ceremony, cheerleading, snack-making, poetry."),
      q(22, "如果可以自创一个学校社团，你想要什么社团？", "If you could start a school club, what would it be?"),
      q(23, "你曾经因为某项课外活动而得到了特殊的奖项或认可吗？", "Have you ever received a special award or recognition for an extracurricular?"),
      q(24, "你认为参加课外活动对你的学习和生活有什么好处？", "What benefits do extracurriculars have for study and life?"),
    ],
  },
  {
    id: "2-4",
    unitId: 2,
    title: "上学",
    titleEn: "Going to school",
    pageStart: 30,
    audioId: "2-4",
    scenario: {
      time: "周末晚餐后",
      timeEn: "After dinner on the weekend",
      location: "家里客厅",
      locationEn: "Living room at home",
      participants: "夫妻",
      participantsEn: "Husband and wife",
      topic: "谈选学校",
      topicEn: "Talking about choosing a school",
    },
    dialogue: [
      notedLine(LESSON_2_4_LINE_NOTES, "A", "老公，我想给儿子念国际学校。", "Honey, I want our son to go to an international school."),
      notedLine(LESSON_2_4_LINE_NOTES, "B", "那不是私立的吗？公立的不好吗？", "Isn’t that a private school? Are public schools no good?"),
      notedLine(
        LESSON_2_4_LINE_NOTES,
        "A",
        "附近的太太们都说这个学区不太好，很多人早就迁户口了，或者送小孩念私立的。",
        "The wives nearby all say this school district isn’t very good. A lot of people moved their household registration long ago, or send their kids private.",
      ),
      notedLine(LESSON_2_4_LINE_NOTES, "B", "会念的就会念，不会念的就不会念，送到哪都一样。", "Kids who can study will study, and kids who can’t, won’t — it’s the same wherever you send them."),
      notedLine(LESSON_2_4_LINE_NOTES, "A", "你看过《夏山学校》那本书吗？光阳学校就像那样。", "Have you read Summerhill School? Guangyang School is just like that."),
      notedLine(LESSON_2_4_LINE_NOTES, "B", "那是贵族小孩念的，学费几十万吧？", "That’s for rich kids. The tuition is a few hundred thousand, right?"),
      notedLine(LESSON_2_4_LINE_NOTES, "A", "我们两个人都在工作，我算了一下，勉强可以。", "Both of us are working. I did the math — we can just about afford it."),
      notedLine(
        LESSON_2_4_LINE_NOTES,
        "B",
        "为什么我们要过得这么勉强？公立学校还是可以学得很好的，我都是念公立，不也国立大学毕业？",
        "Why do we have to live so tightly? You can still learn very well at a public school. I went public the whole way and still graduated from a national university, didn’t I?",
      ),
      notedLine(
        LESSON_2_4_LINE_NOTES,
        "A",
        "现在这个时代，念公立的还要另外补习，私立的不用，一路升到大学，算起来差不了多少啦。",
        "These days, public school still means extra tutoring. Private schools don’t — you go straight through to university. All told it doesn’t come out that different.",
      ),
      notedLine(LESSON_2_4_LINE_NOTES, "B", "哎，你们这群教育妈妈！你去要资料来，再研究研究吧。", "Ai, you education moms! Go get the materials and we’ll look into it some more."),
    ],
    coreVocabulary: LESSON_2_4_CORE_VOCAB,
    chunks: LESSON_2_4_CHUNKS,
    expressionFamily: {
      title: "一套选校说法",
      titleEn: "One family of school-choice expressions",
      items: LESSON_2_4_FAMILY,
    },
    grammarFocus: LESSON_2_4_GRAMMAR_FOCUS,
    practiceSentences: LESSON_2_4_PRACTICE,
    fillBlanks: LESSON_2_4_FILL_BLANKS,
    vocabulary: [
      v("回忆", "memories"),
      v("学科", "school subject"),
      v("公立", "public (school)"),
      v("私立", "private (school)"),
      v("学区", "school district"),
      v("学费", "tuition"),
      v("距离", "distance"),
      v("实用", "practical"),
      v("用不上", "of no use"),
      v("迁户口", "move one’s household registration"),
      v("恶作剧", "prank"),
      v("霸凌", "bullying"),
      v("欺负", "to pick on"),
      v("勉强", "barely; with difficulty"),
      v("成绩", "grades"),
      v("进步", "progress"),
    ],
    questions: [
      q(1, "你最喜欢和最讨厌的科目是什么？", "What are your favorite and least favorite subjects?"),
      q(2, "简单介绍贵国的义务教育。（有学区制吗？要读几年？）", "Briefly introduce compulsory education in your country. Is there a district system? How many years?"),
      q(3, "学生时代你曾经恶作剧或被别人恶作剧吗？", "Did you ever play a prank or have one played on you?"),
      q(4, "举例说明学校的课表。", "Give an example of a school timetable."),
      q(5, "小学应该教电脑〔计算机〕程式〔程序〕语言吗？", "Should elementary schools teach computer programming languages?"),
      q(6, "你觉得开玩笑、欺负、霸凌有什么不同？你可以容忍恶作剧到什么程度？（请举例）", "What’s the difference between joking, picking on someone, and bullying? How far can you tolerate pranks?"),
      q(7, "你读过的学校有没有霸凌问题？", "Did the schools you attended have a bullying problem?"),
      q(8, "你的小孩如果被同学霸凌，你会怎么做？", "If your child were bullied, what would you do?"),
      q(9, "孩子如果遇到网路〔网络〕霸凌该怎么办？", "What should be done if a child encounters cyberbullying?"),
      q(10, "你或你朋友遇过言语霸凌的问题吗？", "Have you or your friends run into verbal bullying?"),
      q(11, "贵国学校的霸凌问题严重吗？", "Is bullying in schools a serious problem in your country?"),
      q(12, "如果你是校长，你想办什么样的学校？", "If you were a principal, what kind of school would you run?"),
      q(13, "你最怀念的学生时代是小学、中学〔初中〕、高中，还是大学？", "Which part of your student years do you miss most?"),
      q(14, "你觉得住学校宿舍怎么样？你上过寄宿学校吗？", "What do you think of living in a dorm? Have you gone to boarding school?"),
      q(15, "男女同校的优缺点？", "Advantages and disadvantages of co-ed schools?"),
      q(16, "私立学校和公立学校的优缺点？", "Advantages and disadvantages of private and public schools?"),
      q(17, "现在贵国最严重的教育问题是？", "What is the most serious education problem in your country right now?"),
      q(18, "如果不用考虑学费，你想读私立学校吗？你想让小孩读私立学校吗？", "If tuition were not a concern, would you or your child go private?"),
      q(19, "有人说学校学的科目不实用，日常生活大多用不上，你的看法？", "Some people say school subjects are not practical. What’s your view?"),
      q(20, "学校给你的回忆是好的多还是坏的多？", "Are your memories of school mostly good or mostly bad?"),
      q(21, "你喜欢上实体课还是网课？为什么？", "Do you prefer in-person classes or online classes? Why?"),
      q(22, "为什么有家长会为了学区买学区房迁户口？", "Why do some parents buy school-district housing and move their household registration?"),
      q(23, "你看过《夏山学校》或是听说过“森林小学”吗？你觉得怎么样？", "Have you read Summerhill School or heard of forest primary schools? What do you think?"),
      q(24, "贵国重视职业教育吗？请简单介绍贵国的职业教育体系。", "Does your country value vocational education? Briefly introduce the system."),
      q(25, "你对未来的教育有什么想法？", "What thoughts do you have about the future of education?"),
      q(26, "延伸活动：设计小学的一周课表。", "Extension: design a weekly elementary-school timetable."),
    ],
  },
  {
    id: "2-5",
    unitId: 2,
    title: "便当〔盒饭〕和营养午餐",
    titleEn: "Bento and school lunch",
    pageStart: 32,
    audioId: "2-5",
    scenario: {
      time: "午餐时间",
      timeEn: "Lunchtime",
      location: "公司休息室",
      locationEn: "Company break room",
      participants: "和同事",
      participantsEn: "With a colleague",
      topic: "聊便当〔盒饭〕",
      topicEn: "Chatting about bento",
    },
    dialogue: [
      notedLine(LESSON_2_5_LINE_NOTES, "A", "吃饭了，你今天带便当〔盒饭〕啊？", "Time to eat — you brought a bento today?"),
      notedLine(LESSON_2_5_LINE_NOTES, "B", "嗯，昨天卤了一锅红烧肉。", "Yeah, I braised a pot of red-cooked pork yesterday."),
      notedLine(LESSON_2_5_LINE_NOTES, "A", "看起来好好吃哦！你还配色！像日本的五色便当〔盒饭〕一样！", "It looks so good! You even color-coordinated it, like a Japanese five-color bento!"),
      notedLine(LESSON_2_5_LINE_NOTES, "B", "难得做便当〔盒饭〕啦，我可没时间每天这样搞。", "It’s rare for me to make a bento — I really don’t have time to do this every day."),
      notedLine(
        LESSON_2_5_LINE_NOTES,
        "A",
        "我在网上看过卡通图案便当〔盒饭〕，每次都想那要花多久时间做啊，好夸张！",
        "I’ve seen cartoon-pattern bentos online. Every time I wonder how long they take — so over the top!",
      ),
      notedLine(LESSON_2_5_LINE_NOTES, "B", "专职家庭主妇才有办法吧。公司像小学一样有营养午餐就好了。", "Probably only a full-time housewife could manage that. It would be great if the company had school-style lunches."),
      notedLine(
        LESSON_2_5_LINE_NOTES,
        "A",
        "你喜欢小学的营养午餐？我比较喜欢我妈做的便当〔盒饭〕。我受不了营养午餐配牛奶，无法理解为什么吃饭要配牛奶。",
        "You liked elementary-school lunch? I preferred the bento my mom made. I couldn’t stand lunch paired with milk — I don’t get why a meal has to come with milk.",
      ),
      notedLine(LESSON_2_5_LINE_NOTES, "B", "大概是怕我们营养不良，要补充钙质吧。", "Probably because they were afraid we’d be malnourished and wanted us to get calcium."),
      notedLine(LESSON_2_5_LINE_NOTES, "A", "听说牛奶喝得最多的国家，罹患骨质疏松症的比例反而较高呢！", "I heard that in the countries where people drink the most milk, the osteoporosis rate is actually higher!"),
      notedLine(LESSON_2_5_LINE_NOTES, "B", "还好我现在都喝豆浆。", "Good thing I drink soy milk now."),
    ],
    coreVocabulary: LESSON_2_5_CORE_VOCAB,
    chunks: LESSON_2_5_CHUNKS,
    expressionFamily: {
      title: "一套便当说法",
      titleEn: "One family of lunchbox expressions",
      items: LESSON_2_5_FAMILY,
    },
    grammarFocus: LESSON_2_5_GRAMMAR_FOCUS,
    practiceSentences: LESSON_2_5_PRACTICE,
    fillBlanks: LESSON_2_5_FILL_BLANKS,
    vocabulary: [
      v("便当", "bento; boxed lunch"),
      v("盒饭", "boxed lunch (Mainland)"),
      v("营养午餐", "school / nutritious lunch"),
      v("菜色", "dishes; menu items"),
      v("夸张", "exaggerated; over the top"),
      v("强制推行", "to force through; implement mandatorily"),
      v("自带", "to bring one’s own"),
      v("特殊造型", "special shapes; food art"),
      v("赏心悦目", "pleasing to the eye"),
      v("营养不良", "malnutrition"),
      v("营养均衡", "balanced nutrition"),
      v("兼顾", "to take both into account"),
      v("偏食", "to be a picky eater"),
    ],
    questions: [
      q(1, "你知道便当〔盒饭〕一词的由来吗？你带过便当〔盒饭〕吗？", "Do you know the origin of 便当? Have you ever brought a bento?"),
      q(2, "你买过便当〔盒饭〕吗？多久买一次？", "Have you bought a boxed lunch? How often?"),
      q(3, "你觉得开放学生中午外出购买午餐好吗？", "Is it good to let students go out and buy lunch at noon?"),
      q(4, "你吃过或看过其他国家的便当〔盒饭〕吗？和贵国的餐盒有什么不同？", "Have you eaten or seen bentos from other countries? How do they differ?"),
      q(5, "搜寻〔搜索〕世界各地上班族的午餐，你喜欢哪一国的？为什么？", "Look up office-worker lunches around the world. Which country’s do you like?"),
      q(6, "你是学生时，午餐是吃自己带的便当〔盒饭〕还是学校的营养午餐？你喜欢哪一个？为什么？", "As a student, did you bring a bento or eat school lunch? Which did you prefer?"),
      q(7, "贵国学校的营养午餐是免费的吗？", "Are school lunches in your country free?"),
      q(8, "请举例说明学校营养午餐的菜色。（你喜欢和不喜欢的）", "Give examples of school-lunch dishes you liked and disliked."),
      q(9, "贵国的便当〔盒饭〕大多是吃冷的还是热的？你知道日本人为什么大多吃冷的便当〔盒饭〕吗？", "Are boxed lunches in your country mostly cold or hot? Why do Japanese people often eat them cold?"),
      q(10, "日本人的便当〔盒饭〕以赏心悦目闻名，因为多有“五种颜色”，你知道什么是五色便当〔盒饭〕吗？", "Japanese bentos are known for looking beautiful, often with five colors. What is a five-color bento?"),
      q(11, "你看过卡通图案或特殊造型的便当〔盒饭〕吗？", "Have you seen cartoon-pattern or shaped bentos?"),
      q(12, "你觉得应该强制推行学校营养午餐吗？（每个学生都必须吃学校的，不可以自带），为什么？", "Should school lunch be mandatory, with no homemade boxes? Why?"),
      q(13, "你家的便当〔盒饭〕大多是什么时候做的？谁做？", "When is your family’s bento usually made, and by whom?"),
      q(14, "贵国有没有家长亲送便当〔盒饭〕的？你的看法？", "Do parents in your country personally deliver lunchboxes? What’s your view?"),
      q(15, "如果可以立刻吃到，你想吃哪一国的什么样的便当〔盒饭〕？", "If you could eat it right now, what boxed lunch from which country?"),
      q(16, "便当〔盒饭〕中有没有什么菜色是你讨厌的？", "Are there dishes in a bento that you dislike?"),
      q(17, "贵国有火车便当〔盒饭〕吗？什么样的？", "Does your country have train bentos? What are they like?"),
      q(18, "你觉得学校午餐营养和好吃能兼顾吗？", "Can school lunch be both nutritious and tasty?"),
      q(19, "你担心便当〔盒饭〕或营养午餐中添加物的问题吗？", "Do you worry about additives in boxed or school lunches?"),
      q(20, "贵国学校有合作社或贩卖部吗？卖什么？有什么样的食物？", "Do schools in your country have a co-op or snack shop? What do they sell?"),
      q(21, "你们公司提供午餐或便当吗？你喜欢自带还是吃公司的？", "Does your company provide lunch? Do you prefer bringing your own?"),
      q(22, "辩论：学校应该禁止贩卖或携带高热量零食。", "Debate: Schools should ban selling or bringing high-calorie snacks.", "debate"),
    ],
  },
  {
    id: "2-6",
    unitId: 2,
    title: "外语学习",
    titleEn: "Learning a foreign language",
    pageStart: 34,
    audioId: "2-6",
    scenario: {
      time: "周日晚上9点",
      timeEn: "Sunday evening at 9 p.m.",
      location: "网上即时通讯",
      locationEn: "Online chat",
      participants: "和法国网友",
      participantsEn: "With a French online friend",
      topic: "询问语言交换",
      topicEn: "Asking about a language exchange",
    },
    dialogue: [
      notedLine(LESSON_2_6_LINE_NOTES, "A", "你好，我是法国人，想学中文，可以跟你语言交换吗？", "Hello, I’m French and want to learn Chinese. Can I do a language exchange with you?"),
      notedLine(LESSON_2_6_LINE_NOTES, "B", "你好，可以。我刚通过A2，你的中文程度怎么样？", "Hello, yes. I just passed A2. What’s your Chinese level like?"),
      notedLine(LESSON_2_6_LINE_NOTES, "A", "我没考过，大概中级水平。", "I haven’t taken any exams; it’s roughly intermediate."),
      notedLine(LESSON_2_6_LINE_NOTES, "B", "你在哪学的中文呢？", "Where did you learn Chinese?"),
      notedLine(LESSON_2_6_LINE_NOTES, "A", "大学时第二外语，很久没用，退步了。你呢？你的法语在哪学的？", "It was my second foreign language in university. I haven’t used it in a long time, so I’ve slipped. How about you? Where did you learn French?"),
      notedLine(LESSON_2_6_LINE_NOTES, "B", "我自学的，没有语伴，说得不好。", "I’m self-taught. I don’t have a language partner, so I don’t speak well."),
      notedLine(LESSON_2_6_LINE_NOTES, "A", "自学？好棒！那我们一星期一次，一人30分钟怎么样？", "Self-taught? That’s great! How about once a week, 30 minutes each?"),
      notedLine(LESSON_2_6_LINE_NOTES, "B", "45分钟也可以，30分钟好短。", "45 minutes is also fine; 30 minutes is pretty short."),
      notedLine(LESSON_2_6_LINE_NOTES, "A", "好啊，我周末比较有空。", "Sure — I’m relatively free on weekends."),
      notedLine(LESSON_2_6_LINE_NOTES, "B", "那就每周日的这个时间吧！", "Then let’s make it this time every Sunday!"),
    ],
    coreVocabulary: LESSON_2_6_CORE_VOCAB,
    chunks: LESSON_2_6_CHUNKS,
    expressionFamily: {
      title: "一套外语学习说法",
      titleEn: "One family of language-learning expressions",
      items: LESSON_2_6_FAMILY,
    },
    grammarFocus: LESSON_2_6_GRAMMAR_FOCUS,
    practiceSentences: LESSON_2_6_PRACTICE,
    fillBlanks: LESSON_2_6_FILL_BLANKS,
    vocabulary: [
      v("外语", "foreign language"),
      v("提高", "to improve"),
      v("水平", "level; proficiency"),
      v("翻译", "to translate; translation"),
      v("腔调", "accent; intonation"),
      v("精通", "to be proficient in"),
      v("留学", "to study abroad"),
      v("选修", "to take as an elective"),
      v("第二外语", "second foreign language"),
      v("寄宿家庭", "host family"),
      v("修课", "to take a course"),
      v("学分", "credit (academic)"),
      v("听说读写译", "listening, speaking, reading, writing, and translating"),
    ],
    questions: [
      q(1, "你会几种语言？你会说方言吗？", "How many languages can you speak? Can you speak a dialect?"),
      q(2, "你学习各外语多长时间？", "How long have you been studying each foreign language?"),
      q(3, "你觉得所有学生都必须学一种外语吗？", "Do you think all students must learn a foreign language?"),
      q(4, "你觉得所有大学生都必须修第二外语吗？", "Must all university students take a second foreign language?"),
      q(5, "在学习外语上，你觉得最大的乐趣是什么？", "What’s the greatest joy in learning a foreign language?"),
      q(6, "听说读写技能中你觉得哪一个最难？", "Among listening, speaking, reading, and writing, which is hardest?"),
      q(7, "你为什么想学华语？", "Why do you want to learn Chinese?"),
      q(8, "你平常如何练习外语？", "How do you usually practice a foreign language?"),
      q(9, "如果你是华语老师，你会怎么做来提高你学生的华语水平？", "If you were a Chinese teacher, how would you raise your students’ level?"),
      q(10, "如果你可以改变你们国家的英语教育，你将如何改变？", "If you could change English education in your country, how would you?"),
      q(11, "你觉得从几岁开始学习外语最好？", "From what age is it best to start a foreign language?"),
      q(12, "幼儿园该不该教外语？", "Should kindergartens teach a foreign language?"),
      q(13, "你觉得怎样才能学好外语？", "How can someone learn a foreign language well?"),
      q(14, "贵国的官方语言是什么？", "What is the official language of your country?"),
      q(15, "AI和翻译越来越厉害，你觉得人类将来还需要学习外语吗？为什么？", "AI and translation keep getting stronger. Will humans still need to learn foreign languages?"),
      q(16, "你常用翻译器吗？最常用哪种？请举例机器翻译很难翻好的部分。", "Do you often use a translator? Which kind? What does machine translation still do badly?"),
      q(17, "跟外国人说外语会令你紧张吗？", "Does speaking a foreign language with foreigners make you nervous?"),
      q(18, "你去过外语咖啡馆吗？", "Have you been to a foreign-language café?"),
      q(19, "你住过或当过寄宿家庭吗？", "Have you lived with or been a host family?"),
      q(20, "你在意自己的发音和腔调吗？", "Do you care about your pronunciation and accent?"),
      q(21, "如果你可以精通任何一种语言，你想精通哪一种？", "If you could master any one language, which would it be?"),
      q(22, "你想精通一种外语还是会十种语言但是每一种都只有初级水平？", "Would you rather master one language, or know ten at beginner level?"),
      q(23, "你觉得贵国的外语教育怎么样？", "What do you think of foreign-language education in your country?"),
      q(24, "你留过学吗？如果要留学，你想去哪里？为什么？", "Have you studied abroad? If you were going to, where and why?"),
      q(25, "台湾华语和普通话有什么不同？你喜欢哪一个？", "What’s the difference between Taiwan Mandarin and Putonghua? Which do you prefer?"),
      q(26, "你觉得短期游学对外语学习有帮助吗？", "Do short-term study tours help with language learning?"),
    ],
  },
]

for (const lesson of UNIT_2) assertLessonReady(lesson)
