/**
 * RULE: every dialogue line is built with notedLine(LESSON_X_Y_LINE_NOTES, …).
 * Do not add a local line() helper that skips mini lessons. Keys must match 汉字 exactly.
 */
import { LESSON_1_6_CORE_VOCAB, LESSON_1_6_GRAMMAR_FOCUS, LESSON_1_6_LINE_NOTES } from "@/content/lessons/1-6-notes"
import { LESSON_1_7_CORE_VOCAB, LESSON_1_7_GRAMMAR_FOCUS, LESSON_1_7_LINE_NOTES } from "@/content/lessons/1-7-notes"
import { LESSON_1_8_CORE_VOCAB, LESSON_1_8_GRAMMAR_FOCUS, LESSON_1_8_LINE_NOTES } from "@/content/lessons/1-8-notes"
import { LESSON_1_9_CORE_VOCAB, LESSON_1_9_GRAMMAR_FOCUS, LESSON_1_9_LINE_NOTES } from "@/content/lessons/1-9-notes"
import { LESSON_1_10_CORE_VOCAB, LESSON_1_10_GRAMMAR_FOCUS, LESSON_1_10_LINE_NOTES } from "@/content/lessons/1-10-notes"
import { notedLine } from "@/content/lessons/note-helpers"
import type { Lesson, Question, VocabItem } from "@/lib/types"

function v(hanzi: string, en: string): VocabItem {
  return { hanzi, en }
}

function q(n: number, hanzi: string, en: string, kind?: Question["kind"]): Question {
  return kind ? { n, hanzi, en, kind } : { n, hanzi, en }
}

export const UNIT_1_LESSONS_B: Lesson[] = [
  {
    id: "1-6",
    unitId: 1,
    title: "生儿育女",
    titleEn: "Having and raising children",
    pageStart: 12,
    audioId: "1-6",
    scenario: {
      time: "下午5点",
      timeEn: "5 p.m.",
      location: "办公室",
      locationEn: "Office",
      participants: "和邻座的同事",
      participantsEn: "With the colleague at the next desk",
      topic: "拜托同事帮忙，聊育儿",
      topicEn: "Asking a colleague for help, chatting about parenting",
    },
    dialogue: [
      notedLine(LESSON_1_6_LINE_NOTES,
        "A",
        "不好意思，刚刚接到学校电话说小孩不舒服，我要提早下班，可以麻烦你帮我打印这些资料吗？",
        "Sorry — the school just called saying my kid isn’t well. I need to leave early. Could you print these materials for me?",
      ),
      notedLine(LESSON_1_6_LINE_NOTES, "B", "没问题。生病了？要紧吗？", "No problem. Sick? Is it serious?"),
      notedLine(LESSON_1_6_LINE_NOTES, "A", "不知道，我等一下带去看医生。", "I don’t know. I’ll take them to the doctor in a bit."),
      notedLine(LESSON_1_6_LINE_NOTES, "B", "有小孩真累，怪不得出生率越来越低。", "Kids are exhausting. No wonder the birth rate keeps falling."),
      notedLine(LESSON_1_6_LINE_NOTES, "A", "还好啦，大部分时间都很快乐，小孩很可爱。", "It’s alright. Most of the time it’s joyful. Kids are adorable."),
      notedLine(LESSON_1_6_LINE_NOTES, "B", "听说养到大学要500万台币呢！父母老了还不一定能指望他们孝顺。", "I heard raising a child to university costs 5 million NTD! And when parents get old, they still might not be able to count on filial piety."),
      notedLine(LESSON_1_6_LINE_NOTES, "A", "没想那么多，现在只希望他们健康快乐地长大就好了。", "I don’t think that far. Right now I just hope they grow up healthy and happy."),
      notedLine(LESSON_1_6_LINE_NOTES, "B", "真佩服你们这些爸爸妈妈。你快去吧。这些就好了吗？", "I really admire you moms and dads. Go on. Is this all?"),
      notedLine(LESSON_1_6_LINE_NOTES, "A", "对，麻烦你了，谢谢！我先走了。", "Yes. Thanks so much — I’m heading out."),
    ],
    coreVocabulary: LESSON_1_6_CORE_VOCAB,
    grammarFocus: LESSON_1_6_GRAMMAR_FOCUS,
    vocabulary: [
      v("育儿", "child-rearing"),
      v("出生率", "birth rate"),
      v("月子中心", "postpartum care center"),
      v("哭闹", "crying and fussing"),
      v("偏心", "favoritism"),
      v("隔代教养", "grandparents raising grandchildren"),
      v("虎妈", "tiger mom"),
      v("外籍配偶", "foreign spouse"),
      v("领养", "adoption"),
      v("养儿防老", "raise children to provide for old age"),
      v("人口金字塔", "population pyramid"),
      v("管教", "discipline"),
      v("孝顺", "filial piety"),
    ],
    questions: [
      q(1, "为什么出生率越来越低？", "Why is the birth rate getting lower and lower?"),
      q(2, "出生率低会有什么社会问题？", "What social problems come from a low birth rate?"),
      q(3, "贵国鼓励生小孩吗？怎么鼓励？", "Does your country encourage having children? How?"),
      q(4, "搜寻〔搜索〕贵国养小孩到大学要花多少钱？再和各国比较一下。", "Look up how much it costs to raise a child to university in your country, then compare with other countries."),
      q(5, "你想要有小孩吗？有小孩的好处和坏处是什么？", "Do you want children? Pros and cons?"),
      q(
        6,
        "什么是坐月子？贵国有坐月子的习俗吗？如果你（或你的伴侣）必须坐月子，你想怎么坐？（婆婆／娘家／坐月子中心）",
        "What is 坐月子? Does your country have this custom? If you or your partner had to, where — mother-in-law, natal home, or a postpartum center?",
      ),
      q(7, "如果你有小孩，你对小孩最大的期望会是什么？", "If you had children, what would be your greatest hope for them?"),
      q(8, "你觉得养小孩最大的挑战是什么？", "What’s the biggest challenge of raising children?"),
      q(9, "你觉得现在的小孩和以前的小孩有什么不一样？", "How are children today different from children in the past?"),
      q(10, "在餐厅看见别家的／自己的孩子哭闹，你觉得怎么样？你会做什么？", "When a child — someone else’s or yours — cries in a restaurant, how do you feel? What would you do?"),
      q(11, "什么是虎妈或教育妈妈？你的看法？", "What is a “tiger mom” or “education mom”? Your view?"),
      q(12, "如果你有小孩，你会担心他／她不结婚生子吗？", "If you had children, would you worry they wouldn’t marry or have kids?"),
      q(13, "亚洲国家的小孩跟你们国家的小孩，在教养上有什么不一样？", "How is upbringing different for children in Asian countries versus your country?"),
      q(14, "你听说过隔代教养的问题吗？", "Have you heard of issues with grandparents raising grandchildren?"),
      q(15, "是否支持孩子自学（home schooling）？为什么？", "Do you support homeschooling? Why?"),
      q(16, "你认为孩子成人后应该与父母同住，还是分开各自生活？为什么？", "Should adult children live with parents or live separately? Why?"),
      q(17, "如果你跟伴侣来自不同国家，你希望你的孩子在哪里上学？", "If you and your partner were from different countries, where would you want your child to go to school?"),
      q(18, "你老了以后想跟自己的孩子住在一起吗？", "When you’re old, do you want to live with your children?"),
      q(19, "什么是“养儿防老”？贵国的传统文化中有没有这种说法？", "What is “raising children to provide for old age”? Does your culture have a similar idea?"),
      q(20, "你印象中小时候父母陪你做什么？", "In your memory, what did your parents do with you as a child?"),
      q(21, "你有两个以上小孩的话，你觉得你和配偶“偏心”吗？", "If you have more than two children, do you think you and your spouse play favorites?"),
      q(22, "贵国有育婴假吗？可以放多久？你觉得多久最好？", "Does your country have parental leave? How long? How long would be best?"),
      q(23, "你觉得商业代孕是否该合法化？", "Should commercial surrogacy be legalized?"),
      q(24, "父母可以为了管教打小孩吗？为什么？", "May parents hit children for discipline? Why?"),
      q(25, "“3岁定终身”是什么意思？你同意吗？", "What does “the first three years determine a lifetime” mean? Do you agree?"),
      q(26, "你认为什么是“孝顺”？", "What do you think filial piety is?"),
    ],
  },
  {
    id: "1-7",
    unitId: 1,
    title: "派对",
    titleEn: "Parties",
    pageStart: 14,
    audioId: "1-7",
    scenario: {
      time: "老师在贴海报",
      timeEn: "While the teacher is putting up a poster",
      location: "学校布告栏前",
      locationEn: "In front of the school bulletin board",
      participants: "和华语老师",
      participantsEn: "With a Chinese teacher",
      topic: "聊派对活动",
      topicEn: "Chatting about a party",
    },
    dialogue: [
      notedLine(LESSON_1_7_LINE_NOTES, "A", "老师好！", "Hello, teacher!"),
      notedLine(LESSON_1_7_LINE_NOTES, "B", "哦，杰克！有派对哦！", "Oh, Jack! There’s a party!"),
      notedLine(LESSON_1_7_LINE_NOTES, "A", "派对？什么派对？", "A party? What kind?"),
      notedLine(LESSON_1_7_LINE_NOTES, "B", "台湾美食派对。你喜欢派对吗？", "A Taiwanese food party. Do you like parties?"),
      notedLine(LESSON_1_7_LINE_NOTES, "A", "我喜欢吃！可是我不喝酒，也不太会跟别人聊天。", "I like eating! But I don’t drink, and I’m not great at chatting with people."),
      notedLine(LESSON_1_7_LINE_NOTES, "B", "没关系，还可以唱歌跳舞。", "That’s okay. You can also sing and dance."),
      notedLine(LESSON_1_7_LINE_NOTES, "A", "我唱歌跳舞都不行，不过我喜欢听别人唱歌、看别人跳舞。", "I’m no good at singing or dancing, but I like listening to others sing and watching them dance."),
      notedLine(LESSON_1_7_LINE_NOTES, "B", "也可以啊。要不你帮忙做菜好了！我们要做刈包、珍珠奶茶、炒米粉和贡丸汤。", "That works too. How about you help cook? We’re making gua bao, bubble tea, fried rice noodles, and pork-ball soup."),
      notedLine(LESSON_1_7_LINE_NOTES, "A", "太好了！都是我爱吃的！老师教我做！", "Perfect! Those are all my favorites! Teacher, show me how!"),
      notedLine(LESSON_1_7_LINE_NOTES, "B", "没问题，我也很高兴多一个助手！", "No problem. I’m glad to have an extra helper!"),
    ],
    coreVocabulary: LESSON_1_7_CORE_VOCAB,
    grammarFocus: LESSON_1_7_GRAMMAR_FOCUS,
    vocabulary: [
      v("开派对", "throw a party"),
      v("趴", "party (slang)"),
      v("社交舞", "social dance"),
      v("喝醉", "get drunk"),
      v("名人", "celebrity"),
      v("邀请", "invite"),
      v("好／烂借口", "a good / lame excuse"),
      v("乔迁", "moving house / housewarming"),
      v("单身", "single"),
      v("打包", "pack leftovers / takeaway"),
      v("自助", "buffet / self-serve"),
      v("代驾", "designated driver"),
      v("饭局", "dinner gathering"),
      v("很嗨", "very high-energy / hyped"),
      v("百乐餐", "potluck"),
    ],
    questions: [
      q(1, "你经常参加派对吗？", "Do you often go to parties?"),
      q(2, "你喜欢参加派对吗？", "Do you like going to parties?"),
      q(3, "描述你上一次参加的派对。", "Describe the last party you went to."),
      q(4, "你喜欢什么样的派对？为什么？", "What kind of party do you like? Why?"),
      q(5, "你印象最深的派对是什么样的？", "What was the most memorable party like?"),
      q(6, "你曾经有不愉快的派对经验吗？", "Have you ever had an unpleasant party experience?"),
      q(7, "你喜欢去别人家开派对还是请别人来你家开派对？", "Do you prefer going to someone else’s party or hosting at your place?"),
      q(8, "你帮忙策划过派对活动吗？", "Have you helped plan a party?"),
      q(9, "贵国有乔迁派对文化吗？", "Is there a housewarming-party culture in your country?"),
      q(10, "你参加过新生儿派对吗？你带什么礼物去？", "Have you been to a newborn / baby party? What gift did you bring?"),
      q(11, "贵国有“告别单身派对”文化吗？", "Does your country have bachelor / bachelorette parties?"),
      q(12, "你参加过或看过新商品发表会吗？（哪一种？）", "Have you attended or seen a product launch? What kind?"),
      q(13, "你参加过舞会吗？你会跳社交舞吗？", "Have you been to a dance? Can you do social dancing?"),
      q(14, "你喜欢站立式派对还是坐席式派对？为什么？", "Do you prefer a standing party or a seated one? Why?"),
      q(15, "在派对中你会主动找人聊天吗？", "Do you start conversations with people at parties?"),
      q(16, "你喜欢喝酒吗？参加过品酒会吗？你曾经喝醉吗？", "Do you like drinking? Have you been to a tasting? Have you ever gotten drunk?"),
      q(17, "参加自带美食、一人一菜的聚餐会，你会带什么？", "At a potluck, what would you bring?"),
      q(18, "你参加过无趣的派对吗？为什么觉得无趣？", "Have you been to a boring party? Why was it boring?"),
      q(19, "如果可以参加任何一位名人的家庭派对，你想参加谁的？", "If you could go to any celebrity’s house party, whose?"),
      q(20, "如果可以邀请任何一位名人来参加你的派对，你想邀请谁？", "If you could invite any celebrity to your party, who?"),
      q(21, "如果可以参加任何一种派对，你想参加什么样的派对？", "If you could attend any kind of party, what kind?"),
      q(22, "你觉得什么是不想参加派对时的好借口和烂借口？", "What’s a good excuse and a lame excuse for skipping a party?"),
      q(23, "如果能在任何地方开派对，你想在哪里开？（如：私人海滩、游艇、山上、湖边……）", "If you could party anywhere, where? (Private beach, yacht, mountain, lakeside…)"),
      q(24, "体演：参加朋友的新店开幕立食派对，主动和陌生人开始聊天。", "Role-play: at a friend’s standing-room shop opening, start chatting with strangers.", "roleplay"),
      q(25, "请计划一场派对，邀请老师参加。", "Plan a party and invite the teacher."),
    ],
  },
  {
    id: "1-8",
    unitId: 1,
    title: "购物",
    titleEn: "Shopping",
    pageStart: 16,
    audioId: "1-8",
    scenario: {
      time: "早上9点",
      timeEn: "9 a.m.",
      location: "公寓电梯",
      locationEn: "Apartment elevator",
      participants: "和隔壁王妈妈",
      participantsEn: "With neighbor Auntie Wang",
      topic: "搭电梯聊购物",
      topicEn: "Chatting about shopping in the elevator",
    },
    dialogue: [
      notedLine(LESSON_1_8_LINE_NOTES, "A", "王妈妈早。", "Good morning, Auntie Wang."),
      notedLine(LESSON_1_8_LINE_NOTES, "B", "早，早。去买东西啊？", "Morning, morning. Going shopping?"),
      notedLine(LESSON_1_8_LINE_NOTES, "A", "对，去超市。", "Yes, to the supermarket."),
      notedLine(LESSON_1_8_LINE_NOTES, "B", "怎么不去大菜市？传统市场东西多，又新鲜又便宜。", "Why not the big wet market? Traditional markets have more, and it’s fresher and cheaper."),
      notedLine(LESSON_1_8_LINE_NOTES, "A", "超市有定价我感觉比较安心。不过大菜市好像真的比较新鲜和便宜，下次去看看。", "Supermarkets have set prices, so I feel safer. But the wet market does seem fresher and cheaper. I’ll try it next time."),
      notedLine(LESSON_1_8_LINE_NOTES, "B", "对了，春天百货在打折你知道吗？周年庆，还有很多限定的东西哦！", "By the way, Spring Department Store is on sale — you know? Anniversary event, lots of limited items!"),
      notedLine(LESSON_1_8_LINE_NOTES, "A", "真的吗？每天忙着上班都不知道。", "Really? I’ve been so busy with work I had no idea."),
      notedLine(LESSON_1_8_LINE_NOTES, "B", "噢！我明天要去量贩店，要不要一起去？我们可以合买。", "Oh! I’m going to the warehouse store tomorrow. Want to come? We can split bulk packs."),
      notedLine(LESSON_1_8_LINE_NOTES, "A", "太好了，我一直想去量贩店，可是只有我一个人，大包装吃不完用不完。", "Perfect. I’ve been wanting to go, but I’m alone — the big packs never get finished."),
      notedLine(LESSON_1_8_LINE_NOTES, "B", "那我们明天早上9点出发，在楼下门口等我。", "Then we leave at 9 tomorrow. Wait for me at the downstairs entrance."),
      notedLine(LESSON_1_8_LINE_NOTES, "A", "好，谢谢王妈妈！王妈妈再见！", "Okay, thanks Auntie Wang! See you!"),
    ],
    coreVocabulary: LESSON_1_8_CORE_VOCAB,
    grammarFocus: LESSON_1_8_GRAMMAR_FOCUS,
    vocabulary: [
      v("网购", "shop online"),
      v("讲／杀／砍价", "haggle / bargain down the price"),
      v("讨价还价", "bargain"),
      v("心动", "tempted / interested"),
      v("卡奴", "credit-card slave"),
      v("纠纷", "dispute"),
      v("购物难民", "shopping refugee (poor access to stores)"),
      v("逛街", "go window-shopping / stroll the shops"),
      v("客诉", "customer complaint"),
      v("负评", "negative review"),
      v("刷爆", "max out a card"),
      v("支付", "pay / payment"),
      v("周年庆", "anniversary sale"),
      v("限定", "limited edition"),
      v("旗舰店", "flagship store"),
    ],
    questions: [
      q(1, "你喜欢逛街吗？", "Do you like going shopping / strolling shops?"),
      q(2, "你最近买了什么？想买什么？", "What have you bought recently? What do you want to buy?"),
      q(3, "你喜欢去哪里购物？", "Where do you like to shop?"),
      q(4, "你多久买一次东西？", "How often do you buy things?"),
      q(5, "你擅长讨价还价吗？", "Are you good at bargaining?"),
      q(6, "在你住的地方购物要讲价吗？（体演讲价）", "Do you have to bargain where you live? (Role-play bargaining.)", "roleplay"),
      q(7, "看到“打折”、“周年庆”、“限定”等标语，你会心动吗？", "Do slogans like “sale,” “anniversary,” or “limited” tempt you?"),
      q(8, "你曾经网购吗？大多在网上买什么？", "Have you shopped online? What do you mostly buy online?"),
      q(9, "你曾经在网上卖过东西吗？", "Have you sold anything online?"),
      q(10, "你购物时曾经遇过诈欺吗？", "Have you ever been scammed while shopping?"),
      q(11, "你有购物纠纷的经验吗？", "Have you had a shopping dispute?"),
      q(12, "什么是卡奴？", "What is a “credit-card slave”?"),
      q(13, "你觉得没有工作的学生可以办信用卡吗？", "Should students without jobs be able to get credit cards?"),
      q(14, "你买东西的时候会考虑哪些条件？（以服饰和电器为例）", "What do you consider when buying things? Use clothes and appliances as examples."),
      q(15, "网路〔网络〕购物与实体商店购物相比，有什么优缺点？", "Compared with physical stores, what are the pros and cons of online shopping?"),
      q(16, "你喜欢超级市场还是传统市场？为什么？", "Supermarket or traditional market? Why?"),
      q(17, "大卖场和商店街，你喜欢哪一个？为什么？", "Hypermarket or shopping street — which do you prefer? Why?"),
      q(18, "你去过量贩店吗？你喜欢在量贩店购物吗？为什么？", "Have you been to a warehouse club? Do you like shopping there? Why?"),
      q(19, "什么是购物难民？贵国政府怎么解决购物难民的问题？", "What are “shopping refugees”? How does your government address that?"),
      q(20, "你曾经客诉或给负评吗？（发生什么事？）", "Have you ever filed a complaint or left a bad review? What happened?"),
      q(21, "你喜欢自己逛街还是和朋友或家人一起逛街？", "Do you prefer shopping alone or with friends or family?"),
      q(22, "如果你必须卖东西，你要在哪里卖什么？", "If you had to sell something, where and what?"),
      q(23, "某公司的企业伦理有问题，你会因此拒绝购买他们的产品吗？", "If a company had ethics problems, would you refuse to buy from them?"),
      q(24, "你曾经退换货吗？（什么东西？为什么？）", "Have you returned or exchanged something? What, and why?"),
      q(25, "购物体演：询问、购买、退税、退换货。", "Shopping role-play: ask, buy, claim a tax refund, return or exchange.", "roleplay"),
    ],
  },
  {
    id: "1-9",
    unitId: 1,
    title: "兴趣爱好",
    titleEn: "Hobbies",
    pageStart: 18,
    audioId: "1-9",
    scenario: {
      time: "朋友做手工时",
      timeEn: "While a friend is doing crafts",
      location: "宿舍",
      locationEn: "Dormitory",
      participants: "和朋友",
      participantsEn: "With a friend",
      topic: "聊兴趣爱好",
      topicEn: "Chatting about hobbies",
    },
    dialogue: [
      notedLine(LESSON_1_9_LINE_NOTES, "A", "你在做什么？", "What are you doing?"),
      notedLine(LESSON_1_9_LINE_NOTES, "B", "剪纸。", "Paper cutting."),
      notedLine(LESSON_1_9_LINE_NOTES, "A", "剪纸？你什么时候开始有这个爱好的？我怎么不知道！", "Paper cutting? When did you start this hobby? How did I not know!"),
      notedLine(LESSON_1_9_LINE_NOTES, "B", "今年年初才开始的，很有意思。", "Only at the beginning of this year. It’s really interesting."),
      notedLine(LESSON_1_9_LINE_NOTES, "A", "好漂亮！嗯……在我的拼贴画上贴你的剪纸，应该不错！", "So pretty! Hmm… sticking your paper cuts on my collage would look good!"),
      notedLine(LESSON_1_9_LINE_NOTES, "B", "拼贴画？什么拼贴画？", "Collage? What collage?"),
      notedLine(LESSON_1_9_LINE_NOTES, "A", "把实物或各种材料贴在画面上的一种画，像这样……", "A picture where you paste real objects or materials onto the surface, like this…"),
      notedLine(LESSON_1_9_LINE_NOTES, "B", "哇！这些都是你拼贴的吗？好厉害！", "Wow! You collaged all of these? Amazing!"),
      notedLine(LESSON_1_9_LINE_NOTES,
        "A",
        "没有啦！随便弄的。其实我最想学的是油画，可是一直没行动。如果可以培养任何爱好，你还想要有什么兴趣爱好？",
        "Nah, I just threw them together. What I really want to learn is oil painting, but I never act. If you could take up any hobby, what else would you want?",
      ),
      notedLine(LESSON_1_9_LINE_NOTES, "B", "我最近迷上了摄影，想换单眼相机〔单反相机〕。", "I’ve gotten into photography lately. I want to switch to an SLR."),
      notedLine(LESSON_1_9_LINE_NOTES, "A", "太好了！你要出外景的时候记得找我啊！", "Great! When you go shoot on location, remember to take me!"),
    ],
    coreVocabulary: LESSON_1_9_CORE_VOCAB,
    grammarFocus: LESSON_1_9_GRAMMAR_FOCUS,
    vocabulary: [
      v("兴趣", "interest"),
      v("爱好", "hobby"),
      v("休假日", "day off"),
      v("退休", "retire"),
      v("集邮", "stamp collecting"),
      v("钱币", "coins"),
      v("迷", "be obsessed with / fan"),
      v("癖", "habit / collecting bug"),
      v("培养", "cultivate"),
      v("收集", "collect"),
      v("特殊", "special / unusual"),
      v("共同", "shared / in common"),
      v("个别", "individual"),
      v("文化教室", "community / culture class"),
      v("技艺", "craft / skill"),
    ],
    questions: [
      q(1, "你的休假日是什么时候？", "When are your days off?"),
      q(2, "你放学或下班后喜欢做什么？", "What do you like to do after school or work?"),
      q(3, "你休假时喜欢做什么？你什么时候开始有这些兴趣爱好的？", "What do you like to do on days off? When did these hobbies start?"),
      q(4, "你小时候的兴趣爱好和现在一样吗？", "Are your childhood hobbies the same as now?"),
      q(5, "你最近几年有没有新的兴趣？", "Have you picked up any new interests in recent years?"),
      q(6, "你最近有没有迷上什么？", "Have you gotten obsessed with anything lately?"),
      q(7, "你觉得伴侣最好有共同爱好吗？", "Do you think partners should share hobbies?"),
      q(8, "你现在的伴侣和你有共同爱好吗？", "Does your current partner share hobbies with you?"),
      q(9, "如果你的伴侣常常要求你陪他（她）做你没兴趣的事，你会怎么做？", "If your partner often asked you to join something you have no interest in, what would you do?"),
      q(
        10,
        "现在的伴侣有你不喜欢的爱好（例如：你喜欢在家他喜欢出门），你会要求对方改变吗？",
        "If your partner had a hobby you dislike (you like staying in, they like going out), would you ask them to change?",
      ),
      q(11, "你听过谁有奇怪的爱好吗？", "Have you heard of anyone with a strange hobby?"),
      q(12, "如果可以培养任何爱好，你想要什么兴趣爱好？", "If you could take up any hobby, what would it be?"),
      q(13, "你觉得每个人都必须有兴趣爱好吗？为什么？", "Does everyone need a hobby? Why?"),
      q(14, "你收集过任何东西吗？", "Have you ever collected anything?"),
      q(15, "退休后你想要有什么兴趣爱好？", "What hobbies would you want after retirement?"),
      q(16, "你的伴侣有没有什么收集癖？你无法忍受同住者收集什么？", "Does your partner collect anything? What couldn’t you stand a housemate collecting?"),
      q(17, "好友的伴侣喜欢收集好友要丢弃的东西，让好友觉得很烦，你会怎么建议？", "A friend’s partner collects things the friend wants to throw away, and it annoys them. What would you suggest?"),
      q(18, "你在过去曾经尝试过培养什么兴趣却发现它不适合你吗？", "Have you tried a hobby and found it wasn’t for you?"),
      q(19, "你的兴趣是否有助于你现在的工作？", "Do your interests help with your current job?"),
      q(20, "你是否有过想要将你的兴趣变成职业的想法？", "Have you thought about turning a hobby into a career?"),
      q(21, "你看过特殊的钱币或邮票吗？", "Have you seen unusual coins or stamps?"),
      q(22, "如果你有小孩，你想让小孩拥有什么兴趣爱好？", "If you had children, what hobbies would you want them to have?"),
      q(23, "贵国有没有技职训练、长青学校〔老年大学〕之类鼓励永续学习的机构？", "Does your country have vocational training, senior colleges, or other lifelong-learning institutions?"),
      q(24, "辩论：职业的选择以兴趣为标准。", "Debate: career choice should be based on interest.", "debate"),
    ],
  },
  {
    id: "1-10",
    unitId: 1,
    title: "个人习惯",
    titleEn: "Personal habits",
    pageStart: 20,
    audioId: "1-10",
    scenario: {
      time: "晚上11点",
      timeEn: "11 p.m.",
      location: "宿舍",
      locationEn: "Dormitory",
      participants: "和室友",
      participantsEn: "With a roommate",
      topic: "买宵夜聊坏习惯",
      topicEn: "Buying a late-night snack and chatting about bad habits",
    },
    dialogue: [
      notedLine(LESSON_1_10_LINE_NOTES, "A", "你要不要吃宵夜？我要去买生煎包。", "Want a late-night snack? I’m going to buy pan-fried buns."),
      notedLine(LESSON_1_10_LINE_NOTES, "B", "我不吃宵夜。吃宵夜不好吧，要睡觉了，不好消化。", "I don’t eat late-night snacks. It’s not good, right? We’re about to sleep — hard to digest."),
      notedLine(LESSON_1_10_LINE_NOTES, "A", "我不吃早餐，没问题。", "I don’t eat breakfast. It’s fine."),
      notedLine(LESSON_1_10_LINE_NOTES, "B", "你好像坏习惯不少，又抽烟〔吸烟〕又喝酒。", "You seem to have quite a few bad habits — smoking and drinking."),
      notedLine(LESSON_1_10_LINE_NOTES, "A", "想戒烟啊！戒不掉，太难了。", "I want to quit smoking! I can’t. It’s too hard."),
      notedLine(LESSON_1_10_LINE_NOTES, "B", "交个女朋友吧，说不定立刻改掉坏习惯。", "Get a girlfriend. Maybe you’d drop the bad habits overnight."),
      notedLine(LESSON_1_10_LINE_NOTES, "A", "希望如此，不过要是我的女友要我改这改那的也很烦。你呢？你没有坏习惯？", "I hope so. But it’d also be annoying if a girlfriend made me change this and that. You? No bad habits?"),
      notedLine(LESSON_1_10_LINE_NOTES, "B", "Hmm. 我的坏习惯大概是晚睡吧，每次都想早点睡，一上网，不知不觉就半夜1点了。", "Hmm. Mine is probably staying up late. I always mean to sleep early, get online, and it’s 1 a.m. before I notice."),
      notedLine(LESSON_1_10_LINE_NOTES, "A", "那更应该要吃宵夜！你真的不要？我去买了！", "Then you need a snack even more! You really don’t want one? I’m going!"),
      notedLine(LESSON_1_10_LINE_NOTES, "B", "要不然帮我带一碗芒果冰好了，好热！", "Then bring me a bowl of mango ice. It’s so hot!"),
    ],
    coreVocabulary: LESSON_1_10_CORE_VOCAB,
    grammarFocus: LESSON_1_10_GRAMMAR_FOCUS,
    vocabulary: [
      v("宵夜", "late-night snack"),
      v("改坏习惯", "change a bad habit"),
      v("戒烟", "quit smoking"),
      v("丢／扔垃圾", "throw away trash / litter"),
      v("懒散", "lazy / sloppy"),
      v("勤快", "hardworking / diligent"),
      v("狗改不了吃屎", "a leopard can’t change its spots (lit. a dog can’t stop eating dung)"),
      v("自主", "self-directed / autonomous"),
      v("改变", "change"),
      v("零食", "snacks"),
    ],
    questions: [
      q(1, "你有什么好习惯？", "What good habits do you have?"),
      q(2, "你有不好的习惯吗？", "Do you have bad habits?"),
      q(3, "你会咬指甲吗？", "Do you bite your nails?"),
      q(4, "你睡在沙发上吗？", "Do you sleep on the sofa?"),
      q(5, "你会吃宵夜吗？你最晚曾经几点去买吃的？", "Do you eat late-night snacks? What’s the latest you’ve gone out to buy food?"),
      q(6, "什么是健康的和不良的饮食习惯？你的饮食习惯怎么样？", "What are healthy and unhealthy eating habits? How are yours?"),
      q(7, "人们的不良习惯主要是从家庭还是学校社会养成的？", "Are bad habits mainly formed at home, or at school and in society?"),
      q(8, "什么是好的和不好的学习习惯？", "What are good and bad study habits?"),
      q(9, "你的学习习惯怎么样？", "How are your study habits?"),
      q(10, "你觉得孩子们在学校还是在家里更容易学到不好的习惯？", "Do children pick up bad habits more easily at school or at home?"),
      q(11, "你会吸烟吗？你觉得戒烟难吗？", "Do you smoke? Is quitting hard?"),
      q(12, "改掉坏习惯容易还是培养好习惯容易？", "Is it easier to break a bad habit or build a good one?"),
      q(13, "你小时候有没有什么习惯是现在没有的？", "Did you have childhood habits you don’t have now?"),
      q(14, "贵国人民常在街上扔垃圾吗？", "Do people in your country often litter on the street?"),
      q(15, "你觉得自己懒吗？", "Do you think you’re lazy?"),
      q(16, "你曾经成功改掉坏习惯吗？", "Have you ever successfully broken a bad habit?"),
      q(17, "你认为哪种坏习惯是最难改的？为什么？", "Which bad habit is hardest to break? Why?"),
      q(18, "你认为哪种好习惯是最难养成的？为什么？", "Which good habit is hardest to build? Why?"),
      q(19, "如果可以改变任何一位身边的人，你想改变谁的什么？", "If you could change something about someone around you, who and what?"),
      q(20, "你最讨厌跑步可是你的伴侣基于健康理由，要求你每天陪他晨跑，你会怎么做？", "You hate running, but your partner wants you to morning-run every day for health. What would you do?"),
      q(21, "中国俗语“狗改不了吃屎”是什么意思？你赞成吗？", "What does the saying “a dog can’t stop eating dung” mean? Do you agree?"),
      q(22, "你觉得男人或女人可以为爱人改变自己的习惯吗？", "Can men or women change their habits for someone they love?"),
      q(23, "你有没有一个你想要养成的习惯但是一直没有成功？", "Is there a habit you’ve wanted to build but never managed?"),
      q(24, "你现在最想培养的好习惯是什么？", "What good habit do you most want to build now?"),
      q(25, "阅读讨论：《原子习惯》（James Clear, 2018）", "Reading discussion: Atomic Habits (James Clear, 2018).", "reading"),
    ],
  },
]
