/**
 * RULE: every dialogue line is built with notedLine(LESSON_X_Y_LINE_NOTES, …).
 * Keys must match 汉字 exactly, including 〔酒店〕 / 〔菠萝〕 / 〔程序〕, Latin Hmm / hmm / KTV, and spaces around 3 / 14 题.
 */
import {
  LESSON_4_1_CHUNKS,
  LESSON_4_1_CORE_VOCAB,
  LESSON_4_1_FAMILY,
  LESSON_4_1_FILL_BLANKS,
  LESSON_4_1_GRAMMAR_FOCUS,
  LESSON_4_1_LINE_NOTES,
  LESSON_4_1_PRACTICE,
} from "@/content/lessons/4-1-notes"
import {
  LESSON_4_2_CHUNKS,
  LESSON_4_2_CORE_VOCAB,
  LESSON_4_2_FAMILY,
  LESSON_4_2_FILL_BLANKS,
  LESSON_4_2_GRAMMAR_FOCUS,
  LESSON_4_2_LINE_NOTES,
  LESSON_4_2_PRACTICE,
} from "@/content/lessons/4-2-notes"
import {
  LESSON_4_3_CHUNKS,
  LESSON_4_3_CORE_VOCAB,
  LESSON_4_3_FAMILY,
  LESSON_4_3_FILL_BLANKS,
  LESSON_4_3_GRAMMAR_FOCUS,
  LESSON_4_3_LINE_NOTES,
  LESSON_4_3_PRACTICE,
} from "@/content/lessons/4-3-notes"
import {
  LESSON_4_4_CHUNKS,
  LESSON_4_4_CORE_VOCAB,
  LESSON_4_4_FAMILY,
  LESSON_4_4_FILL_BLANKS,
  LESSON_4_4_GRAMMAR_FOCUS,
  LESSON_4_4_LINE_NOTES,
  LESSON_4_4_PRACTICE,
} from "@/content/lessons/4-4-notes"
import {
  LESSON_4_5_CHUNKS,
  LESSON_4_5_CORE_VOCAB,
  LESSON_4_5_FAMILY,
  LESSON_4_5_FILL_BLANKS,
  LESSON_4_5_GRAMMAR_FOCUS,
  LESSON_4_5_LINE_NOTES,
  LESSON_4_5_PRACTICE,
} from "@/content/lessons/4-5-notes"
import {
  LESSON_4_6_CHUNKS,
  LESSON_4_6_CORE_VOCAB,
  LESSON_4_6_FAMILY,
  LESSON_4_6_FILL_BLANKS,
  LESSON_4_6_GRAMMAR_FOCUS,
  LESSON_4_6_LINE_NOTES,
  LESSON_4_6_PRACTICE,
} from "@/content/lessons/4-6-notes"
import {
  LESSON_4_7_CHUNKS,
  LESSON_4_7_CORE_VOCAB,
  LESSON_4_7_FAMILY,
  LESSON_4_7_FILL_BLANKS,
  LESSON_4_7_GRAMMAR_FOCUS,
  LESSON_4_7_LINE_NOTES,
  LESSON_4_7_PRACTICE,
} from "@/content/lessons/4-7-notes"
import { assertLessonReady, notedLine } from "@/content/lessons/note-helpers"
import type { Lesson, Question, VocabItem } from "@/lib/types"

function v(hanzi: string, en: string): VocabItem {
  return { hanzi, en }
}

function q(n: number, hanzi: string, en: string, kind?: Question["kind"]): Question {
  return kind ? { n, hanzi, en, kind } : { n, hanzi, en }
}

export const UNIT_4: Lesson[] = [
  {
    id: "4-1",
    unitId: 4,
    title: "自我介绍",
    titleEn: "Self-introduction",
    pageStart: 46,
    audioId: "4-1",
    scenario: {
      time: "8分钟快速约会",
      timeEn: "8-minute speed dating",
      location: "大饭店〔大酒店〕",
      locationEn: "A grand hotel",
      participants: "和相亲对象",
      participantsEn: "With a blind-date partner",
      topic: "自我介绍",
      topicEn: "Self-introduction",
    },
    dialogue: [
      notedLine(LESSON_4_1_LINE_NOTES, "A", "你在哪里高就？", "Where do you work?"),
      notedLine(LESSON_4_1_LINE_NOTES, "B", "我是健身教练，专门塑造健美的曲线。你呢？", "I’m a fitness trainer. I specialize in sculpting a fit body line. You?"),
      notedLine(
        LESSON_4_1_LINE_NOTES,
        "A",
        "我是心理师，当情侣吵架时会来找我，我负责帮他们重修旧好。",
        "I’m a psychologist. When couples fight they come to me — I help them make up.",
      ),
      notedLine(LESSON_4_1_LINE_NOTES, "B", "能看透人心的心理师！那你知道我现在在想什么吗？", "A psychologist who can see through people! So do you know what I’m thinking right now?"),
      notedLine(LESSON_4_1_LINE_NOTES, "A", "呵呵，我是心理师不是预言师。", "Ha — I’m a psychologist, not a prophet."),
      notedLine(
        LESSON_4_1_LINE_NOTES,
        "B",
        "我在想我的健身中心如果请一个心理师，身心平衡，好像很赞！",
        "I was thinking if my gym hired a psychologist — mind–body balance — that sounds great!",
      ),
      notedLine(LESSON_4_1_LINE_NOTES, "A", "可以合作哦。你平时都在运动，周末也会运动吗？", "We could work together. You work out all the time — weekends too?"),
      notedLine(LESSON_4_1_LINE_NOTES, "B", "没，周末上网、看电影。你呢？", "No. Weekends I go online and watch movies. You?"),
      notedLine(LESSON_4_1_LINE_NOTES, "A", "我周末喜欢出去走走、照照相。", "On weekends I like to walk around and take photos."),
      notedLine(LESSON_4_1_LINE_NOTES, "B", "我也喜欢照相，我知道很多好地方，下次可以一起去兜风！", "I like photos too. I know lots of good places — next time we can go for a drive!"),
    ],
    notes: [{ hanzi: "高就：客气地问对方在哪里工作。", en: "高就 is a polite “where do you work?” — common at 相亲 and speed dating." }],
    coreVocabulary: LESSON_4_1_CORE_VOCAB,
    chunks: LESSON_4_1_CHUNKS,
    expressionFamily: { title: "一套自我介绍说法", titleEn: "One family of self-intro expressions", items: LESSON_4_1_FAMILY },
    grammarFocus: LESSON_4_1_GRAMMAR_FOCUS,
    practiceSentences: LESSON_4_1_PRACTICE,
    fillBlanks: LESSON_4_1_FILL_BLANKS,
    vocabulary: [
      v("搬家", "to move house"),
      v("影响", "to influence; influence"),
      v("亲密", "close; intimate"),
      v("悼念", "to mourn; to commemorate the dead"),
      v("长处", "strength"),
      v("短处", "weakness"),
      v("真人开箱挑战", "human Tetris / packing challenge"),
      v("快速", "fast; quick"),
      v("幽默", "humor; humorous"),
      v("第一印象", "first impression"),
      v("意义", "meaning; significance"),
      v("出生", "to be born; birth"),
    ],
    questions: [
      q(1, "3分钟自我介绍。", "A 3-minute self-introduction."),
      q(2, "1分钟自我介绍。", "A 1-minute self-introduction."),
      q(3, "你在哪里出生？在哪里长大？现在住在哪里？", "Where were you born? Where did you grow up? Where do you live now?"),
      q(4, "你一个人住还是和家人住？", "Do you live alone or with family?"),
      q(5, "你搬过几次家？住过哪些地方？", "How many times have you moved? Which places have you lived?"),
      q(6, "五年后的你会是什么样的呢？十年后呢？", "What will you be like in five years? In ten?"),
      q(7, "你有什么特殊技能吗？", "Do you have any special skills?"),
      q(8, "用幽默的一句话形容你的工作。", "Describe your job in one humorous sentence."),
      q(9, "你能在别的国家生活吗？", "Could you live in another country?"),
      q(10, "介绍对你一生影响最大的人。", "Introduce the person who has influenced your life the most."),
      q(11, "生命的意义是什么？", "What is the meaning of life?"),
      q(12, "你最在意的是什么？", "What do you care about most?"),
      q(13, "你最不能忍受的是什么？", "What can you least stand?"),
      q(14, "想象在8分钟快速约会中，你怎么让对方留下深刻印象？", "In an 8-minute speed date, how would you leave a deep impression?"),
      q(15, "你的座右铭或最喜欢的一句话是什么？", "What’s your motto or favorite line?"),
      q(16, "你有几个亲密的好友？", "How many close friends do you have?"),
      q(17, "如果能知道死后朋友对你的悼念词，你希望听到朋友怎么介绍你？", "If you could hear the eulogy friends would give, how would you want them to introduce you?"),
      q(18, "如果有来世，下辈子你想当什么样的人？", "If there is a next life, what kind of person would you want to be?"),
      q(19, "你的长处和短处是什么？", "What are your strengths and weaknesses?"),
      q(20, "你擅长什么？不擅长什么？", "What are you good at? Not good at?"),
      q(21, "用一个成语或一个词形容你自己。", "Describe yourself with one idiom or one word."),
      q(22, "如果你能改变一件关于你自己的事，你想改变什么？", "If you could change one thing about yourself, what would it be?"),
      q(23, "和老师或同学玩“三对一错”游戏。", "Play “three truths and one lie” with the teacher or classmates."),
      q(24, "你有什么梦想？", "What dreams do you have?"),
      q(25, "搜寻〔搜索〕真人开箱挑战 (Tetris Challenge)，你的开箱图会是什么样子？请简单画一下。", "Search the human Tetris Challenge. What would your packing picture look like? Sketch it."),
    ],
  },
  {
    id: "4-2",
    unitId: 4,
    title: "经常和不常做的事",
    titleEn: "Things you do and don’t do",
    pageStart: 48,
    audioId: "4-2",
    scenario: {
      time: "晚餐时间",
      timeEn: "Dinnertime",
      location: "拉面店",
      locationEn: "A ramen shop",
      participants: "和朋友",
      participantsEn: "With a friend",
      topic: "聊吃喝玩乐计划",
      topicEn: "Chatting about eat-drink-and-be-merry plans",
    },
    dialogue: [
      notedLine(LESSON_4_2_LINE_NOTES, "A", "路口新开的那家饭店〔酒店〕推出开幕优惠套餐呢！", "The new place at the intersection is offering an opening set-meal deal!"),
      notedLine(LESSON_4_2_LINE_NOTES, "B", "我们去吃！我很久没吃大餐了！", "Let’s go eat! I haven’t had a big meal in a long time!"),
      notedLine(LESSON_4_2_LINE_NOTES, "A", "我也是，大概一年来都没吃大餐了。", "Me too — I haven’t had a big meal in about a year."),
      notedLine(LESSON_4_2_LINE_NOTES, "B", "那家饭店不是还有水疗吗？我也好久没泡汤了。", "Doesn’t that place also have a spa? I haven’t soaked in ages either."),
      notedLine(LESSON_4_2_LINE_NOTES, "A", "我上一次泡汤好像是两年前。我们可以下午先去泡。", "Last time I soaked was maybe two years ago. We can go soak in the afternoon first."),
      notedLine(LESSON_4_2_LINE_NOTES, "B", "说到泡汤就想到日本。以前每年都至少会去一次。", "Speaking of soaking, I think of Japan. I used to go at least once a year."),
      notedLine(LESSON_4_2_LINE_NOTES, "A", "日本很适合自助游。我是疫情前每年都至少去一个国家玩。", "Japan is great for independent travel. Before the pandemic I visited at least one country a year."),
      notedLine(LESSON_4_2_LINE_NOTES, "B", "不知道这波疫情要到什么时候才会结束，闷死了。", "Who knows when this wave will end. I’m bored to death."),
      notedLine(LESSON_4_2_LINE_NOTES, "A", "对啊，三年没出国旅行了。", "Right — I haven’t traveled abroad in three years."),
      notedLine(LESSON_4_2_LINE_NOTES, "B", "快预约吧，新开幕又有优惠，一定很热门，希望还订得到。", "Book it quick. New opening plus a deal — it’ll be packed. Hope we can still get a table."),
    ],
    coreVocabulary: LESSON_4_2_CORE_VOCAB,
    chunks: LESSON_4_2_CHUNKS,
    expressionFamily: { title: "一套“多久没”说法", titleEn: "One family of “haven’t … in ages” expressions", items: LESSON_4_2_FAMILY },
    grammarFocus: LESSON_4_2_GRAMMAR_FOCUS,
    practiceSentences: LESSON_4_2_PRACTICE,
    fillBlanks: LESSON_4_2_FILL_BLANKS,
    vocabulary: [
      v("剪头发", "to get a haircut"),
      v("搭计程车〔出租车〕", "to take a taxi"),
      v("图书馆", "library"),
      v("旅行", "to travel; a trip"),
      v("吃大餐", "to have a big meal"),
      v("温泉", "hot spring"),
      v("水疗", "spa"),
      v("泡汤", "to soak in a hot spring"),
      v("家乡菜", "hometown food"),
      v("热门", "popular"),
      v("疫情", "pandemic; epidemic"),
      v("闷", "bored; stuffy; pent-up"),
      v("新开幕", "newly opened"),
      v("优惠", "a deal; discount"),
    ],
    questions: [
      q(1, "你多久剪一次头发？", "How often do you get a haircut?"),
      q(2, "你多久看一场电影？", "How often do you see a movie?"),
      q(3, "你常搭计程车〔出租车〕吗？", "Do you often take a taxi?"),
      q(4, "你多久和家人出游一回？", "How often do you take a trip with family?"),
      q(5, "你最后一次去图书馆是什么时候？", "When was the last time you went to a library?"),
      q(6, "你最后一次说英文是什么时候？", "When was the last time you spoke English?"),
      q(7, "你多久没去市场了？", "How long has it been since you went to a market?"),
      q(8, "你多久没去旅行了？最后一次是什么时候？", "How long since you traveled? When was the last time?"),
      q(9, "你多久没唱歌或跳舞了？", "How long since you sang or danced?"),
      q(10, "你上个星期有几天没看电视 / 用电脑〔计算机〕？", "Last week, how many days did you go without TV / a computer?"),
      q(11, "你去年有多久没住在家里？", "Last year, how long were you not living at home?"),
      q(12, "你多久没看课本以外的书了？", "How long since you read a book that wasn’t a textbook?"),
      q(13, "你多久没看报纸了？", "How long since you read a newspaper?"),
      q(14, "你多久没吃大餐了？你最后一次吃家乡菜是什么时候？", "How long since a big meal? When did you last eat hometown food?"),
      q(15, "你多久去温泉或水疗 (spa) 一次？", "How often do you go to a hot spring or spa?"),
      q(16, "你最后一次大笑是什么时候？", "When was the last time you laughed hard?"),
      q(17, "你和朋友多久见一次面？你多久没跟朋友见面了？", "How often do you see friends? How long since you last met?"),
      q(18, "你经常忘记带东西吗？（什么东西最常忘了带？）", "Do you often forget things? (What do you forget most?)"),
      q(19, "如果能够，你最想再次体验的事是什么？为什么？", "If you could, what would you most want to experience again? Why?"),
      q(20, "你以后想多做什么事？少做什么事？", "What do you want to do more later? Less?"),
      q(21, "跟十年前的自己相比，你“经常做的事和不常做的事”有什么变化？", "Compared with yourself ten years ago, what changed in what you often / seldom do?"),
      q(22, "你常在外用餐吗？你最常吃的三餐是什么？", "Do you often eat out? What are your most common meals?"),
      q(23, "你最常用的网站是什么？", "What website do you use most?"),
      q(24, "你经常在课堂上或工作时打瞌睡吗？", "Do you often doze off in class or at work?"),
      q(25, "你从来不做什么？", "What do you never do?"),
      q(26, "在你从来不做的事中，哪一件事是将来可能想尝试的？", "Of the things you never do, which might you want to try later?"),
    ],
  },
  {
    id: "4-3",
    unitId: 4,
    title: "恋爱和约会",
    titleEn: "Love and dating",
    pageStart: 50,
    audioId: "4-3",
    scenario: {
      time: "晚上9点",
      timeEn: "9 p.m.",
      location: "电话中",
      locationEn: "On the phone",
      participants: "和闺蜜",
      participantsEn: "With a best girl friend",
      topic: "聊朋友闪婚",
      topicEn: "Chatting about a friend’s flash marriage",
    },
    dialogue: [
      notedLine(LESSON_4_3_LINE_NOTES, "A", "你看到了吗？小文要结婚了！", "Did you see? Xiaowen is getting married!"),
      notedLine(LESSON_4_3_LINE_NOTES, "B", "蛤？真假？！", "Huh? For real?!"),
      notedLine(LESSON_4_3_LINE_NOTES, "A", "昨天她的脸书你没看吗？跟她的网友，挪威人。", "Didn’t you see her Facebook yesterday? With her online friend — a Norwegian."),
      notedLine(LESSON_4_3_LINE_NOTES, "B", "挪威网友？不是才在网上认识一年多而已？", "A Norwegian online friend? Didn’t they only meet online a year or so ago?"),
      notedLine(
        LESSON_4_3_LINE_NOTES,
        "A",
        "对啊，听说他上星期飞来台湾跟她见面，两人一见钟情，立刻去登记结婚，好像马上要一起去挪威了。",
        "Right. I heard he flew to Taiwan last week. They fell in love at first sight, registered the marriage at once, and it seems they’re about to leave for Norway together.",
      ),
      notedLine(
        LESSON_4_3_LINE_NOTES,
        "B",
        "哇！太浪漫了，网恋、异国、远距、闪电结婚全都来了！她爸妈心脏也真够大颗！",
        "Wow, too romantic. Online, cross-country, long-distance, flash marriage — the full set! Her parents’ hearts are really bold!",
      ),
      notedLine(
        LESSON_4_3_LINE_NOTES,
        "A",
        "科学家说如果人类坠入情网，大脑判断功能会降低。不过我相信她的直觉啦。我是来问你我们要合送什么礼物的？",
        "Scientists say if humans fall in love, judgment drops. But I trust her intuition. I called to ask what gift we should give together.",
      ),
      notedLine(LESSON_4_3_LINE_NOTES, "B", "挪威啊？感觉很冷，送个什么防寒的？", "Norway? Feels cold — send some kind of winter thing?"),
      notedLine(LESSON_4_3_LINE_NOTES, "A", "防寒的在当地买就好了。我看先约她出来聊聊吧！", "They can just buy winter stuff there. I say we ask her out to chat first!"),
      notedLine(LESSON_4_3_LINE_NOTES, "B", "对！然后我们再探听她可能会需要什么。", "Yes! Then we can sound out what she might need."),
    ],
    notes: [{ hanzi: "大颗：台湾口语，胆子大、心够宽。", en: "大颗 is Taiwan spoken for bold / big-hearted — here, parents OK with a 闪婚." }],
    coreVocabulary: LESSON_4_3_CORE_VOCAB,
    chunks: LESSON_4_3_CHUNKS,
    expressionFamily: { title: "一套恋爱说法", titleEn: "One family of love-and-dating expressions", items: LESSON_4_3_FAMILY },
    grammarFocus: LESSON_4_3_GRAMMAR_FOCUS,
    practiceSentences: LESSON_4_3_PRACTICE,
    fillBlanks: LESSON_4_3_FILL_BLANKS,
    vocabulary: [
      v("各付各的", "each pays their own (going Dutch)"),
      v("一见钟情", "love at first sight"),
      v("秀恩爱", "to show off being in love"),
      v("告白", "to confess love"),
      v("坠入情网", "to fall in love"),
      v("甜言蜜语", "sweet talk"),
      v("畸恋", "a taboo / “twisted” romance"),
      v("柏拉图式恋爱", "Platonic love"),
      v("网恋", "online romance"),
      v("闪电结婚", "flash marriage"),
      v("探听", "to sound out; to fish for info"),
    ],
    questions: [
      q(1, "描述你的梦中情人或理想的约会对象。", "Describe your dream partner or ideal date."),
      q(2, "对你来说，爱情和面包哪个更重要？为什么？", "For you, which matters more — love or bread? Why?"),
      q(3, "约会时你们各付各的吗？", "On dates, do you each pay your own way?"),
      q(4, "你相信一见钟情吗？", "Do you believe in love at first sight?"),
      q(5, "情侣可以在公共场所秀恩爱吗？为什么？", "Can couples show affection in public? Why?"),
      q(6, "第一次约会时你穿什么？", "What do you wear on a first date?"),
      q(7, "爱和喜欢有什么区别？", "What’s the difference between love and like?"),
      q(8, "可以分享你的初恋故事吗？", "Can you share your first-love story?"),
      q(9, "你能接受远距离恋爱吗？", "Can you accept a long-distance relationship?"),
      q(10, "举例一些热门的约会地方。", "Give some popular date spots."),
      q(11, "贵国高中以下的学生可以在学校谈恋爱吗？", "In your country, can students below high-school age date at school?"),
      q(12, "在你们国家，男女约会一般谁付钱？为什么？", "In your country, who usually pays on a date? Why?"),
      q(13, "在你们国家，男女约会一般谁先到？为什么？", "Who usually arrives first? Why?"),
      q(14, "如果你的前任男/女朋友联络你想约见面，你会去吗？", "If an ex contacted you to meet, would you go?"),
      q(15, "如果你爱上了一个人，你会告白吗？", "If you fell in love with someone, would you confess?"),
      q(16, "你搭讪过人或被搭讪过吗？（在哪？说什么？）", "Have you ever hit on someone or been hit on? (Where? What did you say?)"),
      q(17, "想象你必须在这些场所找一位异性聊天，你的第一句话是什么？（1. 街上；2. 酒吧；3. 飞机邻座；4. 青年旅馆）", "You must start a chat with someone in these places. First line? Street, bar, plane seat, hostel."),
      q(18, "你什么时候会向你的父母介绍男/女朋友？", "When would you introduce a partner to your parents?"),
      q(19, "研究发现，如果人类坠入情网，大脑判断功能会降低，你相信吗？有什么跟你自己有关或你听说过的例子吗？", "Research says falling in love lowers judgment. Do you believe it? Any example?"),
      q(20, "你曾经单恋吗？现在还跟曾经暗恋过的对象保持联络吗？或是你从来没有暗恋过任何人？", "Have you had a one-sided love? Still in touch with that crush — or never had one?"),
      q(21, "人类会因甜言蜜语而受到感动，你认为透过大数据分析出高超话术的人工智能机器人是否能让你爱上它？", "Sweet talk moves people. Could an AI with data-trained lines make you fall for it?"),
      q(22, "你曾经失恋吗？你认为谈恋爱很困难吗？为什么？", "Have you had your heart broken? Is dating hard? Why?"),
      q(23, "人说师生恋、姐弟恋、兄妹恋、老少恋等是畸恋，你对这些恋爱关系有什么看法？", "People call teacher-student, older-younger, sibling-like, and May-December romances “畸恋.” What’s your view?"),
      q(24, "你对柏拉图式恋爱的看法？", "What’s your view of Platonic love?"),
    ],
  },
  {
    id: "4-4",
    unitId: 4,
    title: "喜好和厌恶",
    titleEn: "Likes and dislikes",
    pageStart: 52,
    audioId: "4-4",
    scenario: {
      time: "周日中午",
      timeEn: "Sunday noon",
      location: "朋友家",
      locationEn: "A friend’s house",
      participants: "和闺蜜",
      participantsEn: "With a best girl friend",
      topic: "喝茶聊喜好",
      topicEn: "Drinking tea and talking likes",
    },
    dialogue: [
      notedLine(LESSON_4_4_LINE_NOTES, "A", "好香啊！我最爱东方美人茶了！", "It smells so good! Oriental Beauty is my favorite tea!"),
      notedLine(
        LESSON_4_4_LINE_NOTES,
        "B",
        "也是我的最爱。一天中我最喜欢的时间就是晚上洗完澡，坐在阳台喝一杯东方美人看夜景。",
        "Mine too. My favorite time of day is after a night shower, on the balcony with a cup of Oriental Beauty and the night view.",
      ),
      notedLine(LESSON_4_4_LINE_NOTES, "A", "晚上喝茶不会睡不着吗？", "Won’t tea at night keep you up?"),
      notedLine(LESSON_4_4_LINE_NOTES, "B", "不会，东方美人比较没有咖啡因。", "No — Oriental Beauty has relatively little caffeine."),
      notedLine(LESSON_4_4_LINE_NOTES, "A", "你家的桌巾好美哦！", "Your tablecloth is so pretty!"),
      notedLine(LESSON_4_4_LINE_NOTES, "B", "青花瓷的青色是我最喜欢的颜色。你最喜欢什么颜色？", "The blue of blue-and-white porcelain is my favorite color. What’s yours?"),
      notedLine(LESSON_4_4_LINE_NOTES, "A", "我喜欢柔粉色。", "I like soft pink."),
      notedLine(LESSON_4_4_LINE_NOTES, "B", "你今天这件粉色洋装很适合你，很显气色。", "That pink dress really suits you today — it brings out your complexion."),
      notedLine(LESSON_4_4_LINE_NOTES, "A", "谢谢。吃吃看我做的土凤梨〔菠萝〕酥吧，搭配东方美人正好。", "Thanks. Try the pineapple cake I made — it goes perfectly with Oriental Beauty."),
      notedLine(
        LESSON_4_4_LINE_NOTES,
        "B",
        "好久没吃凤梨〔菠萝〕酥了。（品尝后）Hmm～好厉害！不会太甜，比卖的还好吃！",
        "I haven’t had pineapple cake in ages. (After tasting) Hmm — amazing! Not too sweet. Even better than store-bought!",
      ),
    ],
    notes: [{ hanzi: "土凤梨酥：台湾用凤梨，大陆说法是菠萝。", en: "土凤梨酥 is Taiwan pineapple cake; 〔菠萝〕 is the mainland fruit name." }],
    coreVocabulary: LESSON_4_4_CORE_VOCAB,
    chunks: LESSON_4_4_CHUNKS,
    expressionFamily: { title: "一套喜好和厌恶说法", titleEn: "One family of like-and-dislike expressions", items: LESSON_4_4_FAMILY },
    grammarFocus: LESSON_4_4_GRAMMAR_FOCUS,
    practiceSentences: LESSON_4_4_PRACTICE,
    fillBlanks: LESSON_4_4_FILL_BLANKS,
    vocabulary: [
      v("最爱", "favorite"),
      v("谚语", "proverb; saying"),
      v("厌恶", "to loathe; dislike"),
      v("味道", "taste; flavor"),
      v("气味", "smell; odor"),
      v("忍受", "to endure"),
      v("气色", "complexion; color in the face"),
      v("咖啡因", "caffeine"),
      v("被封锁", "to be blocked (account / access)"),
      v("拉黑", "to block (on social media)"),
      v("改观", "to change one’s view"),
      v("手机", "mobile phone"),
      v("游戏", "game"),
    ],
    questions: [
      q(1, "你最好的朋友是谁？", "Who is your best friend?"),
      q(2, "你想改变的三件事。", "Three things you want to change."),
      q(3, "你绝对不想改变的三件事。", "Three things you absolutely don’t want to change."),
      q(4, "你讨厌和什么样的人一起旅行？", "What kind of person do you hate traveling with?"),
      q(5, "你最喜欢的名人？", "Your favorite celebrity?"),
      q(6, "你的童年记忆，好坏各说一件。", "One good and one bad childhood memory."),
      q(7, "你最珍贵的三个财产？", "Your three most precious possessions?"),
      q(8, "在你的公司或学校中有没有你很喜欢和讨厌的人？为什么？", "At work or school, is there someone you really like and someone you can’t stand? Why?"),
      q(9, "你最讨厌别人问你什么？", "What question do you hate being asked most?"),
      q(10, "问老师或语伴三个他们的喜好和厌恶。", "Ask the teacher or language partner for three likes and dislikes."),
      q(11, "你最喜欢的电视节目是什么？", "What’s your favorite TV show?"),
      q(12, "你觉得人的第一印象对于决定被喜欢还是厌恶很重要吗？为什么？", "Is first impression important for being liked or disliked? Why?"),
      q(13, "你最喜欢和讨厌的食物味道？", "Favorite and most-hated food flavors?"),
      q(14, "关于你家 / 学校 / 公司，你喜欢和不喜欢什么？", "About home / school / work — what do you like and dislike?"),
      q(15, "你和你伴侣的喜好厌恶差不多吗？如果有部分相反或完全相反的话，你会怎么做？", "Are your likes close to your partner’s? If some or all are opposite, what do you do?"),
      q(16, "你最喜欢和讨厌的气味是什么？", "Favorite and most-hated smells?"),
      q(17, "当你年轻的时候，你最喜爱的歌手？现在呢？", "Favorite singer when you were young? Now?"),
      q(18, "去好友家做客，有一道菜是你不喜欢吃的，但好友妈妈热情地请你吃，你会怎么做？", "At a friend’s, a dish you dislike — the mom keeps offering it. What do you do?"),
      q(19, "如果你可以和任何人（去世的或在世的）见面，你想见谁和做什么？", "If you could meet anyone living or dead, who, and do what?"),
      q(20, "朋友聚会，有人一直说你不爱听的话题，你会怎么做？", "At a gathering someone keeps talking about a topic you hate. What do you do?"),
      q(21, "如果让你选择，以下哪样东西你最无法忍受“一年不能碰触”？网路〔网络〕、车、手机、伴侣，还是酒？", "Which could you least stand not touching for a year: internet, car, phone, partner, or alcohol?"),
      q(22, "你曾经在社交网站上拉黑谁或被拉黑吗？（为什么？）", "Have you blocked someone on social media, or been blocked? (Why?)"),
      q(23, "你有本来很喜欢或讨厌一个人但后来完全改观的经验吗？怎么改观的？", "Have you fully changed your view of someone you liked or hated? How?"),
    ],
  },
  {
    id: "4-5",
    unitId: 4,
    title: "愿望",
    titleEn: "Wishes",
    pageStart: 54,
    audioId: "4-5",
    scenario: {
      time: "1月初",
      timeEn: "Early January",
      location: "居酒屋",
      locationEn: "An izakaya",
      participants: "和朋友",
      participantsEn: "With friends",
      topic: "聊新年新希望",
      topicEn: "Talking about New Year’s resolutions",
    },
    dialogue: [
      notedLine(LESSON_4_5_LINE_NOTES, "A", "今年有没有立下“新年新希望”啊？", "Did you set a New Year’s resolution this year?"),
      notedLine(
        LESSON_4_5_LINE_NOTES,
        "B",
        "还是跟去年一样，希望减 3 公斤，去年也没成功，哎，3 公斤怎么这么难呢？你呢？",
        "Same as last year: lose 3 kilos. Didn’t succeed last year either. Ugh — how can 3 kilos be this hard? You?",
      ),
      notedLine(LESSON_4_5_LINE_NOTES, "A", "我想挑战全马。", "I want to take on a full marathon."),
      notedLine(LESSON_4_5_LINE_NOTES, "B", "哇！欸？你去年只有跑半马？我以为你跑全马了。", "Wait — last year you only ran a half? I thought you’d already done a full."),
      notedLine(LESSON_4_5_LINE_NOTES, "A", "没，去年跑半马，好像还行，今年看能不能跑完全马。", "No. Last year a half — it was pretty OK. This year we’ll see if I can finish a full."),
      notedLine(
        LESSON_4_5_LINE_NOTES,
        "B",
        "我完全无法理解跑步的乐趣，跑步到底有什么乐趣？跑步时你们在想什么？",
        "I completely cannot understand the fun of running. What fun is there, really? What do you think about while you run?",
      ),
      notedLine(LESSON_4_5_LINE_NOTES, "A", "就是什么都不想，所以可以完全放空，很纾压。", "I think about nothing — so I can fully empty my mind. Very de-stressing."),
      notedLine(LESSON_4_5_LINE_NOTES, "B", "什么啊！累得半死还纾压咧？", "Come on! Exhausted to death and you call that de-stressing?"),
      notedLine(LESSON_4_5_LINE_NOTES, "A", "你不是想减 3 公斤？陪我去练跑，保证你达标。", "Didn’t you want to lose 3 kilos? Come train with me. I guarantee you’ll hit it."),
      notedLine(LESSON_4_5_LINE_NOTES, "B", "算了，你去跑步放空头脑，我想办法放空肚子就好了。", "Forget it. You go empty your head running. I’ll just find a way to empty my stomach."),
    ],
    notes: [{ hanzi: "纾压：台湾说法，大陆多说减压、解压。", en: "纾压 is Taiwan for relieving stress; mainland speech usually uses 减压 / 解压." }],
    coreVocabulary: LESSON_4_5_CORE_VOCAB,
    chunks: LESSON_4_5_CHUNKS,
    expressionFamily: { title: "一套愿望说法", titleEn: "One family of wish expressions", items: LESSON_4_5_FAMILY },
    grammarFocus: LESSON_4_5_GRAMMAR_FOCUS,
    practiceSentences: LESSON_4_5_PRACTICE,
    fillBlanks: LESSON_4_5_FILL_BLANKS,
    vocabulary: [
      v("放空", "to empty the mind; zone out"),
      v("愿望", "wish"),
      v("许愿", "to make a wish"),
      v("志向", "ambition"),
      v("期望", "expectation"),
      v("阿拉丁", "Aladdin"),
      v("神灯", "magic lamp"),
      v("还愿", "to fulfill a vow"),
      v("掷筊", "to cast moon blocks (divination)"),
      v("烧香", "to burn incense"),
      v("拜佛", "to worship Buddha"),
      v("上帝", "God"),
      v("神明", "gods; deities"),
      v("新希望", "new hope / resolution"),
      v("景气", "the economic climate"),
      v("以为", "to think (wrongly)"),
      v("全马", "full marathon"),
      v("半马", "half marathon"),
      v("清单", "list"),
    ],
    questions: [
      q(1, "请说两个你目前生活最大的愿望。如果只能选择其中一个来实现，那将是什么？为什么？", "Name two biggest current wishes. If you could have only one, which, and why?"),
      q(2, "你小时候的志向是什么？长大后改变了吗？", "What was your childhood ambition? Did it change?"),
      q(3, "你小时候的愿望实现了吗？", "Did your childhood wishes come true?"),
      q(4, "你现在的工作和你小时候的志愿一样吗？", "Is your job the same as your childhood vocation?"),
      q(5, "你父母对你有什么期望？", "What expectations do your parents have for you?"),
      q(6, "你担心自己和家人的未来吗？", "Do you worry about your future and your family’s?"),
      q(7, "你上一次吹熄生日蛋糕的蜡烛时许愿了吗？实现了吗？", "Last birthday candles — did you wish? Did it come true?"),
      q(8, "如果你有一个愿望，但你的家人不同意，你会怎么办？", "If you had a wish your family disagreed with, what would you do?"),
      q(9, "如果阿拉丁神灯灯神给你三个愿望，你会许什么愿？", "If Aladdin’s lamp gave you three wishes, what would you wish?"),
      q(10, "你在许愿池许过愿吗？愿望达成了吗？", "Have you wished at a wishing well? Did it come true?"),
      q(11, "你去宗教设施许过愿吗？怎么许愿，要还愿吗？", "Have you wished at a religious site? How, and do you repay the vow?"),
      q(12, "你的文化有带护身符的习惯吗？你有吗？护身符大多祈求什么？", "Does your culture wear amulets? Do you? What do they usually ask for?"),
      q(13, "你每年新年都有新希望吗？你有计划地确实执行吗？", "Do you set a resolution every New Year? Do you actually carry it out?"),
      q(14, "你觉得贵国的未来如何？", "How do you see your country’s future?"),
      q(15, "你觉得明年的景气会更好、更差，还是一样？", "Will next year’s economy be better, worse, or the same?"),
      q(16, "你的愿望通常都能实现吗？", "Do your wishes usually come true?"),
      q(17, "你去年的“新年新希望”是什么？达成了吗？", "What was last year’s resolution? Did you hit it?"),
      q(18, "今年的目标完成得怎么样了？你想怎么做以达成目标？", "How are this year’s goals going? What will you do to hit them?"),
      q(19, "你想改变你现在的生活方式吗？", "Do you want to change how you live now?"),
      q(20, "如果今年可以改变一件事，你希望是什么事？", "If you could change one thing this year, what?"),
      q(21, "你相信“有志者事竟成”吗？", "Do you believe “where there’s a will there’s a way”?"),
      q(22, "给未来（十年或二十年后）的自己写一封信（或说一段话）。", "Write (or say) a letter to yourself in ten or twenty years."),
      q(23, "给过去（十年前或二十年前）的自己写一封信（或说一段话）。", "Write (or say) a letter to yourself ten or twenty years ago."),
      q(24, "如果你必须列一张一百个人生愿望的清单，举其中三个你觉得应该跟一般人不太一样（老师或语伴会感到惊讶）的。", "If you listed 100 life wishes, name three that would surprise a teacher or language partner."),
    ],
  },
  {
    id: "4-6",
    unitId: 4,
    title: "到目前为止的人生",
    titleEn: "Life so far",
    pageStart: 56,
    audioId: "4-6",
    scenario: {
      time: "校友会",
      timeEn: "An alumni gathering",
      location: "餐厅",
      locationEn: "A restaurant",
      participants: "和高中同学",
      participantsEn: "With high-school classmates",
      topic: "聊往事",
      topicEn: "Talking about the old days",
    },
    dialogue: [
      notedLine(LESSON_4_6_LINE_NOTES, "A", "真的好久不见了，二十年了！", "It really has been a long time — twenty years!"),
      notedLine(LESSON_4_6_LINE_NOTES, "B", "是啊，我记得你以前吉他弹得超好，现在还弹吗？", "Yeah. I remember you used to play guitar extremely well. Do you still?"),
      notedLine(
        LESSON_4_6_LINE_NOTES,
        "A",
        "不弹了，歌偶尔会唱，跟同事去 KTV。你呢，你一直都是优秀学生，成绩很好，现在在哪工作？",
        "Not anymore. I still sing now and then — KTV with colleagues. You were always an outstanding student. Where do you work now?",
      ),
      notedLine(LESSON_4_6_LINE_NOTES, "B", "很普通的公司职员而已，负责行销〔营销〕业务。这是我的名片。", "Just an ordinary office worker, in charge of marketing. Here’s my card."),
      notedLine(LESSON_4_6_LINE_NOTES, "A", "外商！一点都不普通！我真后悔以前没好好学英语！", "A foreign firm! Not ordinary at all. I really regret I didn’t study English properly!"),
      notedLine(LESSON_4_6_LINE_NOTES, "B", "你更厉害，自己开公司？！", "You’re even more impressive — you started a company?!"),
      notedLine(LESSON_4_6_LINE_NOTES, "A", "小贸易公司而已。", "Just a small trading company."),
      notedLine(
        LESSON_4_6_LINE_NOTES,
        "B",
        "听说班导这几年身体不好，来不了。如果时光可以倒流，我一定会对她好一点。",
        "I heard the homeroom teacher’s health has been poor these years — she couldn’t come. If time could run backward, I would treat her better.",
      ),
      notedLine(
        LESSON_4_6_LINE_NOTES,
        "A",
        "是啊，我们以前太调皮了，常惹她生气，说不定是几十年来被学生气出病的。",
        "Yeah. We were too naughty. We often made her angry. Maybe decades of students made her ill.",
      ),
      notedLine(LESSON_4_6_LINE_NOTES, "B", "不知道能不能去探望她。", "I wonder if we can go visit her."),
    ],
    coreVocabulary: LESSON_4_6_CORE_VOCAB,
    chunks: LESSON_4_6_CHUNKS,
    expressionFamily: { title: "一套人生回顾说法", titleEn: "One family of life-so-far expressions", items: LESSON_4_6_FAMILY },
    grammarFocus: LESSON_4_6_GRAMMAR_FOCUS,
    practiceSentences: LESSON_4_6_PRACTICE,
    fillBlanks: LESSON_4_6_FILL_BLANKS,
    vocabulary: [
      v("记忆", "memory"),
      v("命名", "to name; naming"),
      v("时光倒流", "time flowing backward"),
      v("值得", "to be worth"),
      v("纪念", "to commemorate"),
      v("后悔", "to regret"),
      v("骄傲", "proud; pride"),
      v("墓志铭", "epitaph"),
      v("惹生气", "to make (someone) angry"),
    ],
    questions: [
      q(1, "你的出生地是？你在那里住多久了？", "Where is your birthplace? How long did you live there?"),
      q(2, "你是如何被命名的？", "How were you named?"),
      q(3, "你最早的记忆是什么？", "What’s your earliest memory?"),
      q(4, "你的家乡有什么变化？", "How has your hometown changed?"),
      q(5, "你喜欢你的中学生活吗？（初中和高中）", "Did you like middle school and high school?"),
      q(6, "你喜欢大学生活吗？", "Do you / did you like university life?"),
      q(7, "说说你的童年时光，印象最深刻的是什么？", "Talk about childhood. What left the deepest mark?"),
      q(8, "你第一次工作领薪水是什么时候做什么？", "When was your first paid job, and what was it?"),
      q(9, "你结婚了吗？你和你的配偶是怎么认识的？", "Are you married? How did you meet your spouse?"),
      q(10, "哪个对你更重要？婚姻还是工作？", "Which matters more — marriage or work?"),
      q(11, "你曾经做过什么重大决定？", "What major decisions have you made?"),
      q(12, "如果时光可以倒流，你想改变什么？", "If time could run backward, what would you change?"),
      q(13, "请用一句话来形容你到目前为止的人生。", "Describe your life so far in one sentence."),
      q(14, "到目前为止的人生，你觉得最值得纪念或骄傲的事是什么？", "In your life so far, what is most worth remembering or being proud of?"),
      q(15, "到目前为止的人生，你最后悔的事是什么？", "In your life so far, what do you regret most?"),
      q(16, "如果要为自己写一篇墓志铭死后让人纪念，你想写什么样的内容？", "If you wrote your own epitaph, what would it say?"),
      q(17, "你曾经在正式场合致词吗？（什么场合？）", "Have you spoken at a formal occasion? Which?"),
      q(18, "你还有跟小时候的玩伴联络吗？", "Are you still in touch with childhood playmates?"),
      q(19, "如果你得去一个无人岛一年而且只能带三样东西，你要带什么？", "A year on a deserted island, only three things — what do you take?"),
      q(20, "试完成一首诗：我是……我想知道……我听到……我想要……我是…… / 我是……我假装是……我试着……我梦到……我希望……我是……", "Finish a poem: I am… I want to know… I hear… I want… I am… / I am… I pretend… I try… I dream… I hope… I am…"),
    ],
  },
  {
    id: "4-7",
    unitId: 4,
    title: "让陌生人迅速相爱的三十六个问题",
    titleEn: "36 questions for strangers",
    pageStart: 58,
    audioId: "4-7",
    scenario: {
      time: "情人节未婚联谊",
      timeEn: "A Valentine’s singles mixer",
      location: "活动会场",
      locationEn: "The event venue",
      participants: "初次见面的男女",
      participantsEn: "A man and a woman meeting for the first time",
      topic: "轮流回答问题",
      topicEn: "Taking turns answering questions",
    },
    dialogue: [
      notedLine(
        LESSON_4_7_LINE_NOTES,
        "A",
        "14 题，我一直想去北欧周游和看极光！可是很难请长假去，你呢？",
        "Question 14: I’ve always wanted to travel Northern Europe and see the aurora. But it’s hard to take a long leave. You?",
      ),
      notedLine(LESSON_4_7_LINE_NOTES, "B", "有点类似，我想去南极，得努力存钱。", "Somewhat similar. I want to go to Antarctica. I have to save hard."),
      notedLine(
        LESSON_4_7_LINE_NOTES,
        "A",
        "15 题，最大的成就，hmm，应该是我开发的一个新程式〔程序〕被高价买下。",
        "Question 15, greatest achievement — hmm, a new program I built was bought at a high price.",
      ),
      notedLine(LESSON_4_7_LINE_NOTES, "B", "好酷，我好像没有这么大的成就，出过两本书，勉强算成就吧。", "Cool. I don’t seem to have one that big. I’ve published two books — that barely counts."),
      notedLine(LESSON_4_7_LINE_NOTES, "A", "出书是大成就啊！哪一方面的书？", "Publishing a book is a big achievement! What kind?"),
      notedLine(LESSON_4_7_LINE_NOTES, "B", "有关华语教学的。", "Ones about teaching Chinese."),
      notedLine(LESSON_4_7_LINE_NOTES, "A", "厉害！下次我有外国客户要学华语介绍给你。", "Nice! Next time I have a foreign client who wants Chinese, I’ll send them to you."),
      notedLine(LESSON_4_7_LINE_NOTES, "B", "好啊！谢谢。16 题，友情中最重视的是什么，hmm，你先说吧。", "Sure — thanks. Question 16, what do you value most in friendship — hmm, you go first."),
      notedLine(LESSON_4_7_LINE_NOTES, "A", "我最重视的是真诚、不背叛、会互相帮助。你呢？", "What I value most is sincerity, no betrayal, and helping each other. You?"),
      notedLine(
        LESSON_4_7_LINE_NOTES,
        "B",
        "我最喜欢的一句话是“一期一会”，我珍惜相处的每一个瞬间。",
        "My favorite line is “一期一会.” I cherish every moment we spend together.",
      ),
    ],
    notes: [
      {
        hanzi: "说明：参考 Mandy Len Catron《如何快速与陌生人相爱》。三十六题分三组，由浅入深。互问之后要对视2～4分钟。",
        en: "After Mandy Len Catron’s “To Fall in Love With Anyone, Do This.” Three sets, shallow to deep. Then hold eye contact for 2–4 minutes.",
      },
    ],
    coreVocabulary: LESSON_4_7_CORE_VOCAB,
    chunks: LESSON_4_7_CHUNKS,
    expressionFamily: { title: "一套快速升温说法", titleEn: "One family of fast-intimacy expressions", items: LESSON_4_7_FAMILY },
    grammarFocus: LESSON_4_7_GRAMMAR_FOCUS,
    practiceSentences: LESSON_4_7_PRACTICE,
    fillBlanks: LESSON_4_7_FILL_BLANKS,
    vocabulary: [
      v("陌生", "unfamiliar; a stranger"),
      v("一见钟情", "love at first sight"),
      v("坦露自我", "to reveal oneself"),
      v("快速升温", "to heat up quickly"),
      v("尴尬", "awkward"),
      v("萍水之交", "a chance acquaintance"),
      v("三观相合", "values align"),
      v("三观不合", "values clash"),
      v("把妹", "to pick up girls (slang)"),
      v("撩汉", "to flirt with men (slang)"),
      v("脱单", "to stop being single"),
      v("深层", "deep-level"),
      v("升温", "to warm up"),
    ],
    questions: [
      q(1, "如果可以在世界上所有人中任意选择，你想邀请谁共进晚餐？", "If you could choose anyone on earth, who would you invite to dinner?"),
      q(2, "你希望自己出名吗？希望自己以什么方式出名？", "Do you want to be famous? In what way?"),
      q(3, "打电话之前你会先排练一下要说什么吗？为什么？", "Before a phone call, do you rehearse what you’ll say? Why?"),
      q(4, "对你来说，“完美”的一天是什么样的？", "What would a “perfect” day be for you?"),
      q(5, "你上一次唱歌给自己听是什么时候？上一次唱给别人听呢？", "When did you last sing to yourself? To someone else?"),
      q(6, "如果你能够活到90岁，而你能选择保有30岁的身体或30岁的心灵活力，你会选择哪个？", "If you lived to 90 and could keep a 30-year-old body or a 30-year-old mind, which?"),
      q(7, "你对于自己将如何死去，是否曾有过神秘的预感？", "Have you ever had a secret hunch about how you will die?"),
      q(8, "说出三件你和对方看上去相同的特征。", "Name three things you and the other person appear to have in common."),
      q(9, "在人生中，你最感激的事情是什么？", "What in your life are you most grateful for?"),
      q(10, "如果你能改变你成长过程中的任何一件事，你会想改变什么？", "If you could change anything about how you were raised, what?"),
      q(11, "花4分钟时间，尽可能详细告诉对方你的人生经历。", "Take four minutes and tell your life story in as much detail as you can."),
      q(12, "如果你明天一觉醒来就能拥有某种才能或能力，你希望是什么？", "If you woke up tomorrow with one new quality or ability, what would you want?"),
      q(13, "如果有一个水晶球可以告诉你关于自己、人生和任何事情的真相，你会想知道吗？", "If a crystal ball could tell the truth about you, life, or anything — would you want to know?"),
      q(14, "有没有什么事是你一直梦想去做而没有去做的，为什么没有做？", "Is there something you’ve always dreamed of doing but haven’t? Why not?"),
      q(15, "你人生中最大的成就是什么？", "What is the greatest achievement of your life?"),
      q(16, "在友情中，你最重视的事情是什么？", "In friendship, what do you value most?"),
      q(17, "你人生中最珍惜的回忆是什么？", "What is your most cherished memory?"),
      q(18, "你人生中最糟糕的一段回忆是什么？", "What is your worst memory?"),
      q(19, "假如你知道自己在一年内就会突然死去，你会改变现在的生活方式吗？为什么？", "If you knew you would die suddenly within a year, would you change how you live? Why?"),
      q(20, "友情对于你的意义是什么？", "What does friendship mean to you?"),
      q(21, "爱情和情感在你人生中扮演着什么样的角色？", "What role do love and feeling play in your life?"),
      q(22, "轮流说对方的五个正向特质。", "Take turns naming five positive traits of the other person."),
      q(23, "你们的家庭关系如何？你会觉得自己比其他家庭的孩子更幸福吗？", "How is your family? Do you feel happier than children from other families?"),
      q(24, "你和母亲之间的关系是怎样的？", "What is your relationship with your mother like?"),
      q(25, "每人用“我们”造三个句子，并含有实际情况，比如：“我们俩在屋子里，感觉……”", "Each person makes three “we” sentences grounded in now, e.g. “The two of us are in this room, feeling…”"),
      q(26, "补完这个句子：“我希望有人能与我共享……”", "Finish: “I wish I had someone with whom I could share…”"),
      q(27, "如果你想和对方成为亲近的朋友，请告诉对方有什么重要的事情是他或她需要知道的。", "If you want to become close friends, tell them something important they need to know."),
      q(28, "诚实地告诉对方你喜欢他的地方。（诚实到甚至不可能跟初次见面的人说这些话的程度）", "Honestly say what you like about them — more honestly than you would with a stranger."),
      q(29, "分享你人生中最尴尬的时刻。", "Share the most embarrassing moment of your life."),
      q(30, "你上一次在别人面前哭泣是什么时候？还是你自己一个人哭泣？", "When did you last cry in front of someone? Or did you cry alone?"),
      q(31, "告诉对方，你已经开始喜欢他的某些特质。", "Tell them you have already started to like certain traits of theirs."),
      q(32, "对于你而言，哪些事情开不得玩笑？", "For you, what topics are off-limits for jokes?"),
      q(33, "如果你今晚就会死去，死去前没有机会再与任何人沟通，你会最后悔没和谁说什么话？为什么这些话你不及早跟他说？", "If you died tonight with no more words, who would you most regret not speaking to, and why haven’t you?"),
      q(34, "假设你拥有的全部东西都在你的房子里，现在房子着了火，救出家人和宠物之后，你还有机会安全地冲进去最后一次，取出最后一件东西，你会拿什么？为什么？", "House on fire. After family and pets, one last object — what, and why?"),
      q(35, "你的家人中，谁去世了会令你最伤心，为什么？", "Whose death in your family would hurt you most, and why?"),
      q(36, "分享一个你的私人困扰，并请对方给你一些建议。接着问他对于你的私人困扰的看法。", "Share a private trouble, ask for advice, then ask how they see that trouble."),
    ],
  },
]

for (const lesson of UNIT_4) assertLessonReady(lesson)
